# Generated by Django 6.0.5 on 2026-06-02 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='agency_type',
            field=models.CharField(choices=[('agencia', 'Agência'), ('representante', 'Representante'), ('operadora', 'Operadora'), ('parceiro', 'Parceiro'), ('outro', 'Outro')], default='agencia', max_length=20, verbose_name='Tipo de cadastro'),
        ),
        migrations.AddField(
            model_name='agency',
            name='cep',
            field=models.CharField(blank=True, max_length=10, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='agency',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='agency',
            name='commission_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Comissão %'),
        ),
        migrations.AddField(
            model_name='agency',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Razão social'),
        ),
        migrations.AddField(
            model_name='agency',
            name='complement',
            field=models.CharField(blank=True, max_length=100, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='agency',
            name='country',
            field=models.CharField(blank=True, default='Brasil', max_length=100, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='agency',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='agency',
            name='municipal_registration',
            field=models.CharField(blank=True, max_length=50, verbose_name='Inscrição municipal'),
        ),
        migrations.AddField(
            model_name='agency',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='agency',
            name='number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='agency',
            name='person_type',
            field=models.CharField(choices=[('juridica', 'Jurídica'), ('fisica', 'Física')], default='juridica', max_length=10, verbose_name='Tipo de pessoa'),
        ),
        migrations.AddField(
            model_name='agency',
            name='pix_key',
            field=models.CharField(blank=True, max_length=200, verbose_name='Chave PIX'),
        ),
        migrations.AddField(
            model_name='agency',
            name='pix_key_type',
            field=models.CharField(blank=True, choices=[('', 'Selecione'), ('cpf', 'CPF'), ('cnpj', 'CNPJ'), ('email', 'E-mail'), ('telefone', 'Telefone'), ('aleatorio', 'Chave aleatória')], max_length=20, verbose_name='Tipo de chave PIX'),
        ),
        migrations.AddField(
            model_name='agency',
            name='receives_mail',
            field=models.BooleanField(default=False, verbose_name='Receber mala direta impressa'),
        ),
        migrations.AddField(
            model_name='agency',
            name='state',
            field=models.CharField(blank=True, max_length=50, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='agency',
            name='state_registration',
            field=models.CharField(blank=True, max_length=50, verbose_name='Inscrição estadual'),
        ),
        migrations.AddField(
            model_name='agency',
            name='street',
            field=models.CharField(blank=True, max_length=200, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='agency',
            name='use_andes_banking',
            field=models.BooleanField(default=False, verbose_name='Utilizar dados bancários da Andes'),
        ),
        migrations.AddField(
            model_name='agency',
            name='website',
            field=models.URLField(blank=True, max_length=300, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome fantasia'),
        ),
    ]
