# Generated by Django 6.0.5 on 2026-06-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0002_add_agency_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nome fantasia'),
        ),
    ]
