# Generated by Django 6.0.5 on 2026-06-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0003_name_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='cpf',
            field=models.CharField(blank=True, max_length=20, verbose_name='CPF'),
        ),
    ]
