# Generated by Django 6.0.5 on 2026-06-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0004_add_cpf_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Sobrenome'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nome / Nome fantasia'),
        ),
    ]
