# Generated by Django 6.0.5 on 2026-06-02 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0005_add_last_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('operator', 'Operador'), ('viewer', 'Visualizador')], default='operator', max_length=20, verbose_name='Função')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Adicionado em')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='agencies.agency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membro da agência',
                'unique_together': {('agency', 'user')},
            },
        ),
    ]
