# Generated by Django 6.0.5 on 2026-06-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0007_clear_fisica_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Excluído em'),
        ),
        migrations.AddField(
            model_name='agency',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Excluído'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nome / Nome fantasma'),
        ),
    ]
