# Generated by Django 6.0.5 on 2026-07-01 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0008_agency_deleted_at_agency_is_deleted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agencies_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='status',
            field=models.CharField(choices=[('active', 'Ativa'), ('pending', 'Pendente'), ('inactive', 'Inativa'), ('rascunho', 'Rascunho')], default='active', max_length=10, verbose_name='Status'),
        ),
    ]
