# Generated by Django 6.0.6 on 2026-07-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0009_agency_created_by_alter_agency_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='use_uneworld_pix',
            field=models.BooleanField(default=False, verbose_name='Usar o PIX da UneWorld no contrato'),
        ),
    ]
