# Generated by Django 6.0.6 on 2026-07-02 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0010_agency_use_uneworld_pix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='use_andes_banking',
        ),
    ]
