# Generated by Django 6.0.6 on 2026-07-08 03:36

import agencies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0012_remove_agency_use_uneworld_pix_agency_use_agency_pix'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=agencies.models.agency_logo_path, verbose_name='Logo'),
        ),
    ]
