# Generated by Django 6.0.6 on 2026-07-09 19:44

import agencies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0013_agency_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='logo_crop',
            field=models.JSONField(blank=True, default=dict, verbose_name='Recorte da logo'),
        ),
        migrations.AddField(
            model_name='agency',
            name='logo_original',
            field=models.ImageField(blank=True, null=True, upload_to=agencies.models.agency_logo_path, verbose_name='Logo (original)'),
        ),
    ]
