# Generated by Django 6.0.6 on 2026-07-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0014_agency_logo_crop_agency_logo_original'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='autentique_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail da conta Autentique da agência'),
        ),
        migrations.AddField(
            model_name='agency',
            name='autentique_token',
            field=models.CharField(blank=True, max_length=255, verbose_name='Token de assinatura (Autentique) da agência'),
        ),
        migrations.AddField(
            model_name='agency',
            name='auto_sign',
            field=models.BooleanField(default=False, verbose_name='Assinar automaticamente os contratos digitais'),
        ),
    ]
