# Generated by Django 5.2.15 on 2026-07-16 18:02

import agencies.models
import core.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0014_agency_logo_crop_agency_logo_original'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=core.storages.public_media_storage, upload_to=agencies.models.agency_logo_path, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='logo_original',
            field=models.ImageField(blank=True, null=True, storage=core.storages.public_media_storage, upload_to=agencies.models.agency_logo_path, verbose_name='Logo (original)'),
        ),
    ]
