# Generated by Django 6.0.6 on 2026-07-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0015_agency_autentique_email_agency_autentique_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='auto_sign_allowed',
            field=models.BooleanField(default=False, verbose_name='Operadora permite assinatura automática'),
        ),
    ]
