# Generated by Django 6.0.6 on 2026-07-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0016_agency_auto_sign_allowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='auto_sign_allowed',
            field=models.BooleanField(default=True, verbose_name='Operadora permite assinatura automática'),
        ),
    ]
