# Generated by Django 6.0.6 on 2026-07-25 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0015_alter_agency_logo_alter_agency_logo_original'),
        ('agencies', '0017_alter_agency_auto_sign_allowed'),
    ]

    operations = [
    ]
