# Generated by Django 6.0.6 on 2026-08-01 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Nome')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], db_index=True, default='ativo', max_length=10, verbose_name='Status')),
                ('category', models.CharField(blank=True, choices=[('operadora', 'Operadora'), ('receptivo', 'Receptivo'), ('hotel', 'Hotel'), ('consolidador', 'Consolidador'), ('cia_aerea', 'Cia Aérea'), ('locadora', 'Locadora'), ('outros', 'Outros')], db_index=True, default='', max_length=20, verbose_name='Categoria')),
                ('airline_abbr', models.CharField(blank=True, default='', max_length=10, verbose_name='Abreviatura Cia')),
                ('city', models.CharField(blank=True, default='', max_length=120, verbose_name='Cidade')),
                ('country', models.CharField(blank=True, default='', max_length=120, verbose_name='País')),
                ('cpf', models.CharField(blank=True, db_index=True, default='', max_length=11, verbose_name='CPF')),
                ('cnpj', models.CharField(blank=True, db_index=True, default='', max_length=14, verbose_name='CNPJ')),
                ('company_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Razão Social')),
                ('supplier_network', models.CharField(blank=True, default='', max_length=200, verbose_name='Rede Fornecedor')),
                ('legacy_code', models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='Código legado')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fornecedores_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['status', 'category'], name='forn_status_cat_idx'), models.Index(fields=['name'], name='forn_name_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('legacy_code', ''), _negated=True)), fields=('legacy_code',), name='uniq_fornecedor_legacy_code')],
            },
        ),
    ]
