# Generated by Django 6.0.6 on 2026-08-01 19:23

from django.db import migrations, models


def backfill_person_type(apps, schema_editor):
    # Registros já importados: quem tem só CPF vira 'fisica'; o resto fica 'juridica'.
    Fornecedor = apps.get_model('fornecedores', 'Fornecedor')
    Fornecedor.objects.exclude(cpf='').filter(cnpj='').update(person_type='fisica')


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='person_type',
            field=models.CharField(choices=[('juridica', 'Pessoa Jurídica'), ('fisica', 'Pessoa Física')], default='juridica', max_length=10, verbose_name='Tipo de pessoa'),
        ),
        migrations.RunPython(backfill_person_type, migrations.RunPython.noop),
    ]
