# Generated by Django 6.0.6 on 2026-08-01 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0002_fornecedor_person_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fornecedor',
            name='uniq_fornecedor_legacy_code',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='legacy_code',
        ),
    ]
