# Generated by Django 6.0.5 on 2026-06-25 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config_api', '0028_configcontinent_configitinerarycategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Nome da viagem')),
                ('slug', models.SlugField(blank=True, max_length=350, unique=True, verbose_name='Slug')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Data de início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de término')),
                ('trip_type', models.CharField(choices=[('aereo', 'Aéreo'), ('terrestre', 'Terrestre')], default='aereo', max_length=20, verbose_name='Tipo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Excluído')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Excluído em')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itineraries', to='config_api.configitinerarycategory', verbose_name='Categoria')),
                ('cities', models.ManyToManyField(blank=True, related_name='itineraries', to='config_api.configcity', verbose_name='Destinos e Cidades')),
                ('continent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itineraries', to='config_api.configcontinent', verbose_name='Continente')),
                ('countries', models.ManyToManyField(blank=True, related_name='itineraries', to='config_api.configcountry', verbose_name='Países')),
            ],
            options={
                'verbose_name': 'Roteiro',
                'verbose_name_plural': 'Roteiros',
                'ordering': ['-created_at'],
            },
        ),
    ]
