# Generated by Django 6.0.5 on 2026-06-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0029_configdestination'),
        ('itineraries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='cities',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='destinations',
            field=models.ManyToManyField(blank=True, related_name='itineraries', to='config_api.configdestination', verbose_name='Destinos e Cidades'),
        ),
    ]
