# Generated by Django 6.0.5 on 2026-06-25 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0031_configholiday'),
        ('itineraries', '0002_remove_itinerary_cities_itinerary_destinations'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='cover_title',
            field=models.CharField(blank=True, max_length=300, verbose_name='Título da capa'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='holiday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itineraries', to='config_api.configholiday', verbose_name='Feriado'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='internal_title',
            field=models.TextField(blank=True, verbose_name='Título interno completo'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Roteiro ativo?'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Destaque na home?'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='is_full',
            field=models.BooleanField(default=False, verbose_name='Roteiro lotado?'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='is_listed',
            field=models.BooleanField(default=True, verbose_name='Listado no website?'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='short_description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Breve descrição'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='subtitle',
            field=models.CharField(blank=True, max_length=500, verbose_name='Subtítulo'),
        ),
    ]
