# Generated by Django 6.0.5 on 2026-06-25 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0032_configservice'),
        ('itineraries', '0003_itinerary_cover_title_itinerary_holiday_and_more'),
        ('trips', '0038_room_same_sex_ack'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='additional_spread_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Spread adicional em %'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='base_currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'Dólar'), ('BRL', 'Real')], default='EUR', max_length=3, verbose_name='Moeda base'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='cash_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Desconto à vista em %'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='day_count_correction',
            field=models.IntegerField(default=0, verbose_name='Correção contagem de dias'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='has_notice',
            field=models.BooleanField(default=False, verbose_name='Aviso'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='notice_color',
            field=models.CharField(choices=[('laranja', 'Laranja'), ('vermelho', 'Vermelho'), ('verde', 'Verde'), ('azul', 'Azul'), ('cinza', 'Cinza')], default='laranja', max_length=20, verbose_name='Cor do aviso'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='notice_message',
            field=models.CharField(blank=True, max_length=300, verbose_name='Mensagem do aviso'),
        ),
        migrations.CreateModel(
            name='ItineraryServiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Percentual %')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_lines', to='itineraries.itinerary')),
                ('services', models.ManyToManyField(blank=True, related_name='+', to='config_api.configservice', verbose_name='Serviços')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='trips.supplier', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Linha de serviço',
                'verbose_name_plural': 'Linhas de serviço',
                'ordering': ['order'],
            },
        ),
    ]
