# Generated by Django 6.0.5 on 2026-06-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0004_itinerary_additional_spread_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='about_destination',
            field=models.TextField(blank=True, verbose_name='Sobre o destino'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='day_by_day',
            field=models.TextField(blank=True, verbose_name='Dia a dia'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='documentation_info',
            field=models.TextField(blank=True, verbose_name='Documentação necessária para a viagem'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='extras',
            field=models.TextField(blank=True, verbose_name='Extras'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='hotels_reserved',
            field=models.TextField(blank=True, verbose_name='Hotéis reservados'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='insurance_info',
            field=models.TextField(blank=True, verbose_name='Adicional de seguro viagem'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='package_excludes',
            field=models.TextField(blank=True, verbose_name='O que não inclui no pacote'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='package_includes',
            field=models.TextField(blank=True, verbose_name='O que inclui no pacote'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='payment_info',
            field=models.TextField(blank=True, verbose_name='Forma de pagamento'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='pricing_info',
            field=models.TextField(blank=True, verbose_name='Informações sobre valores'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='terms_info',
            field=models.TextField(blank=True, verbose_name='Condições gerais para compra do pacote'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='transport_info',
            field=models.TextField(blank=True, verbose_name='Parte aérea / rodoviária'),
        ),
    ]
