# Generated by Django 6.0.5 on 2026-06-29 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0041_configexchangerate_rate_updated_at'),
        ('itineraries', '0005_itinerary_about_destination_itinerary_day_by_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryAccommodationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_per_person', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor por pessoa')),
                ('taxes', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Taxas')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('accommodation_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='config_api.configaccommodation', verbose_name='Tipo de acomodação')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodation_lines', to='itineraries.itinerary')),
            ],
            options={
                'verbose_name': 'Linha de acomodação',
                'verbose_name_plural': 'Linhas de acomodação',
                'ordering': ['order'],
            },
        ),
    ]
