# Generated by Django 6.0.5 on 2026-06-30 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0041_configexchangerate_rate_updated_at'),
        ('itineraries', '0006_itineraryaccommodationline'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='clauses',
            field=models.ManyToManyField(blank=True, related_name='itineraries', to='config_api.contractclause', verbose_name='Cláusulas do contrato'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='custom_clauses',
            field=models.JSONField(blank=True, default=list, verbose_name='Cláusulas personalizadas'),
        ),
    ]
