# Generated by Django 6.0.6 on 2026-07-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0007_itinerary_clauses_itinerary_custom_clauses'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='payment_plan',
            field=models.JSONField(blank=True, null=True, verbose_name='Sugestão de pagamento'),
        ),
    ]
