# Generated by Django 6.0.6 on 2026-07-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0008_itinerary_payment_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='payment_plans',
            field=models.JSONField(blank=True, default=list, verbose_name='Modelos de pagamento do roteiro'),
        ),
    ]
