# Generated by Django 6.0.6 on 2026-07-03 20:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0053_configcurrency_configitinerarytype_and_more'),
        ('itineraries', '0010_remove_itinerary_about_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='cities',
            field=models.ManyToManyField(blank=True, related_name='itineraries', to='config_api.configcity', verbose_name='Cidades'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='itinerary_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itineraries', to='config_api.configitinerarytype', verbose_name='Tipo de roteiro (lista)'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='maritime_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itineraries', to='config_api.configmaritimecompany', verbose_name='Companhia marítima'),
        ),
        migrations.CreateModel(
            name='ItineraryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Dia nº')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='itineraries.itinerary')),
            ],
            options={
                'verbose_name': 'Dia do roteiro',
                'verbose_name_plural': 'Dias do roteiro',
                'ordering': ['order', 'day_number'],
                'indexes': [models.Index(fields=['itinerary', 'order'], name='idx_itinday_itin_order')],
                'constraints': [models.UniqueConstraint(fields=('itinerary', 'day_number'), name='uniq_itinerary_day_number')],
            },
        ),
        migrations.CreateModel(
            name='ItineraryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='itineraries/', verbose_name='Imagem')),
                ('caption', models.CharField(blank=True, max_length=300, verbose_name='Legenda')),
                ('is_cover', models.BooleanField(default=False, verbose_name='É a capa')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='itineraries.itinerary')),
            ],
            options={
                'verbose_name': 'Imagem do roteiro',
                'verbose_name_plural': 'Imagens do roteiro',
                'ordering': ['order'],
                'indexes': [models.Index(fields=['itinerary', 'order'], name='idx_itinimg_itin_order')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_cover', True)), fields=('itinerary',), name='uniq_cover_per_itinerary')],
            },
        ),
    ]
