# Generated by Django 6.0.6 on 2026-07-03 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0053_configcurrency_configitinerarytype_and_more'),
        ('itineraries', '0011_itinerary_cities_itinerary_itinerary_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='airports',
            field=models.ManyToManyField(blank=True, related_name='itineraries', to='config_api.airport', verbose_name='Aeroportos'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='countries',
            field=models.ManyToManyField(blank=True, related_name='itineraries', to='config_api.configcountry', verbose_name='Países'),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='config_api.configcity', verbose_name='Cidade do dia'),
        ),
        migrations.AddField(
            model_name='itineraryimage',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='itineraries.itineraryday'),
        ),
        migrations.CreateModel(
            name='ItineraryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='itineraries/docs/', verbose_name='Arquivo')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='Título')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='itineraries.itinerary')),
            ],
            options={
                'verbose_name': 'Documento do roteiro',
                'verbose_name_plural': 'Documentos do roteiro',
                'ordering': ['order'],
                'indexes': [models.Index(fields=['itinerary', 'order'], name='idx_itindoc_itin_order')],
            },
        ),
    ]
