# Generated by Django 6.0.6 on 2026-07-04 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0012_itinerary_airports_itinerary_countries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='a_vista_discount_mode',
            field=models.CharField(choices=[('percent', '% do total'), ('valor', 'Valor em R$')], default='percent', max_length=10, verbose_name='Tipo do desconto à vista'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='a_vista_discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Desconto à vista (valor ou %)'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='a_vista_payment_method',
            field=models.CharField(blank=True, max_length=100, verbose_name='Forma de pagamento à vista'),
        ),
    ]
