# Generated by Django 6.0.6 on 2026-07-04 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0056_configkeyword'),
        ('itineraries', '0013_itinerary_a_vista_discount_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='itineraries', to='config_api.configkeyword', verbose_name='Palavras-chave'),
        ),
    ]
