# Generated by Django 6.0.6 on 2026-07-04 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0014_itinerary_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('ativo', 'Ativo')], db_index=True, default='ativo', max_length=20, verbose_name='Status'),
        ),
    ]
