# Generated by Django 6.0.6 on 2026-07-04 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0015_itinerary_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='is_own_product',
            field=models.BooleanField(default=True, verbose_name='Produto próprio da UneWorld'),
        ),
    ]
