# Generated by Django 6.0.6 on 2026-07-04 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0016_itinerary_is_own_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='trip_type',
            field=models.CharField(choices=[('aereo', 'Aéreo'), ('terrestre', 'Terrestre'), ('maritimo', 'Marítimo')], default='aereo', max_length=20, verbose_name='Tipo'),
        ),
    ]
