# Generated by Django 6.0.6 on 2026-07-04 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0057_configinclusion'),
        ('itineraries', '0017_alter_itinerary_trip_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='inclusions',
            field=models.ManyToManyField(blank=True, related_name='itineraries', to='config_api.configinclusion', verbose_name='Inclusos no pacote'),
        ),
    ]
