# Generated by Django 6.0.6 on 2026-07-04 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0057_configinclusion'),
        ('itineraries', '0018_itinerary_inclusions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itineraries', to='config_api.configlistcategory', verbose_name='Categoria'),
        ),
    ]
