# Generated by Django 6.0.6 on 2026-07-04 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0058_confighighlight'),
        ('itineraries', '0019_alter_itinerary_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='highlights',
            field=models.ManyToManyField(blank=True, related_name='itineraries', to='config_api.confighighlight', verbose_name='Destaques'),
        ),
    ]
