# Generated by Django 6.0.6 on 2026-07-04 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0059_configspecialdate'),
        ('itineraries', '0020_itinerary_highlights'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='itinerary_types',
            field=models.ManyToManyField(blank=True, related_name='typed_itineraries', to='config_api.configitinerarytype', verbose_name='Tipos de roteiro'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='special_dates',
            field=models.ManyToManyField(blank=True, related_name='itineraries', to='config_api.configspecialdate', verbose_name='Datas especiais'),
        ),
    ]
