# Generated by Django 6.0.6 on 2026-07-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0021_itinerary_itinerary_types_itinerary_special_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Destaque do roteiro'),
        ),
    ]
