# Generated by Django 6.0.6 on 2026-07-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0059_configspecialdate'),
        ('itineraries', '0022_itinerary_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='continents',
            field=models.ManyToManyField(blank=True, related_name='itineraries_multi', to='config_api.configcontinent', verbose_name='Continentes'),
        ),
    ]
