# Generated by Django 6.0.6 on 2026-07-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0023_itinerary_continents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='base_currency',
            field=models.CharField(default='EUR', max_length=3, verbose_name='Moeda base'),
        ),
    ]
