# Generated by Django 6.0.6 on 2026-07-04 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0024_alter_itinerary_base_currency'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='itinerarydocument',
            name='idx_itindoc_itin_order',
        ),
        migrations.DeleteModel(
            name='ItineraryDocument',
        ),
    ]
