# Generated by Django 6.0.6 on 2026-07-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0025_remove_itinerarydocument_idx_itindoc_itin_order_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='itineraryimage',
            name='uniq_cover_per_itinerary',
        ),
        migrations.AddField(
            model_name='itineraryimage',
            name='kind',
            field=models.CharField(choices=[('gallery', 'Galeria'), ('cover', 'Capa'), ('blocking', 'Lâmina do Bloqueio'), ('blocking_promo', 'Lâmina do Bloqueio Promocional')], default='gallery', max_length=20, verbose_name='Tipo'),
        ),
    ]
