# Generated by Django 6.0.6 on 2026-07-04 13:26

from django.db import migrations


def copy_iscover_to_kind(apps, schema_editor):
    Image = apps.get_model('itineraries', 'ItineraryImage')
    Image.objects.filter(is_cover=True).update(kind='cover')


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0026_remove_itineraryimage_uniq_cover_per_itinerary_and_more'),
    ]

    operations = [
        migrations.RunPython(copy_iscover_to_kind, migrations.RunPython.noop),
    ]
