# Generated by Django 6.0.6 on 2026-07-04 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0027_copy_iscover_to_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itineraryimage',
            name='is_cover',
        ),
    ]
