# Generated by Django 6.0.6 on 2026-07-04 13:46

import itineraries.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0028_remove_itineraryimage_is_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraryimage',
            name='image',
            field=models.ImageField(upload_to=itineraries.models.secure_itinerary_image_path, verbose_name='Imagem'),
        ),
    ]
