# Generated by Django 6.0.6 on 2026-07-04 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0029_alter_itineraryimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='info_documents',
            field=models.TextField(blank=True, default='', verbose_name='Documentos Necessários'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='info_general',
            field=models.TextField(blank=True, default='', verbose_name='Informações'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='info_included',
            field=models.TextField(blank=True, default='', verbose_name='Incluso no Pacote'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='info_not_included',
            field=models.TextField(blank=True, default='', verbose_name='Não Incluso no Pacote'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='info_optionals',
            field=models.TextField(blank=True, default='', verbose_name='Opcionais'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='info_promo_rules',
            field=models.TextField(blank=True, default='', verbose_name='Regras Promoção'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='info_tips',
            field=models.TextField(blank=True, default='', verbose_name='Dicas de Viagem'),
        ),
    ]
