# Generated by Django 6.0.6 on 2026-07-04 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0030_itinerary_info_documents_itinerary_info_general_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Observações'),
        ),
    ]
