# Generated by Django 6.0.6 on 2026-07-04 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0031_itinerary_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryFieldTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('included', 'Incluso no Pacote'), ('not_included', 'Não Incluso no Pacote'), ('optionals', 'Opcionais'), ('tips', 'Dicas de Viagem'), ('documents', 'Documentos Necessários'), ('promo_rules', 'Regras Promoção')], db_index=True, max_length=20, verbose_name='Campo')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do template')),
                ('content', models.TextField(blank=True, default='', verbose_name='Conteúdo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Template de campo do roteiro',
                'verbose_name_plural': 'Templates de campos do roteiro',
                'ordering': ['field', 'order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='itinerary',
            name='info_documents_template_linked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='info_included_template_linked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='info_not_included_template_linked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='info_optionals_template_linked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='info_promo_rules_template_linked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='info_tips_template_linked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='info_documents_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='itineraries.itineraryfieldtemplate'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='info_included_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='itineraries.itineraryfieldtemplate'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='info_not_included_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='itineraries.itineraryfieldtemplate'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='info_optionals_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='itineraries.itineraryfieldtemplate'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='info_promo_rules_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='itineraries.itineraryfieldtemplate'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='info_tips_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='itineraries.itineraryfieldtemplate'),
        ),
    ]
