# Generated by Django 6.0.6 on 2026-07-05 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0033_itinerary_info_general_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='info_insurance',
            field=models.TextField(blank=True, default='', verbose_name='Seguros'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='info_insurance_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='itineraries.itineraryfieldtemplate'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='info_insurance_template_linked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='itineraryfieldtemplate',
            name='field',
            field=models.CharField(choices=[('general', 'Informações'), ('included', 'Incluso no Pacote'), ('not_included', 'Não Incluso no Pacote'), ('optionals', 'Opcionais'), ('tips', 'Dicas de Viagem'), ('documents', 'Documentos Necessários'), ('promo_rules', 'Regras Promoção'), ('insurance', 'Seguros')], db_index=True, max_length=20, verbose_name='Campo'),
        ),
    ]
