# Generated by Django 6.0.6 on 2026-07-05 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0034_itinerary_info_insurance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='info_extras',
            field=models.TextField(blank=True, default='', verbose_name='Extras'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='info_extras_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='itineraries.itineraryfieldtemplate'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='info_extras_template_linked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='info_hotels',
            field=models.TextField(blank=True, default='', verbose_name='Hotéis Reservados'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='info_hotels_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='itineraries.itineraryfieldtemplate'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='info_hotels_template_linked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='info_values',
            field=models.TextField(blank=True, default='', verbose_name='Informações sobre Valores'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='info_values_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='itineraries.itineraryfieldtemplate'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='info_values_template_linked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='itineraryfieldtemplate',
            name='field',
            field=models.CharField(choices=[('general', 'Informações'), ('included', 'Incluso no Pacote'), ('not_included', 'Não Incluso no Pacote'), ('optionals', 'Opcionais'), ('tips', 'Dicas de Viagem'), ('documents', 'Documentos Necessários'), ('promo_rules', 'Regras Promoção'), ('insurance', 'Seguros'), ('values', 'Informações sobre Valores'), ('hotels', 'Hotéis Reservados'), ('extras', 'Extras')], db_index=True, max_length=20, verbose_name='Campo'),
        ),
    ]
