# Generated by Django 6.0.6 on 2026-07-05 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0060_operatingcompanycontact'),
        ('itineraries', '0035_itinerary_info_extras_itinerary_info_extras_template_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryDeparture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('airport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='config_api.airport', verbose_name='Aeroporto de saída')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='itineraries.itinerary')),
            ],
            options={
                'verbose_name': 'Aeroporto de saída do roteiro',
                'verbose_name_plural': 'Aeroportos de saída do roteiro',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(blank=True, max_length=20, verbose_name='Número do voo')),
                ('departs_at', models.DateTimeField(blank=True, null=True, verbose_name='Saída')),
                ('arrives_at', models.DateTimeField(blank=True, null=True, verbose_name='Chegada')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('airline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='config_api.airline', verbose_name='Companhia')),
                ('departure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='itineraries.itinerarydeparture')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='config_api.airport', verbose_name='Destino')),
                ('origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='config_api.airport', verbose_name='Origem')),
            ],
            options={
                'verbose_name': 'Voo do roteiro',
                'verbose_name_plural': 'Voos do roteiro',
                'ordering': ['order', 'id'],
            },
        ),
    ]
