# Generated by Django 6.0.6 on 2026-07-05 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0036_itinerarydeparture_itineraryflight'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Nome do hotel')),
                ('city', models.CharField(blank=True, max_length=200, verbose_name='Cidade')),
                ('check_in', models.DateField(blank=True, null=True, verbose_name='Check-in')),
                ('check_out', models.DateField(blank=True, null=True, verbose_name='Check-out')),
                ('address', models.CharField(blank=True, max_length=400, verbose_name='Endereço')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Telefone')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='itineraries.itinerary')),
            ],
            options={
                'verbose_name': 'Hotel do roteiro',
                'verbose_name_plural': 'Hotéis do roteiro',
                'ordering': ['order', 'id'],
            },
        ),
    ]
