# Generated by Django 6.0.6 on 2026-07-05 04:15

from django.db import migrations, models


def delete_hotels_templates(apps, schema_editor):
    """Remove os templates do campo 'hotels' (config descontinuada)."""
    ItineraryFieldTemplate = apps.get_model('itineraries', 'ItineraryFieldTemplate')
    ItineraryFieldTemplate.objects.filter(field='hotels').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0037_itineraryhotel'),
    ]

    operations = [
        migrations.RunPython(delete_hotels_templates, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='itinerary',
            name='info_hotels',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='info_hotels_template',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='info_hotels_template_linked',
        ),
        migrations.AlterField(
            model_name='itineraryfieldtemplate',
            name='field',
            field=models.CharField(choices=[('general', 'Informações'), ('included', 'Incluso no Pacote'), ('not_included', 'Não Incluso no Pacote'), ('optionals', 'Opcionais'), ('tips', 'Dicas de Viagem'), ('documents', 'Documentos Necessários'), ('promo_rules', 'Regras Promoção'), ('insurance', 'Seguros'), ('values', 'Informações sobre Valores'), ('extras', 'Extras')], db_index=True, max_length=20, verbose_name='Campo'),
        ),
    ]
