# Generated by Django 6.0.6 on 2026-07-05 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0062_confighotelcategory_confighotel'),
        ('itineraries', '0038_remove_itinerary_info_hotels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryhotel',
            name='config_hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='config_api.confighotel'),
        ),
    ]
