# Generated by Django 6.0.6 on 2026-07-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0039_itineraryhotel_config_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryhotel',
            name='config_hotel_linked',
            field=models.BooleanField(default=True),
        ),
    ]
