# Generated by Django 6.0.6 on 2026-07-05 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0067_configterrestrecompany'),
        ('itineraries', '0041_itineraryboat'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryTerrestreDeparture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='config_api.configcity', verbose_name='Cidade de partida')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terrestre_departures', to='itineraries.itinerary')),
            ],
            options={
                'verbose_name': 'Cidade de partida (terrestre)',
                'verbose_name_plural': 'Cidades de partida (terrestre)',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryTerrestreLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_number', models.CharField(blank=True, max_length=40, verbose_name='Identificação')),
                ('departs_at', models.DateTimeField(blank=True, null=True, verbose_name='Saída')),
                ('arrives_at', models.DateTimeField(blank=True, null=True, verbose_name='Chegada')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='config_api.configterrestrecompany', verbose_name='Empresa')),
                ('departure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='itineraries.itineraryterrestredeparture')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='config_api.configcity', verbose_name='Destino')),
                ('origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='config_api.configcity', verbose_name='Origem')),
            ],
            options={
                'verbose_name': 'Trecho terrestre do roteiro',
                'verbose_name_plural': 'Trechos terrestres do roteiro',
                'ordering': ['order', 'id'],
            },
        ),
    ]
