# Generated by Django 6.0.6 on 2026-07-05 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0067_configterrestre_configterrestremedia'),
        ('itineraries', '0041_itineraryboat'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryTerrestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_terrestre_linked', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=300, verbose_name='Nome')),
                ('check_in', models.DateField(blank=True, null=True, verbose_name='Check-in')),
                ('check_out', models.DateField(blank=True, null=True, verbose_name='Check-out')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('config_terrestre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='config_api.configterrestre')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terrestres', to='itineraries.itinerary')),
            ],
            options={
                'verbose_name': 'Terrestre do roteiro',
                'verbose_name_plural': 'Terrestres do roteiro',
                'ordering': ['order', 'id'],
            },
        ),
    ]
