# Generated by Django 6.0.6 on 2026-07-05 16:27

from django.db import migrations, models


def seed_transports(apps, schema_editor):
    """Preenche os meios de transporte a partir do trip_type existente, para os
    roteiros já cadastrados não perderem a aba correspondente."""
    Itinerary = apps.get_model('itineraries', 'Itinerary')
    Itinerary.objects.filter(trip_type='aereo').update(has_voo=True)
    Itinerary.objects.filter(trip_type='maritimo').update(has_barco=True)
    Itinerary.objects.filter(trip_type='terrestre').update(has_terrestre=True)


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0042_itineraryterrestredeparture_itineraryterrestreleg'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='has_barco',
            field=models.BooleanField(default=False, verbose_name='Transporte marítimo (Barco)'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='has_terrestre',
            field=models.BooleanField(default=False, verbose_name='Transporte terrestre'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='has_voo',
            field=models.BooleanField(default=False, verbose_name='Transporte aéreo (Voo)'),
        ),
        migrations.RunPython(seed_transports, migrations.RunPython.noop),
    ]
