# Generated by Django 6.0.6 on 2026-07-05 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0043_itinerary_has_barco_itinerary_has_terrestre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryaccommodationline',
            name='flight_departure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accommodation_lines', to='itineraries.itinerarydeparture', verbose_name='Partida (aéreo)'),
        ),
        migrations.AddField(
            model_name='itineraryaccommodationline',
            name='terrestre_departure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accommodation_lines', to='itineraries.itineraryterrestredeparture', verbose_name='Partida (terrestre)'),
        ),
    ]
