# Generated by Django 6.0.6 on 2026-07-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0044_itineraryaccommodationline_flight_departure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Publicado (visível ao público)'),
        ),
    ]
