# Generated by Django 6.0.6 on 2026-07-05 17:34

import django.db.models.deletion
import itineraries.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0045_itinerary_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Nome')),
                ('file', models.FileField(blank=True, null=True, upload_to=itineraries.models.secure_itinerary_document_path, verbose_name='Arquivo')),
                ('url', models.URLField(blank=True, max_length=1000, verbose_name='Link externo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('edit_key', models.CharField(blank=True, default='', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='itineraries.itinerary')),
            ],
            options={
                'verbose_name': 'Documento do roteiro',
                'verbose_name_plural': 'Documentos do roteiro',
                'ordering': ['order', 'id'],
            },
        ),
    ]
