# Generated by Django 6.0.6 on 2026-07-05 19:03

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0046_itinerarydocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='has_unpublished_changes',
            field=models.BooleanField(default=False, verbose_name='Alterações não publicadas'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Publicado em'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='published_data',
            field=models.JSONField(blank=True, default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Foto publicada'),
        ),
    ]
