# Generated by Django 6.0.6 on 2026-07-05 23:55

from django.db import migrations, models


def seed_order(apps, schema_editor):
    """Ordem inicial = ordem atual (-created_at), para não embaralhar a lista."""
    Itinerary = apps.get_model('itineraries', 'Itinerary')
    for i, it in enumerate(Itinerary.objects.order_by('-created_at')):
        it.order = i
        it.save(update_fields=['order'])


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0047_itinerary_has_unpublished_changes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itinerary',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Roteiro', 'verbose_name_plural': 'Roteiros'},
        ),
        migrations.AddField(
            model_name='itinerary',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Ordem'),
        ),
        migrations.RunPython(seed_order, migrations.RunPython.noop),
    ]
