# Generated by Django 6.0.6 on 2026-07-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0048_alter_itinerary_options_itinerary_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='map_embed_url',
            field=models.TextField(blank=True, default='', verbose_name='Mapa (link/embed do Google My Maps)'),
        ),
    ]
