# Generated by Django 6.0.6 on 2026-07-06 12:23

import itineraries.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0049_itinerary_map_embed_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraryimage',
            name='image',
            field=models.FileField(upload_to=itineraries.models.secure_itinerary_image_path, verbose_name='Arquivo (imagem/vídeo)'),
        ),
    ]
