# Generated by Django 6.0.6 on 2026-07-06 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0051_itinerary_flight_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='accommodation_notes',
            field=models.TextField(blank=True, default='', verbose_name='Observações dos Valores'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='accommodation_notes_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='itineraries.itineraryfieldtemplate'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='accommodation_notes_template_linked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='boat_notes',
            field=models.TextField(blank=True, default='', verbose_name='Observações do Barco'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='boat_notes_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='itineraries.itineraryfieldtemplate'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='boat_notes_template_linked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='hotel_notes',
            field=models.TextField(blank=True, default='', verbose_name='Observações dos Hotéis'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='hotel_notes_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='itineraries.itineraryfieldtemplate'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='hotel_notes_template_linked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='terrestre_notes',
            field=models.TextField(blank=True, default='', verbose_name='Observações do Terrestre'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='terrestre_notes_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='itineraries.itineraryfieldtemplate'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='terrestre_notes_template_linked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='itineraryfieldtemplate',
            name='field',
            field=models.CharField(choices=[('general', 'Informações'), ('included', 'Incluso no Pacote'), ('not_included', 'Não Incluso no Pacote'), ('optionals', 'Opcionais'), ('tips', 'Dicas de Viagem'), ('documents', 'Documentos Necessários'), ('promo_rules', 'Regras Promoção'), ('insurance', 'Seguros'), ('values', 'Informações sobre Valores'), ('extras', 'Extras'), ('flights', 'Observações dos Voos'), ('hotels', 'Observações dos Hotéis'), ('accommodation', 'Observações dos Valores'), ('terrestre', 'Observações do Terrestre'), ('boat', 'Observações do Barco')], db_index=True, max_length=20, verbose_name='Campo'),
        ),
    ]
