# Generated by Django 6.0.6 on 2026-07-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0052_itinerary_accommodation_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='nights_override',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Noites (manual)'),
        ),
    ]
