# Generated by Django 6.0.6 on 2026-07-06 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0071_seed_city_aliases'),
        ('itineraries', '0056_merge_blocking_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryimage',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='config_api.configcity', verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='itineraryimage',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='config_api.configcountry', verbose_name='País'),
        ),
    ]
