# Generated by Django 6.0.6 on 2026-07-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0057_itineraryimage_city_itineraryimage_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryimage',
            name='subject_type',
            field=models.CharField(blank=True, choices=[('landscape', 'Paisagem'), ('object', 'Objeto'), ('lamina', 'Lâmina')], default='', max_length=12, verbose_name='Tipo de conteúdo'),
        ),
    ]
