# Generated by Django 6.0.6 on 2026-07-06 21:54

import django.db.models.deletion
from django.db import migrations, models


VIDEO_EXTS = ('.mp4', '.webm', '.mov', '.m4v', '.ogv')


def backfill_colors(apps, schema_editor):
    """Calcula a cor dominante das imagens já existentes (best-effort; pula vídeos
    e falhas de leitura). Novas imagens já calculam no upload."""
    from itineraries.imagecolor import dominant_color
    ItineraryImage = apps.get_model('itineraries', 'ItineraryImage')
    for img in ItineraryImage.objects.all().iterator():
        name = (getattr(img.image, 'name', '') or '').lower()
        if not name or name.endswith(VIDEO_EXTS):
            continue
        hexc, bucket = '', ''
        try:
            img.image.open('rb')
            hexc, bucket = dominant_color(img.image)
        except Exception:
            pass
        finally:
            try:
                img.image.close()
            except Exception:
                pass
        if hexc:
            img.dominant_color = hexc
            img.color_bucket = bucket
            img.save(update_fields=['dominant_color', 'color_bucket'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0058_itineraryimage_subject_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryimage',
            name='color_bucket',
            field=models.CharField(blank=True, db_index=True, default='', max_length=12, verbose_name='Faixa de cor'),
        ),
        migrations.AddField(
            model_name='itineraryimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='itineraryimage',
            name='dominant_color',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Cor dominante'),
        ),
        migrations.AlterField(
            model_name='itineraryimage',
            name='itinerary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='itineraries.itinerary'),
        ),
        migrations.RunPython(backfill_colors, noop),
    ]
