# Generated by Django 6.0.6 on 2026-07-06 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0059_itineraryimage_color_bucket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='badge_color',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Cor do selo'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='badge_text',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Texto do selo'),
        ),
    ]
