# Generated by Django 6.0.6 on 2026-07-07 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0062_itinerary_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='info_lamina',
            field=models.TextField(blank=True, default='', verbose_name='Texto informativo da lâmina'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='info_lamina_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='itineraries.itineraryfieldtemplate'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='info_lamina_template_linked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='itineraryfieldtemplate',
            name='field',
            field=models.CharField(choices=[('general', 'Informações'), ('included', 'Incluso no Pacote'), ('not_included', 'Não Incluso no Pacote'), ('optionals', 'Opcionais'), ('tips', 'Dicas de Viagem'), ('documents', 'Documentos Necessários'), ('promo_rules', 'Regras Promoção'), ('insurance', 'Seguros'), ('values', 'Informações sobre Valores'), ('extras', 'Extras'), ('lamina', 'Texto informativo da lâmina'), ('flights', 'Observações dos Voos'), ('hotels', 'Observações dos Hotéis'), ('accommodation', 'Observações dos Valores'), ('terrestre', 'Observações do Terrestre'), ('boat', 'Observações do Barco')], db_index=True, max_length=20, verbose_name='Campo'),
        ),
    ]
