# Generated by Django 6.0.6 on 2026-07-07 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0063_itinerary_info_lamina_itinerary_info_lamina_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='inclusion_counts',
            field=models.JSONField(blank=True, default=dict, verbose_name='Quantidades dos inclusos'),
        ),
    ]
