# Generated by Django 6.0.6 on 2026-07-10 20:40

from django.db import migrations, models


def sync_visibility(apps, schema_editor):
    # Roteiros já publicados viram 'public'; o resto fica 'unlisted' (default).
    Itinerary = apps.get_model('itineraries', 'Itinerary')
    Itinerary.objects.filter(is_published=True).update(visibility='public')


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0014_agency_logo_crop_agency_logo_original'),
        ('itineraries', '0064_itinerary_inclusion_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='shared_agencies',
            field=models.ManyToManyField(blank=True, related_name='shared_itineraries', to='agencies.agency', verbose_name='Agências com acesso (exclusivo)'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='visibility',
            field=models.CharField(choices=[('public', 'Público'), ('unlisted', 'Não listado'), ('agencies', 'Exclusivo para agências')], db_index=True, default='unlisted', max_length=12, verbose_name='Visibilidade'),
        ),
        migrations.RunPython(sync_visibility, migrations.RunPython.noop),
    ]
