# Generated by Django 6.0.6 on 2026-07-10 23:45

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0081_operatingcompany_website'),
        ('itineraries', '0065_itinerary_shared_agencies_itinerary_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryCostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição')),
                ('category', models.CharField(choices=[('aereo', 'Aéreo'), ('hospedagem', 'Hospedagem'), ('terrestre', 'Transporte terrestre'), ('maritimo', 'Transporte marítimo'), ('guia', 'Guia'), ('receptivo', 'Receptivo'), ('alimentacao', 'Alimentação'), ('passeios', 'Passeios'), ('ingressos', 'Ingressos'), ('seguro', 'Seguro'), ('documentacao', 'Documentação'), ('vistos', 'Vistos'), ('taxas', 'Taxas'), ('marketing', 'Marketing'), ('brindes', 'Brindes'), ('operacao', 'Operação'), ('comissao', 'Comissão'), ('financeiro', 'Custo financeiro'), ('contingencia', 'Contingência'), ('outros', 'Outros')], default='outros', max_length=16, verbose_name='Categoria')),
                ('supplier', models.CharField(blank=True, default='', max_length=160, verbose_name='Fornecedor')),
                ('cost_type', models.CharField(choices=[('per_person', 'Por pessoa'), ('group', 'Do grupo')], default='per_person', max_length=12, verbose_name='Tipo de custo')),
                ('currency', models.CharField(blank=True, default='', max_length=3, verbose_name='Moeda do item')),
                ('unit_value', models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='Valor unitário')),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=12, verbose_name='Quantidade')),
                ('basis', models.CharField(choices=[('per_person', 'Por pessoa (período)'), ('per_person_night', 'Por pessoa/noite'), ('per_room', 'Por quarto (período)'), ('per_room_night', 'Por quarto/noite'), ('block_total', 'Total do bloqueio')], default='per_person', max_length=16, verbose_name='Base do preço')),
                ('occupancy', models.PositiveSmallIntegerField(default=1, verbose_name='Ocupação (divisor)')),
                ('nights', models.PositiveSmallIntegerField(default=1, verbose_name='Noites')),
                ('rateio_rule', models.CharField(choices=[('base', 'Quantidade-base'), ('custom', 'Quantidade específica'), ('departure', 'Passageiros da saída'), ('accommodation', 'Passageiros da acomodação'), ('none', 'Sem divisão (informativo)')], default='base', max_length=14, verbose_name='Regra de rateio')),
                ('rateio_qty', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade do rateio')),
                ('tax_percent', models.DecimalField(decimal_places=4, default=0, max_digits=9, verbose_name='Taxa (%)')),
                ('card_fee_percent', models.DecimalField(decimal_places=4, default=0, max_digits=9, verbose_name='Taxa de cartão (%)')),
                ('iof_percent', models.DecimalField(decimal_places=4, default=0, max_digits=9, verbose_name='IOF (%)')),
                ('iof_base', models.CharField(choices=[('original', 'Sobre o valor original'), ('with_fees', 'Sobre o valor com taxas'), ('none', 'Não aplicável')], default='with_fees', max_length=10, verbose_name='Base do IOF')),
                ('fixed_fee', models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='Taxa fixa')),
                ('payment_method', models.CharField(blank=True, default='', max_length=100, verbose_name='Forma de pagamento')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Vencimento')),
                ('included_in_price', models.BooleanField(default=True, verbose_name='Incluir no preço de venda')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('accommodation_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='config_api.configaccommodation')),
                ('flight_departure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_items', to='itineraries.itinerarydeparture')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_items', to='itineraries.itinerary')),
                ('terrestre_departure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_items', to='itineraries.itineraryterrestredeparture')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryPricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_pax', models.PositiveIntegerField(default=15, verbose_name='Quantidade-base de passageiros')),
                ('min_pax', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade mínima')),
                ('max_pax', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade máxima estimada')),
                ('free_pax', models.PositiveIntegerField(default=0, verbose_name='Passageiros gratuitos')),
                ('free_mode', models.CharField(choices=[('absorbed', 'Absorvido pelos pagantes'), ('excluded', 'Fora do rateio'), ('individual', 'Tratado individualmente')], default='absorbed', max_length=12, verbose_name='Tratamento dos gratuitos')),
                ('rounding_mode', models.CharField(choices=[('none', 'Sem arredondamento'), ('int', 'Inteiro'), ('m5', 'Múltiplo de 5'), ('m10', 'Múltiplo de 10'), ('m50', 'Múltiplo de 50'), ('m100', 'Múltiplo de 100'), ('custom', 'Personalizado')], default='none', max_length=8, verbose_name='Arredondamento')),
                ('rounding_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='Arredondar para múltiplo de')),
                ('margin_mode', models.CharField(choices=[('markup', 'Markup sobre o custo'), ('margin', 'Margem sobre a venda')], default='markup', max_length=8, verbose_name='Estratégia de preço')),
                ('margin_percent', models.DecimalField(decimal_places=4, default=Decimal('20'), max_digits=9, verbose_name='Margem/Markup (%)')),
                ('min_margin_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True, verbose_name='Margem mínima (%)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('itinerary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='itineraries.itinerary')),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryCurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3, verbose_name='Moeda')),
                ('rate', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=18, verbose_name='1 moeda = X na base')),
                ('rate_date', models.DateField(blank=True, null=True, verbose_name='Data da cotação')),
                ('source', models.CharField(blank=True, default='', max_length=120, verbose_name='Fonte')),
                ('locked', models.BooleanField(default=True, verbose_name='Cotação travada')),
                ('notes', models.CharField(blank=True, default='', max_length=200, verbose_name='Observação')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_rates', to='itineraries.itinerary')),
            ],
            options={
                'unique_together': {('itinerary', 'currency')},
            },
        ),
    ]
