# Generated by Django 6.0.6 on 2026-07-10 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0066_itinerarycostitem_itinerarypricingconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerarydeparture',
            name='expected_pax',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Passageiros previstos'),
        ),
        migrations.AddField(
            model_name='itineraryterrestredeparture',
            name='expected_pax',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Passageiros previstos'),
        ),
    ]
