# Generated by Django 6.0.6 on 2026-07-11 00:56

from decimal import Decimal
from django.db import migrations, models


def to_percent(apps, schema_editor):
    # Modos antigos (markup/margin) viram 'percent' — o fator agora é digitado.
    Cfg = apps.get_model('itineraries', 'ItineraryPricingConfig')
    Cfg.objects.exclude(margin_mode__in=['percent', 'decimal']).update(margin_mode='percent')


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0067_itinerarydeparture_expected_pax_and_more'),
    ]

    operations = [
        migrations.RunPython(to_percent, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='itinerarypricingconfig',
            name='margin_mode',
            field=models.CharField(choices=[('percent', 'Percentual'), ('decimal', 'Fator decimal')], default='percent', max_length=8, verbose_name='Tipo do markup'),
        ),
        migrations.AlterField(
            model_name='itinerarypricingconfig',
            name='margin_percent',
            field=models.DecimalField(decimal_places=4, default=Decimal('80'), max_digits=9, verbose_name='Markup (valor)'),
        ),
    ]
