# Generated by Django 6.0.6 on 2026-07-11 01:11

from django.db import migrations, models

SLUG_TO_NAME = {
    'aereo': 'Aéreo', 'hospedagem': 'Hospedagem', 'terrestre': 'Transporte terrestre',
    'maritimo': 'Transporte marítimo', 'guia': 'Guia', 'receptivo': 'Receptivo',
    'alimentacao': 'Alimentação', 'passeios': 'Passeios', 'ingressos': 'Ingressos',
    'seguro': 'Seguro', 'documentacao': 'Documentação', 'vistos': 'Vistos',
    'taxas': 'Taxas', 'marketing': 'Marketing', 'brindes': 'Brindes',
    'operacao': 'Operação', 'comissao': 'Comissão', 'financeiro': 'Custo financeiro',
    'contingencia': 'Contingência', 'outros': 'Outros',
}


def slug_to_name(apps, schema_editor):
    Item = apps.get_model('itineraries', 'ItineraryCostItem')
    for it in Item.objects.all():
        name = SLUG_TO_NAME.get(it.category)
        if name and name != it.category:
            it.category = name
            it.save(update_fields=['category'])


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0068_alter_itinerarypricingconfig_margin_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerarycostitem',
            name='card_fee_percent',
        ),
        migrations.RemoveField(
            model_name='itinerarycostitem',
            name='fixed_fee',
        ),
        migrations.RemoveField(
            model_name='itinerarycostitem',
            name='iof_base',
        ),
        migrations.RemoveField(
            model_name='itinerarycostitem',
            name='iof_percent',
        ),
        migrations.RemoveField(
            model_name='itinerarycostitem',
            name='tax_percent',
        ),
        migrations.AddField(
            model_name='itinerarycostitem',
            name='tax_kind',
            field=models.CharField(choices=[('percent', 'Percentual'), ('fixed', 'Valor fixo')], default='percent', max_length=8, verbose_name='Tipo da taxa'),
        ),
        migrations.AddField(
            model_name='itinerarycostitem',
            name='tax_value',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='Taxa (valor)'),
        ),
        migrations.AlterField(
            model_name='itinerarycostitem',
            name='category',
            field=models.CharField(blank=True, default='Outros', max_length=60, verbose_name='Categoria'),
        ),
        migrations.RunPython(slug_to_name, migrations.RunPython.noop),
    ]
