# Generated by Django 6.0.6 on 2026-07-11 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0083_configshipcabin'),
        ('itineraries', '0069_remove_itinerarycostitem_card_fee_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerarycostitem',
            name='ship_cabin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='config_api.configshipcabin'),
        ),
    ]
