# Generated by Django 6.0.6 on 2026-07-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0070_itinerarycostitem_ship_cabin'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerarycostitem',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='Câmbio do item (1 moeda = X base)'),
        ),
    ]
