# Generated by Django 6.0.6 on 2026-07-13 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0084_configflightclass_configflightsegment'),
        ('itineraries', '0071_itinerarycostitem_exchange_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerarycostitem',
            name='flight_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='config_api.configflightclass'),
        ),
        migrations.AddField(
            model_name='itinerarycostitem',
            name='flight_segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='config_api.configflightsegment'),
        ),
    ]
