# Generated by Django 6.0.6 on 2026-07-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0072_itinerarycostitem_flight_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerarycostitem',
            name='accommodation_capacity',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Capacidade da acomodação'),
        ),
    ]
