# Generated by Django 6.0.6 on 2026-07-14 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0073_itinerarycostitem_accommodation_capacity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryDocumentFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_folders', to='itineraries.itinerary')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itinerary_document_folders', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='itineraries.itinerarydocumentfolder')),
            ],
            options={
                'verbose_name': 'Pasta de documentos do roteiro',
                'verbose_name_plural': 'Pastas de documentos do roteiro',
                'ordering': ['order', 'name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='itinerarydocument',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='itineraries.itinerarydocumentfolder'),
        ),
    ]
