# Generated by Django 6.0.6 on 2026-07-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0074_itinerarydocumentfolder_itinerarydocument_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerarypricingconfig',
            name='price_overrides',
            field=models.JSONField(blank=True, default=dict, verbose_name='Valores finais sobrescritos'),
        ),
    ]
