# Generated by Django 6.0.6 on 2026-07-14 15:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0075_itinerarypricingconfig_price_overrides'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerarypricingconfig',
            name='final_fee_percent',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=9, verbose_name='Taxa final (%)'),
        ),
    ]
