# Generated by Django 6.0.6 on 2026-07-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0076_itinerarypricingconfig_final_fee_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerarycostitem',
            name='fee_capacities',
            field=models.JSONField(blank=True, default=list, verbose_name='Capacidades da taxa'),
        ),
        migrations.AddField(
            model_name='itinerarycostitem',
            name='is_fee',
            field=models.BooleanField(default=False, verbose_name='É taxa (valor separado)'),
        ),
    ]
