# Generated by Django 6.0.6 on 2026-07-14 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0086_alter_configshipcabin_options_and_more'),
        ('itineraries', '0077_itinerarycostitem_fee_capacities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryaccommodationline',
            name='accommodation_label',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Rótulo da acomodação'),
        ),
        migrations.AddField(
            model_name='itineraryaccommodationline',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacidade'),
        ),
        migrations.AddField(
            model_name='itineraryaccommodationline',
            name='ship_cabin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='config_api.configshipcabin', verbose_name='Cabine (grupo)'),
        ),
    ]
