# Generated by Django 6.0.6 on 2026-07-15 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0086_alter_configshipcabin_options_and_more'),
        ('itineraries', '0078_itineraryaccommodationline_accommodation_label_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryInventoryBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('terrestre', 'Terrestre'), ('aereo', 'Aéreo'), ('navio', 'Navio')], max_length=10, verbose_name='Tipo')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantidade (unidades no bloco)')),
                ('notes', models.CharField(blank=True, default='', max_length=200, verbose_name='Observação')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accommodations', models.ManyToManyField(blank=True, related_name='+', to='config_api.configaccommodation')),
                ('airline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='config_api.airline')),
                ('flight_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='config_api.configflightclass')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_blocks', to='itineraries.itinerary')),
                ('ship_cabin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='config_api.configshipcabin')),
            ],
            options={
                'ordering': ['kind', 'order', 'id'],
            },
        ),
    ]
