# Generated by Django 5.2.15 on 2026-07-16 18:02

import core.storages
import itineraries.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0079_itineraryinventoryblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraryimage',
            name='image',
            field=models.FileField(storage=core.storages.public_media_storage, upload_to=itineraries.models.secure_itinerary_image_path, verbose_name='Arquivo (imagem/vídeo)'),
        ),
    ]
