# Generated by Django 6.0.6 on 2026-07-21 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0093_alter_configpaymentplan_options_and_more'),
        ('itineraries', '0080_itinerary_info_required_docs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryimage',
            name='continent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='config_api.configcontinent', verbose_name='Continente'),
        ),
    ]
