# Generated by Django 5.2.15 on 2026-07-22 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0080_alter_itineraryimage_image'),
        ('itineraries', '0081_itineraryimage_continent'),
    ]

    operations = [
    ]
