# Generated by Django 6.0.6 on 2026-07-24 00:49

import itineraries.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0083_itineraryboat_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryimage',
            name='codec',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Codec de origem'),
        ),
        migrations.AddField(
            model_name='itineraryimage',
            name='detected_mime',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='MIME detectado'),
        ),
        migrations.AddField(
            model_name='itineraryimage',
            name='duration',
            field=models.FloatField(blank=True, null=True, verbose_name='Duração (s)'),
        ),
        migrations.AddField(
            model_name='itineraryimage',
            name='error_message',
            field=models.TextField(blank=True, default='', verbose_name='Mensagem técnica (falha)'),
        ),
        migrations.AddField(
            model_name='itineraryimage',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Altura'),
        ),
        migrations.AddField(
            model_name='itineraryimage',
            name='orig_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nome original'),
        ),
        migrations.AddField(
            model_name='itineraryimage',
            name='orig_size',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Tamanho original (bytes)'),
        ),
        migrations.AddField(
            model_name='itineraryimage',
            name='processing_finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Processamento concluído em'),
        ),
        migrations.AddField(
            model_name='itineraryimage',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Processamento iniciado em'),
        ),
        migrations.AddField(
            model_name='itineraryimage',
            name='status',
            field=models.CharField(choices=[('pending', 'Na fila'), ('processing', 'Processando'), ('ready', 'Pronto'), ('failed', 'Falhou')], db_index=True, default='ready', max_length=12, verbose_name='Status do processamento'),
        ),
        migrations.AddField(
            model_name='itineraryimage',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to=itineraries.models.secure_itinerary_thumb_path, verbose_name='Miniatura do vídeo'),
        ),
        migrations.AddField(
            model_name='itineraryimage',
            name='video_normalized',
            field=models.FileField(blank=True, null=True, upload_to=itineraries.models.secure_itinerary_video_norm_path, verbose_name='Vídeo normalizado (MP4)'),
        ),
        migrations.AddField(
            model_name='itineraryimage',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Largura'),
        ),
    ]
