# Generated by Django 6.0.6 on 2026-07-24 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0084_itineraryimage_codec_itineraryimage_detected_mime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryimage',
            name='estimated_remaining_seconds',
            field=models.FloatField(blank=True, null=True, verbose_name='Tempo restante estimado (s)'),
        ),
        migrations.AddField(
            model_name='itineraryimage',
            name='processing_attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='Tentativas de processamento'),
        ),
        migrations.AddField(
            model_name='itineraryimage',
            name='processing_heartbeat_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último sinal de vida'),
        ),
        migrations.AddField(
            model_name='itineraryimage',
            name='processing_progress',
            field=models.FloatField(default=0, verbose_name='Progresso (%)'),
        ),
        migrations.AddField(
            model_name='itineraryimage',
            name='processing_speed',
            field=models.FloatField(blank=True, null=True, verbose_name='Velocidade do FFmpeg (x)'),
        ),
        migrations.AddField(
            model_name='itineraryimage',
            name='processing_stage',
            field=models.CharField(blank=True, choices=[('queued', 'Na fila'), ('probing', 'Analisando o arquivo'), ('transcoding', 'Convertendo'), ('validating', 'Verificando'), ('generating_thumbnail', 'Gerando capa'), ('finalizing', 'Finalizando'), ('completed', 'Concluído'), ('failed', 'Falhou')], default='queued', max_length=24, verbose_name='Etapa'),
        ),
    ]
