# Generated by Django 6.0.6 on 2026-07-24 13:34

import itineraries.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0085_itineraryimage_estimated_remaining_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryimage',
            name='video_normalized_webm',
            field=models.FileField(blank=True, null=True, upload_to=itineraries.models.secure_itinerary_video_webm_path, verbose_name='Vídeo normalizado (WebM/VP9)'),
        ),
        migrations.AlterField(
            model_name='itineraryimage',
            name='processing_stage',
            field=models.CharField(blank=True, choices=[('queued', 'Na fila'), ('probing', 'Analisando o arquivo'), ('transcoding', 'Convertendo (MP4)'), ('validating', 'Verificando (MP4)'), ('transcoding_webm', 'Convertendo (WebM)'), ('validating_webm', 'Verificando (WebM)'), ('generating_thumbnail', 'Gerando capa'), ('finalizing', 'Finalizando'), ('completed', 'Concluído'), ('failed', 'Falhou')], default='queued', max_length=24, verbose_name='Etapa'),
        ),
        migrations.AlterField(
            model_name='itineraryimage',
            name='video_normalized',
            field=models.FileField(blank=True, null=True, upload_to=itineraries.models.secure_itinerary_video_norm_path, verbose_name='Vídeo normalizado (MP4/H.264)'),
        ),
    ]
