# Generated by Django 6.0.6 on 2026-07-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0086_itineraryimage_video_normalized_webm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryimage',
            name='webm_error',
            field=models.TextField(blank=True, default='', verbose_name='Falha técnica do WebM'),
        ),
    ]
