# Generated by Django 6.0.6 on 2026-07-24 16:18

import django.db.models.deletion
import itineraries.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0087_itineraryimage_webm_error'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container', models.CharField(max_length=8, verbose_name='Contêiner')),
                ('video_codec', models.CharField(max_length=20, verbose_name='Codec de vídeo')),
                ('audio_codec', models.CharField(max_length=10, verbose_name='Codec de áudio')),
                ('resolution', models.CharField(max_length=10, verbose_name='Resolução')),
                ('quality', models.CharField(max_length=12, verbose_name='Qualidade')),
                ('config_hash', models.CharField(db_index=True, max_length=64, verbose_name='Hash da config')),
                ('status', models.CharField(choices=[('pending', 'Na fila'), ('processing', 'Processando'), ('ready', 'Pronto'), ('failed', 'Falhou')], db_index=True, default='pending', max_length=12)),
                ('progress', models.FloatField(default=0, verbose_name='Progresso (%)')),
                ('stage', models.CharField(blank=True, default='queued', max_length=24, verbose_name='Etapa')),
                ('estimated_remaining_seconds', models.FloatField(blank=True, null=True, verbose_name='Tempo restante (s)')),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True, verbose_name='Sinal de vida')),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('file', models.FileField(blank=True, null=True, upload_to=itineraries.models.secure_video_export_path, verbose_name='Arquivo exportado')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='Tamanho (bytes)')),
                ('error', models.TextField(blank=True, default='', verbose_name='Falha técnica')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Expira em')),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='itineraries.itineraryimage')),
            ],
            options={
                'verbose_name': 'Exportação de vídeo',
                'verbose_name_plural': 'Exportações de vídeo',
                'indexes': [models.Index(fields=['video', 'config_hash'], name='idx_vexport_video_hash')],
            },
        ),
    ]
