# Generated by Django 6.0.6 on 2026-07-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0088_videoexport'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoexport',
            name='frame_rate',
            field=models.CharField(default='auto', max_length=8, verbose_name='Taxa de quadros'),
        ),
    ]
