# Generated by Django 6.0.6 on 2026-07-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0089_videoexport_frame_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraryimage',
            name='kind',
            field=models.CharField(choices=[('gallery', 'Galeria'), ('cover', 'Capa'), ('video', 'Vídeo'), ('blocking', 'Lâmina do Bloqueio')], default='gallery', max_length=20, verbose_name='Tipo'),
        ),
    ]
