# Generated by Django 6.0.6 on 2026-07-25 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0082_merge_20260722_0018'),
        ('itineraries', '0090_alter_itineraryimage_kind'),
    ]

    operations = [
    ]
