# Generated by Django 6.0.6 on 2026-07-27 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0091_merge_20260725_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerarypricingconfig',
            name='contract_accommodations',
            field=models.JSONField(blank=True, default=list, verbose_name='Acomodações do contrato'),
        ),
    ]
