# Generated by Django 6.0.6 on 2026-07-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0092_itinerarypricingconfig_contract_accommodations'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerarycostitem',
            name='payment_schedule',
            field=models.JSONField(blank=True, default=list, verbose_name='Cronograma de pagamento'),
        ),
    ]
