# Generated by Django 6.0.6 on 2026-07-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0093_itinerarycostitem_payment_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerarypricingconfig',
            name='pagamento_imediato_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Pagamento imediato (%)'),
        ),
        migrations.AddField(
            model_name='itinerarypricingconfig',
            name='reserva_online_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Reserva online (%)'),
        ),
        migrations.AddField(
            model_name='itinerarypricingconfig',
            name='reserva_operadora_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Reserva exclusiva da operadora (%)'),
        ),
    ]
