# Generated by Django 6.0.6 on 2026-07-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0094_itinerarypricingconfig_pagamento_imediato_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerarypricingconfig',
            name='reservation_deadline_hours',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Prazo da reserva sem pagamento (horas)'),
        ),
    ]
