# Generated by Django 6.0.6 on 2026-07-29 23:08

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0095_itinerarypricingconfig_reservation_deadline_hours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryCostPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_on', models.DateField(blank=True, null=True, verbose_name='Data do pagamento')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='Valor pago')),
                ('currency', models.CharField(blank=True, default='', max_length=3, verbose_name='Moeda')),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=18, verbose_name='Câmbio (1 moeda = X reais)')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='Parcela / observação')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cost_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='itineraries.itinerarycostitem')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_payments_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pagamento de custo',
                'verbose_name_plural': 'Pagamentos de custo',
                'ordering': ['order', 'id'],
            },
        ),
    ]
