# Generated by Django 6.0.6 on 2026-07-29 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0096_itinerarycostpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerarycostpayment',
            name='installment_index',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Parcela (índice)'),
        ),
    ]
