# Generated by Django 6.0.6 on 2026-07-31 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0097_itinerarycostpayment_installment_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerarypricingconfig',
            name='custo_real_done',
            field=models.BooleanField(default=False, verbose_name='Custo real concluído'),
        ),
    ]
