# Generated by Django 6.0.6 on 2026-07-31 13:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0098_itinerarypricingconfig_custo_real_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerarycostpayment',
            name='tax_kind',
            field=models.CharField(choices=[('percent', 'Percentual'), ('fixed', 'Valor fixo')], default='percent', max_length=8, verbose_name='Tipo da taxa'),
        ),
        migrations.AddField(
            model_name='itinerarycostpayment',
            name='tax_value',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18, verbose_name='Taxa (% ou valor)'),
        ),
    ]
