# Generated by Django 6.0.6 on 2026-07-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0099_itinerarycostpayment_tax_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerarypricingconfig',
            name='seats_for_sale',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Passageiros à venda'),
        ),
    ]
