# Generated by Django 6.0.6 on 2026-08-03 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0100_itinerarypricingconfig_seats_for_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='pinned_position',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Posição fixada (ordem do site)'),
        ),
    ]
