# Generated by Django 6.0.6 on 2026-08-04 14:59

import core.storages
import django.core.validators
import django.db.models.deletion
import itineraries.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0101_itinerary_pinned_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryMapPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitude')),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitude')),
                ('image', models.FileField(blank=True, null=True, storage=core.storages.public_media_storage, upload_to=itineraries.models.secure_itinerary_image_path, verbose_name='Foto')),
                ('color', models.CharField(blank=True, default='', max_length=20, verbose_name='Cor do marcador')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_points', to='itineraries.itinerary')),
            ],
            options={
                'verbose_name': 'Ponto do mapa',
                'verbose_name_plural': 'Pontos do mapa',
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['itinerary', 'order'], name='idx_itinmap_itin_order')],
            },
        ),
    ]
