# Generated by Django 6.0.6 on 2026-08-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0102_itinerarymappoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerarymappoint',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Ícone do marcador'),
        ),
    ]
