# Generated by Django 6.0.6 on 2026-08-04 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0103_itinerarymappoint_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryimage',
            name='map_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='itineraries.itinerarymappoint', verbose_name='Ponto do mapa'),
        ),
    ]
