# Generated by Django 6.0.6 on 2026-08-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0104_itineraryimage_map_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerarymappoint',
            name='leg_color',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Cor da linha'),
        ),
        migrations.AddField(
            model_name='itinerarymappoint',
            name='leg_icon',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Ícone do trecho'),
        ),
        migrations.AddField(
            model_name='itinerarymappoint',
            name='leg_label',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Descrição do trecho'),
        ),
        migrations.AddField(
            model_name='itinerarymappoint',
            name='leg_style',
            field=models.CharField(blank=True, choices=[('dashed', 'Tracejada'), ('solid', 'Contínua'), ('dotted', 'Pontilhada')], default='', max_length=10, verbose_name='Estilo da linha'),
        ),
        migrations.AlterField(
            model_name='itinerarymappoint',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Ícone do marcador'),
        ),
    ]
