# Generated by Django 6.0.6 on 2026-08-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0105_itinerarymappoint_leg_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='map_highlight_color',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Cor dos países do roteiro'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='map_land_color',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Cor dos países'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='map_style',
            field=models.CharField(blank=True, choices=[('claro', 'Claro'), ('colorido', 'Colorido'), ('satelite', 'Satélite'), ('ilustrado', 'Ilustrado (países pintados)')], default='', max_length=20, verbose_name='Estilo do mapa'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='map_water_color',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Cor do mar'),
        ),
    ]
