# Generated by Django 6.0.6 on 2026-08-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0106_itinerary_map_highlight_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='map_show_borders',
            field=models.BooleanField(default=True, verbose_name='Mostrar o contorno dos países'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='map_show_state_names',
            field=models.BooleanField(default=False, verbose_name='Mostrar o nome dos estados'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='map_show_states',
            field=models.BooleanField(default=False, verbose_name='Mostrar a divisão dos estados'),
        ),
    ]
