# Generated by Django 6.0.6 on 2026-08-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0107_itinerary_map_show_borders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='map_show_country_names',
            field=models.BooleanField(default=False, verbose_name='Mostrar o nome dos países'),
        ),
    ]
