# Generated by Django 6.0.6 on 2026-08-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0108_itinerary_map_show_country_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='map_extra_countries',
            field=models.JSONField(blank=True, default=list, verbose_name='Países destacados a mais'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='map_highlight_color_dark',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Cor dos países destacados (tema escuro)'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='map_land_color_dark',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Cor dos países (tema escuro)'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='map_state_countries',
            field=models.JSONField(blank=True, default=list, verbose_name='Países com estados desenhados'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='map_water_color_dark',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Cor do mar (tema escuro)'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='map_highlight_color',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Cor dos países destacados (tema claro)'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='map_land_color',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Cor dos países (tema claro)'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='map_water_color',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Cor do mar (tema claro)'),
        ),
    ]
