# Generated by Django 6.0.6 on 2026-08-04 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0109_itinerary_map_extra_countries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='map_show_tile_labels',
            field=models.BooleanField(default=True, verbose_name='Mostrar os nomes do provedor do mapa'),
        ),
    ]
