# Generated by Django 6.0.6 on 2026-08-04 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0110_itinerary_map_show_tile_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='map_highlight_opacity',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Opacidade do destaque (%)'),
        ),
    ]
