# Generated by Django 6.0.6 on 2026-08-04 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0111_itinerary_map_highlight_opacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryimage',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='itineraries.itineraryimage', verbose_name='Copiada de'),
        ),
    ]
