# Generated by Django 6.0.6 on 2026-08-05 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0112_itineraryimage_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerarymappoint',
            name='leg_style',
            field=models.CharField(blank=True, choices=[('dashed', 'Tracejada'), ('solid', 'Contínua'), ('dotted', 'Pontilhada'), ('none', 'Sem linha')], default='', max_length=10, verbose_name='Estilo da linha'),
        ),
    ]
