# Generated by Django 6.0.6 on 2026-08-05 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0113_alter_itinerarymappoint_leg_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerarypricingconfig',
            name='seats_for_sale',
        ),
    ]
