# Generated by Django 6.0.6 on 2026-08-05 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0105_systemsettings_site_order_by_and_more'),
        ('itineraries', '0114_remove_itinerarypricingconfig_seats_for_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryinventoryblock',
            name='terrestre_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='config_api.configterrestrecompany', verbose_name='Empresa do ônibus'),
        ),
        migrations.AlterField(
            model_name='itineraryinventoryblock',
            name='kind',
            field=models.CharField(choices=[('terrestre', 'Terrestre (quartos)'), ('rodoviario', 'Rodoviário (assentos)'), ('aereo', 'Aéreo'), ('navio', 'Navio')], max_length=10, verbose_name='Tipo'),
        ),
    ]
