# Generated by Django 6.0.6 on 2026-08-06 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0108_systemsettings_list_notification_users'),
        ('itineraries', '0115_itineraryinventoryblock_terrestre_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryinventoryblock',
            name='bus_map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='config_api.busmap', verbose_name='Mapa de ônibus'),
        ),
    ]
