# Generated by Django 6.0.6 on 2026-08-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0116_itineraryinventoryblock_bus_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='map_close_route',
            field=models.BooleanField(default=False, verbose_name='Ligar o último ponto ao primeiro'),
        ),
    ]
