# Generated by Django 6.0.5 on 2026-06-24 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0008_agency_deleted_at_agency_is_deleted_and_more'),
        ('config_api', '0026_operatingcompany'),
        ('passengers', '0022_passenger_deleted_at_passenger_is_deleted'),
        ('trips', '0038_room_same_sex_ack'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_number', models.CharField(blank=True, max_length=50, verbose_name='Reserva nº')),
                ('contract_date', models.DateField(blank=True, null=True, verbose_name='Data desta contratação')),
                ('package_name', models.CharField(blank=True, max_length=300, verbose_name='Nome do pacote')),
                ('departure_date', models.DateField(blank=True, null=True, verbose_name='Data da viagem')),
                ('departure_airport', models.CharField(blank=True, max_length=200, verbose_name='Aeroporto de embarque')),
                ('observations', models.TextField(blank=True, verbose_name='Observações')),
                ('total_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Soma total (USD)')),
                ('total_brl', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Total em (BRL)')),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Câmbio')),
                ('payment_method', models.CharField(blank=True, max_length=100, verbose_name='Forma de pagamento')),
                ('received_down_payment_brl', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Recebido na entrada (BRL)')),
                ('received_installments_brl', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Recebido a prazo (BRL)')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('cancelado', 'Cancelado')], default='ativo', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Excluído')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Excluído em')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='agencies.agency', verbose_name='Agência de viagem')),
                ('clauses', models.ManyToManyField(blank=True, related_name='contracts', to='config_api.contractclause', verbose_name='Cláusulas')),
                ('contratante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts_as_contratante', to='passengers.passenger', verbose_name='Contratante')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_created', to=settings.AUTH_USER_MODEL)),
                ('passenger_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='trips.passengerlist', verbose_name='Lista de passageiros')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractAccommodationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_per_person_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor por pessoa (USD)')),
                ('taxes_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taxas (USD)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('accommodation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='config_api.configaccommodation')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodation_lines', to='contracts.contract')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContractInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('entrada', 'Entrada'), ('parcela', 'Parcela')], default='parcela', max_length=10, verbose_name='Tipo')),
                ('installment_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Número da parcela')),
                ('detail', models.CharField(blank=True, max_length=300, verbose_name='Detalhe do pagamento')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Para (data)')),
                ('value_brl', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor (BRL)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='contracts.contract')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContractGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('accommodation_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='config_api.configaccommodation')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='contracts.contract')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_guest_entries', to='passengers.passenger')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('contract', 'passenger')},
            },
        ),
    ]
