# Generated by Django 6.0.5 on 2026-06-24 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='contractinstallment',
            name='payment_method',
            field=models.CharField(blank=True, max_length=100, verbose_name='Forma de pagamento'),
        ),
    ]
