# Generated by Django 6.0.5 on 2026-06-24 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_remove_contract_payment_method_and_more'),
        ('passengers', '0022_passenger_deleted_at_passenger_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='payer_address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='contract',
            name='payer_birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AddField(
            model_name='contract',
            name='payer_document',
            field=models.CharField(blank=True, max_length=20, verbose_name='CPF / CNPJ'),
        ),
        migrations.AddField(
            model_name='contract',
            name='payer_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='contract',
            name='payer_gender',
            field=models.CharField(blank=True, max_length=50, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='contract',
            name='payer_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nome completo / Razão social'),
        ),
        migrations.AddField(
            model_name='contract',
            name='payer_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='contract',
            name='payer_type',
            field=models.CharField(blank=True, choices=[('fisica', 'Pessoa física'), ('juridica', 'Pessoa jurídica / Empresa')], max_length=10, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='contract',
            name='return_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de término da viagem'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contratante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts_as_contratante', to='passengers.passenger', verbose_name='Contratante'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='departure_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de início da viagem'),
        ),
    ]
