# Generated by Django 6.0.5 on 2026-06-28 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_contract_payer_address_contract_payer_birth_date_and_more'),
        ('itineraries', '0005_itinerary_about_destination_itinerary_day_by_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='itinerary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='itineraries.itinerary', verbose_name='Roteiro'),
        ),
    ]
