# Generated by Django 6.0.5 on 2026-06-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_contract_itinerary'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractguest',
            name='room_group',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quarto'),
        ),
    ]
