# Generated by Django 6.0.5 on 2026-06-28 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_contractguest_room_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Descrição')),
                ('kind', models.CharField(choices=[('acrescimo', 'Acréscimo'), ('desconto', 'Desconto')], default='acrescimo', max_length=10, verbose_name='Tipo')),
                ('value_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor (USD)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='contracts.contract')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
