# Generated by Django 6.0.5 on 2026-06-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_contractadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractadjustment',
            name='mode',
            field=models.CharField(choices=[('valor', 'Valor (USD)'), ('percentual', 'Percentual (%)')], default='valor', max_length=12, verbose_name='Modo'),
        ),
        migrations.AddField(
            model_name='contractadjustment',
            name='percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Percentual'),
        ),
    ]
