# Generated by Django 6.0.5 on 2026-06-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_contractadjustment_mode_contractadjustment_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='round_currency',
            field=models.CharField(choices=[('brl', 'Real (BRL)'), ('usd', 'Dólar (USD)')], default='brl', max_length=3, verbose_name='Moeda do arredondamento'),
        ),
        migrations.AddField(
            model_name='contract',
            name='round_mode',
            field=models.CharField(choices=[('nearest', 'Mais próximo'), ('up', 'Pra cima'), ('down', 'Pra baixo')], default='nearest', max_length=8, verbose_name='Direção do arredondamento'),
        ),
        migrations.AddField(
            model_name='contract',
            name='round_step',
            field=models.PositiveIntegerField(default=0, verbose_name='Arredondar para múltiplo de'),
        ),
    ]
