# Generated by Django 6.0.5 on 2026-06-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_contract_round_currency_contract_round_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='signature_type',
            field=models.CharField(choices=[('fisica', 'Física (imprimir e assinar)'), ('digital', 'Digital')], default='fisica', max_length=10, verbose_name='Forma de assinatura'),
        ),
    ]
