# Generated by Django 6.0.5 on 2026-06-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0009_contract_signature_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='signed_file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/signed/', verbose_name='Contrato assinado'),
        ),
        migrations.AddField(
            model_name='contract',
            name='stage',
            field=models.CharField(choices=[('em_edicao', 'Em edição'), ('enviado', 'Enviado para assinatura'), ('assinado', 'Assinado')], db_index=True, default='em_edicao', max_length=12, verbose_name='Etapa'),
        ),
    ]
