# Generated by Django 6.0.5 on 2026-06-28 18:32

import contracts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_contract_signed_file_contract_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='signed_file',
            field=models.FileField(blank=True, null=True, upload_to=contracts.models.secure_signed_path, verbose_name='Contrato assinado'),
        ),
    ]
