# Generated by Django 6.0.5 on 2026-06-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0011_alter_contract_signed_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='signed_verification',
            field=models.JSONField(blank=True, null=True, verbose_name='Conferência do assinado'),
        ),
    ]
