# Generated by Django 6.0.5 on 2026-06-28 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0012_contract_signed_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Enviado para assinatura em'),
        ),
        migrations.AddField(
            model_name='contract',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Assinado em'),
        ),
    ]
