# Generated by Django 6.0.5 on 2026-06-28 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0013_contract_sent_at_contract_signed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='payment_type',
            field=models.CharField(choices=[('a_vista', 'À vista'), ('parcelado', 'Parcelado')], default='parcelado', max_length=10, verbose_name='Forma de pagamento'),
        ),
    ]
