# Generated by Django 6.0.5 on 2026-06-28 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0014_contract_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='base_currency',
            field=models.CharField(default='USD', max_length=3, verbose_name='Moeda base'),
        ),
    ]
