# Generated by Django 6.0.5 on 2026-06-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0016_contract_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='autentique_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Dados da Autentique'),
        ),
        migrations.AddField(
            model_name='contract',
            name='autentique_document_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='ID do documento na Autentique'),
        ),
    ]
