# Generated by Django 6.0.5 on 2026-06-29 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0017_contract_autentique_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='custom_clauses',
            field=models.JSONField(blank=True, default=list, verbose_name='Cláusulas personalizadas'),
        ),
    ]
