# Generated by Django 6.0.5 on 2026-06-30 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0008_agency_deleted_at_agency_is_deleted_and_more'),
        ('contracts', '0018_contract_custom_clauses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='agencies.agency', verbose_name='Agência de viagem'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('ativo', 'Ativo'), ('cancelado', 'Cancelado')], default='ativo', max_length=20, verbose_name='Status'),
        ),
    ]
