# Generated by Django 6.0.5 on 2026-06-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0019_alter_contract_agency_alter_contract_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractadjustment',
            name='value_brl',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor (BRL)'),
        ),
        migrations.AlterField(
            model_name='contractadjustment',
            name='kind',
            field=models.CharField(choices=[('acrescimo', 'Acréscimo'), ('desconto', 'Desconto'), ('comissao', 'Comissão')], default='acrescimo', max_length=10, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='contractadjustment',
            name='mode',
            field=models.CharField(choices=[('valor', 'Valor (USD)'), ('valor_brl', 'Valor (BRL)'), ('percentual', 'Percentual (%)')], default='valor', max_length=12, verbose_name='Modo'),
        ),
    ]
