# Generated by Django 6.0.5 on 2026-07-01 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0020_contractadjustment_value_brl_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='review_note',
            field=models.TextField(blank=True, default='', verbose_name='Observação/motivo da revisão'),
        ),
        migrations.AddField(
            model_name='contract',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Revisado em'),
        ),
        migrations.AddField(
            model_name='contract',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='stage',
            field=models.CharField(choices=[('em_edicao', 'Em edição'), ('enviado', 'Enviado para assinatura'), ('assinado', 'Assinado'), ('revisao', 'Em revisão'), ('aprovado', 'Aprovado')], db_index=True, default='em_edicao', max_length=12, verbose_name='Etapa'),
        ),
    ]
