# Generated by Django 6.0.5 on 2026-07-01 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0021_contract_review_note_contract_reviewed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='invoice_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data da fatura'),
        ),
        migrations.AddField(
            model_name='contract',
            name='invoice_number',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Número da fatura'),
        ),
        migrations.AddField(
            model_name='contract',
            name='invoiced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Faturado em'),
        ),
        migrations.AddField(
            model_name='contract',
            name='invoiced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_invoiced', to=settings.AUTH_USER_MODEL, verbose_name='Faturado por'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='stage',
            field=models.CharField(choices=[('em_edicao', 'Em edição'), ('enviado', 'Enviado para assinatura'), ('assinado', 'Assinado'), ('revisao', 'Em revisão'), ('aprovado', 'Aprovado'), ('a_faturar', 'A faturar'), ('faturado', 'Faturado')], db_index=True, default='em_edicao', max_length=12, verbose_name='Etapa'),
        ),
    ]
