# Generated by Django 6.0.6 on 2026-07-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0022_contract_invoice_date_contract_invoice_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='payment_plan_applied',
            field=models.JSONField(blank=True, null=True, verbose_name='Sugestão de pagamento aplicada'),
        ),
    ]
