# Generated by Django 6.0.6 on 2026-07-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0023_contract_payment_plan_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='signing_version',
            field=models.PositiveIntegerField(default=1, verbose_name='Versão de assinatura'),
        ),
    ]
