# Generated by Django 6.0.6 on 2026-07-03 18:09

import contracts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0024_contract_signing_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='payment_receipt',
            field=models.FileField(blank=True, null=True, upload_to=contracts.models.secure_receipt_path, verbose_name='Comprovante de pagamento'),
        ),
    ]
