# Generated by Django 6.0.6 on 2026-07-03 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0025_contract_payment_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='a_vista_discount_mode',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Tipo do desconto à vista'),
        ),
        migrations.AddField(
            model_name='contract',
            name='a_vista_discount_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Desconto à vista (USD)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='a_vista_discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Desconto à vista (valor/%)'),
        ),
    ]
