# Generated by Django 6.0.6 on 2026-07-06 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0026_contract_a_vista_discount_mode_and_more'),
        ('itineraries', '0048_alter_itinerary_options_itinerary_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='itinerary_flight_departure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='itineraries.itinerarydeparture', verbose_name='Partida (aéreo)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='itinerary_terrestre_departure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='itineraries.itineraryterrestredeparture', verbose_name='Partida (terrestre)'),
        ),
    ]
