# Generated by Django 6.0.6 on 2026-07-10 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0027_contract_itinerary_flight_departure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='stage',
            field=models.CharField(choices=[('em_edicao', 'Em edição'), ('enviado', 'Enviado para assinatura'), ('assinado', 'Assinado'), ('revisao', 'Em revisão'), ('aprovado', 'Aprovado'), ('a_faturar', 'Verificação do financeiro'), ('em_pagamento', 'Em pagamento'), ('faturado', 'Pagos')], db_index=True, default='em_edicao', max_length=12, verbose_name='Etapa'),
        ),
    ]
