# Generated by Django 6.0.6 on 2026-07-14 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0086_alter_configshipcabin_options_and_more'),
        ('contracts', '0028_alter_contract_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractaccommodationline',
            name='accommodation_label',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Rótulo da acomodação'),
        ),
        migrations.AddField(
            model_name='contractaccommodationline',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacidade'),
        ),
        migrations.AddField(
            model_name='contractaccommodationline',
            name='ship_cabin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='config_api.configshipcabin'),
        ),
        migrations.AddField(
            model_name='contractguest',
            name='accommodation_label',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Rótulo da acomodação'),
        ),
        migrations.AddField(
            model_name='contractguest',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacidade'),
        ),
        migrations.AddField(
            model_name='contractguest',
            name='ship_cabin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='config_api.configshipcabin'),
        ),
        migrations.AlterField(
            model_name='contractaccommodationline',
            name='accommodation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='config_api.configaccommodation'),
        ),
    ]
