# Generated by Django 6.0.6 on 2026-07-20 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0029_contractaccommodationline_accommodation_label_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='agency_seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_as_agency_seller', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor da agência'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_as_seller', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor da operadora'),
        ),
    ]
