# Generated by Django 6.0.6 on 2026-07-29 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0030_contract_agency_seller_alter_contract_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='parent_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addenda', to='contracts.contract', verbose_name='Contrato de origem (adendo)'),
        ),
    ]
