# Generated by Django 6.0.6 on 2026-07-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0031_contract_parent_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractaccommodationline',
            name='currency',
            field=models.CharField(blank=True, default='', max_length=3, verbose_name='Moeda da linha'),
        ),
    ]
