# Generated by Django 6.0.6 on 2026-07-31 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0032_contractaccommodationline_currency'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='source_reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_from', to='reservations.reservation', verbose_name='Reserva de origem'),
        ),
    ]
