# Generated by Django 6.0.6 on 2026-08-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0033_contract_source_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='stage',
            field=models.CharField(choices=[('em_edicao', 'Em edição'), ('revisao', 'Em revisão'), ('a_faturar', 'Verificação do financeiro'), ('enviado', 'Para assinatura'), ('assinado', 'Assinado'), ('conf_pagamento', 'Conferência do pagamento'), ('em_pagamento', 'Em pagamento'), ('faturado', 'Pagos'), ('aprovado', 'Aprovado')], db_index=True, default='em_edicao', max_length=16, verbose_name='Etapa'),
        ),
    ]
