# Generated by Django 6.0.6 on 2026-08-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0035_remap_contract_stages'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='receipt_payer',
            field=models.CharField(blank=True, choices=[('cliente', 'Cliente → UneWorld'), ('agencia', 'Agência → UneWorld')], default='', max_length=10, verbose_name='Pagante'),
        ),
    ]
