# Generated by Django 6.0.6 on 2026-08-19 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0111_configpaymentmethod_kind'),
        ('contracts', '0036_contract_receipt_payer'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='payment_gateway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='config_api.paymentgateway', verbose_name='Gateway de pagamento'),
        ),
    ]
