# Generated by Django 6.0.6 on 2026-08-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0037_contract_payment_gateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='payment_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Link de pagamento'),
        ),
    ]
