# Generated by Django 6.0.6 on 2026-08-19 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0038_contract_payment_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contractinstallment',
            name='received_at',
            field=models.DateField(blank=True, null=True, verbose_name='Recebido em'),
        ),
        migrations.AddField(
            model_name='contractinstallment',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installments_received', to=settings.AUTH_USER_MODEL, verbose_name='Baixado por'),
        ),
        migrations.AddField(
            model_name='contractinstallment',
            name='received_note',
            field=models.CharField(blank=True, max_length=300, verbose_name='Observação da baixa'),
        ),
        migrations.AddField(
            model_name='contractinstallment',
            name='received_value_brl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor recebido (BRL)'),
        ),
    ]
