# Generated by Django 6.0.6 on 2026-07-08 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivenode',
            name='edit_key',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
