# Generated by Django 6.0.6 on 2026-07-08 00:39

import drive.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0002_drivenode_edit_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivenode',
            name='thumb',
            field=models.FileField(blank=True, null=True, upload_to=drive.models.drive_thumb_path),
        ),
    ]
