# Generated by Django 6.0.6 on 2026-07-08 01:25

import drive.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0004_drivenodeversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivenodeversion',
            name='changes_file',
            field=models.FileField(blank=True, null=True, upload_to=drive.models.drive_changes_path),
        ),
        migrations.AddField(
            model_name='drivenodeversion',
            name='changes_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='drivenodeversion',
            name='doc_key',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='drivenodeversion',
            name='server_version',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
