# Generated by Django 6.0.6 on 2026-07-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0005_drivenodeversion_changes_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivenode',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Excluído em'),
        ),
        migrations.AddField(
            model_name='drivenode',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Excluído'),
        ),
    ]
