# Generated by Django 6.0.6 on 2026-07-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0006_drivenode_deleted_at_drivenode_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivenode',
            name='share_levels',
            field=models.JSONField(blank=True, default=dict, verbose_name='Níveis de compartilhamento'),
        ),
    ]
