# Generated by Django 6.0.5 on 2026-06-13 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest_enabled', models.BooleanField(default=False, verbose_name='Resumo automático por e-mail')),
                ('digest_frequency', models.CharField(choices=[('daily', 'Diário'), ('weekly', 'Semanal')], default='daily', max_length=10, verbose_name='Frequência do resumo')),
                ('reminder_enabled', models.BooleanField(default=False, verbose_name='Lembrete de prazos por e-mail')),
                ('reminder_days_before', models.PositiveSmallIntegerField(default=3, verbose_name='Avisar com quantos dias de antecedência')),
                ('last_digest_sent', models.DateField(blank=True, null=True, verbose_name='Último resumo enviado em')),
                ('last_reminder_sent', models.DateField(blank=True, null=True, verbose_name='Último lembrete enviado em')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferência de calendário',
                'verbose_name_plural': 'Preferências de calendário',
            },
        ),
    ]
