# Generated by Django 6.0.5 on 2026-06-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarpreference',
            name='side_panel_enabled',
            field=models.BooleanField(default=True, verbose_name='Exibir painel lateral do calendário'),
        ),
        migrations.AddField(
            model_name='calendarpreference',
            name='side_panel_position',
            field=models.CharField(choices=[('left', 'Esquerda'), ('right', 'Direita')], default='right', max_length=5, verbose_name='Posição do painel lateral'),
        ),
    ]
