# Generated by Django 6.0.5 on 2026-06-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_calendarpreference_birthday_emails'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Enviado em')),
                ('to', models.TextField(verbose_name='Destinatários')),
                ('subject', models.CharField(max_length=500, verbose_name='Assunto')),
                ('email_type', models.CharField(choices=[('daily_digest', 'Digest diário'), ('digest', 'Resumo do calendário'), ('deadline', 'Prazo de confirmação'), ('task', 'Pendência'), ('birthday', 'Aniversário de passageiro'), ('reset_password', 'Redefinição de senha'), ('invite', 'Convite'), ('other', 'Outro')], default='other', max_length=30, verbose_name='Tipo')),
                ('html_body', models.TextField(blank=True, verbose_name='Conteúdo HTML')),
                ('success', models.BooleanField(default=True, verbose_name='Enviado com sucesso')),
            ],
            options={
                'verbose_name': 'Log de e-mail',
                'verbose_name_plural': 'Log de e-mails',
                'ordering': ['-sent_at'],
            },
        ),
    ]
