# Generated by Django 6.0.5 on 2026-06-19 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_time_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarpreference',
            name='send_hour',
            field=models.IntegerField(default=8, verbose_name='Horário de envio das notificações diárias'),
        ),
    ]
