# Generated by Django 6.0.5 on 2026-06-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0009_add_side_panel_to_calendarpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Entregue em'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Aberto em'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='resend_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='ID na Resend'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='status',
            field=models.CharField(choices=[('sent', 'Enviado'), ('delivered', 'Entregue'), ('bounced', 'Não entregue'), ('failed', 'Falhou no envio')], default='sent', max_length=10, verbose_name='Status de entrega'),
        ),
    ]
