# Generated by Django 6.0.5 on 2026-06-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0010_emaillog_delivered_at_emaillog_opened_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarpreference',
            name='contract_create_layout',
            field=models.CharField(choices=[('steps', 'Passo a passo'), ('full', 'Completo')], default='steps', max_length=6, verbose_name='Layout ao criar contrato'),
        ),
        migrations.AddField(
            model_name='calendarpreference',
            name='contract_edit_layout',
            field=models.CharField(choices=[('steps', 'Passo a passo'), ('full', 'Completo')], default='full', max_length=6, verbose_name='Layout ao editar contrato'),
        ),
    ]
