# Generated by Django 6.0.5 on 2026-06-29 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0011_calendarpreference_contract_create_layout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarpreference',
            name='dashboard_currencies',
            field=models.JSONField(blank=True, default=list, verbose_name='Moedas do câmbio no painel'),
        ),
    ]
