# Generated by Django 6.0.6 on 2026-07-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0012_calendarpreference_dashboard_currencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarpreference',
            name='itinerary_tab_order',
            field=models.JSONField(blank=True, default=list, verbose_name='Ordem das abas do roteiro'),
        ),
    ]
