# Generated by Django 6.0.6 on 2026-07-08 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0013_calendarpreference_itinerary_tab_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarpreference',
            name='drive_columns',
            field=models.JSONField(blank=True, default=list, verbose_name='Colunas da lista do Drive'),
        ),
    ]
