# Generated by Django 6.0.6 on 2026-07-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0014_calendarpreference_drive_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarpreference',
            name='nav_order',
            field=models.JSONField(blank=True, default=list, verbose_name='Ordem da barra lateral'),
        ),
    ]
