# Generated by Django 6.0.6 on 2026-07-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0015_calendarpreference_nav_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarpreference',
            name='nav_hidden',
            field=models.JSONField(blank=True, default=list, verbose_name='Itens escondidos da barra lateral'),
        ),
        migrations.AddField(
            model_name='calendarpreference',
            name='table_columns',
            field=models.JSONField(blank=True, default=dict, verbose_name='Colunas das tabelas'),
        ),
    ]
