# Generated by Django 6.0.6 on 2026-07-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0016_calendarpreference_nav_hidden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarpreference',
            name='dashboard_chart_range',
            field=models.CharField(choices=[('week', '1 semana'), ('month', '1 mês'), ('6months', '6 meses'), ('year', '1 ano')], default='week', max_length=8, verbose_name='Intervalo do gráfico de câmbio'),
        ),
    ]
