# Generated by Django 6.0.6 on 2026-07-13 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0017_calendarpreference_dashboard_chart_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarpreference',
            name='lamina_recent_colors',
            field=models.JSONField(blank=True, default=list, verbose_name='Cores recentes das lâminas'),
        ),
    ]
