# Generated by Django 6.0.6 on 2026-07-13 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0018_calendarpreference_lamina_recent_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarpreference',
            name='lamina_favorite_patterns',
            field=models.JSONField(blank=True, default=None, null=True, verbose_name='Estampas favoritas'),
        ),
        migrations.AddField(
            model_name='calendarpreference',
            name='lamina_favorite_recommended',
            field=models.JSONField(blank=True, default=None, null=True, verbose_name='Paletas recomendadas favoritas'),
        ),
        migrations.AddField(
            model_name='calendarpreference',
            name='lamina_recent_patterns',
            field=models.JSONField(blank=True, default=list, verbose_name='Estampas recentes'),
        ),
    ]
