# Generated by Django 6.0.6 on 2026-07-13 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0019_calendarpreference_lamina_favorite_patterns_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarpreference',
            name='lamina_favorite_themes',
            field=models.JSONField(blank=True, default=None, null=True, verbose_name='Templates de tema favoritos'),
        ),
    ]
