# Generated by Django 6.0.6 on 2026-07-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0020_calendarpreference_lamina_favorite_themes'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarpreference',
            name='dashboard_list_statuses',
            field=models.JSONField(blank=True, default=list, verbose_name='Status das listas no painel'),
        ),
    ]
