# Generated by Django 6.0.6 on 2026-07-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0021_calendarpreference_dashboard_list_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarpreference',
            name='contract_review_open_mode',
            field=models.CharField(choices=[('new_tab', 'Abrir em aba separada'), ('same_tab', 'Abrir na mesma aba'), ('none', 'Não abrir')], default='new_tab', max_length=10, verbose_name='Ao aprovar contrato, abrir a lista'),
        ),
    ]
