# Generated by Django 6.0.6 on 2026-07-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0022_calendarpreference_contract_review_open_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarpreference',
            name='contract_tab_order',
            field=models.JSONField(blank=True, default=list, verbose_name='Ordem das abas dos contratos'),
        ),
    ]
