# Generated by Django 6.0.6 on 2026-07-23 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0023_calendarpreference_contract_tab_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarpreference',
            name='gallery_columns',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Colunas da galeria'),
        ),
    ]
