# Generated by Django 6.0.6 on 2026-08-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0024_calendarpreference_gallery_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarpreference',
            name='voucher_tab_colors',
            field=models.JSONField(blank=True, default=dict, verbose_name='Cores das abas dos vouchers'),
        ),
    ]
