# Generated by Django 6.0.6 on 2026-08-05 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0025_calendarpreference_voucher_tab_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarpreference',
            name='lamina_prompt',
            field=models.JSONField(blank=True, default=dict, verbose_name='Configurações do prompt da lâmina'),
        ),
    ]
