# Generated by Django 6.0.6 on 2026-08-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0026_calendarpreference_lamina_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='email_type',
            field=models.CharField(choices=[('daily_digest', 'Digest diário'), ('digest', 'Resumo do calendário'), ('deadline', 'Prazo de confirmação'), ('task', 'Pendência'), ('birthday', 'Aniversário de passageiro'), ('reservation', 'Reserva de assentos'), ('reset_password', 'Redefinição de senha'), ('invite', 'Convite'), ('other', 'Outro')], default='other', max_length=30, verbose_name='Tipo'),
        ),
    ]
