# Generated by Django 6.0.6 on 2026-08-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0027_alter_emaillog_email_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarpreference',
            name='nav_groups',
            field=models.BooleanField(default=True, verbose_name='Mostrar blocos na barra lateral'),
        ),
    ]
