# Generated by Django 6.0.6 on 2026-07-09 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lamina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='Título')),
                ('headline', models.CharField(blank=True, default='', max_length=300, verbose_name='Chamada')),
                ('theme', models.CharField(default='ocean', max_length=20, verbose_name='Tema')),
                ('columns', models.PositiveSmallIntegerField(default=3, verbose_name='Colunas')),
                ('rows', models.PositiveSmallIntegerField(default=2, verbose_name='Linhas')),
                ('roteiro_ids', models.JSONField(blank=True, default=list, verbose_name='Roteiros (ordem)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lâmina',
                'verbose_name_plural': 'Lâminas',
                'ordering': ['-updated_at'],
            },
        ),
    ]
