# Generated by Django 6.0.6 on 2026-07-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laminas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lamina',
            name='pattern',
            field=models.CharField(default='none', max_length=20, verbose_name='Estampa do fundo'),
        ),
    ]
