# Generated by Django 6.0.6 on 2026-07-09 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0014_agency_logo_crop_agency_logo_original'),
        ('laminas', '0002_lamina_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='lamina',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='agencies.agency'),
        ),
        migrations.AddField(
            model_name='lamina',
            name='footer',
            field=models.BooleanField(default=False, verbose_name='Rodapé com contato'),
        ),
        migrations.AddField(
            model_name='lamina',
            name='source',
            field=models.CharField(default='operadora', max_length=12, verbose_name='Marca/contato'),
        ),
    ]
