# Generated by Django 6.0.6 on 2026-07-13 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laminas', '0003_lamina_agency_lamina_footer_lamina_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lamina',
            name='style',
            field=models.JSONField(blank=True, default=dict, verbose_name='Estilo (cores/estampa)'),
        ),
        migrations.CreateModel(
            name='UserColorPalette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nome')),
                ('colors', models.JSONField(blank=True, default=list, verbose_name='Cores')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Favorita')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_palettes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paleta de cores',
                'verbose_name_plural': 'Paletas de cores',
                'ordering': ['-is_favorite', 'sort_order', 'name'],
            },
        ),
    ]
