# Generated by Django 6.0.6 on 2026-07-13 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laminas', '0004_lamina_style_usercolorpalette'),
    ]

    operations = [
        migrations.AddField(
            model_name='lamina',
            name='roteiro_order_manual',
            field=models.BooleanField(default=False, verbose_name='Ordem manual dos roteiros'),
        ),
    ]
