# Generated by Django 6.0.6 on 2026-07-29 18:46

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0018_merge_20260725_1243'),
        ('contracts', '0032_contractaccommodationline_currency'),
        ('itineraries', '0095_itinerarypricingconfig_reservation_deadline_hours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_type', models.CharField(choices=[('sem_pagamento', 'Sem pagamento'), ('pagamento_imediato', 'Pagamento imediato'), ('operadora', 'Exclusiva da operadora')], db_index=True, default='sem_pagamento', max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('paga', 'Paga'), ('convertida', 'Convertida em contrato'), ('expirada', 'Expirada'), ('cancelada', 'Cancelada')], db_index=True, default='pendente', max_length=12, verbose_name='Status')),
                ('pax', models.PositiveIntegerField(default=1, verbose_name='Passageiros')),
                ('deadline_hours', models.PositiveIntegerField(blank=True, null=True, verbose_name='Prazo (horas)')),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Expira em')),
                ('amount_due', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Valor a pagar agora')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Valor pago')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='agencies.agency', verbose_name='Agência')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='contracts.contract', verbose_name='Contrato')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_created', to=settings.AUTH_USER_MODEL)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='itineraries.itinerary', verbose_name='Roteiro')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-created_at'],
            },
        ),
    ]
