# Generated by Django 6.0.6 on 2026-07-31 23:56

from django.db import migrations, models


def backfill(apps, schema_editor):
    Reservation = apps.get_model('reservations', 'Reservation')
    Reservation.objects.filter(original_pax__isnull=True).update(original_pax=models.F('pax'))


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='original_pax',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Passageiros reservados'),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
