# Generated by Django 6.0.6 on 2026-08-07 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0108_systemsettings_list_notification_users'),
        ('itineraries', '0116_itineraryinventoryblock_bus_map'),
        ('reservations', '0002_reservation_original_pax'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('terrestre', 'Quarto (hotel)'), ('navio', 'Cabine (navio)')], max_length=10, verbose_name='Tipo')),
                ('label', models.CharField(blank=True, default='', max_length=200, verbose_name='Rótulo')),
                ('capacity', models.PositiveIntegerField(default=1, verbose_name='Pessoas por unidade')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Unidades')),
                ('accommodation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='config_api.configaccommodation', verbose_name='Acomodação')),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='itineraries.itineraryinventoryblock', verbose_name='Bloqueio')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='reservations.reservation')),
                ('ship_cabin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='config_api.configshipcabin', verbose_name='Cabine')),
            ],
            options={
                'verbose_name': 'Quarto/cabine da reserva',
                'verbose_name_plural': 'Quartos/cabines da reserva',
                'ordering': ['kind', 'id'],
            },
        ),
    ]
