# Generated by Django 6.0.6 on 2026-08-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservationroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationroom',
            name='guests',
            field=models.JSONField(blank=True, default=list, verbose_name='Pessoas'),
        ),
    ]
