# Generated by Django 6.0.6 on 2026-08-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_reservation_responsible_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='list_guests',
            field=models.JSONField(blank=True, default=list, verbose_name='Pessoas sem unidade própria'),
        ),
    ]
