# Generated by Django 6.0.5 on 2026-05-29 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
        ('passengers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='address',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='document_number',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='passenger',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passengers', to='agencies.agency', verbose_name='Agência'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='birth_place',
            field=models.CharField(blank=True, max_length=200, verbose_name='Local de nascimento'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='cep',
            field=models.CharField(blank=True, max_length=10, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='complement',
            field=models.CharField(blank=True, max_length=100, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='country',
            field=models.CharField(default='Brasil', max_length=100, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='cpf',
            field=models.CharField(blank=True, max_length=20, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='diet_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tipo de alimentação'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, verbose_name='Gênero'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='is_foreign',
            field=models.BooleanField(default=False, verbose_name='Estrangeiro'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='is_guide',
            field=models.BooleanField(default=False, verbose_name='Guia acompanhante'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Cadastro verificado'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='mobile',
            field=models.CharField(blank=True, max_length=30, verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='passport',
            field=models.CharField(blank=True, max_length=50, verbose_name='Passaporte'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='passport_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Validade do passaporte'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='passport_issue',
            field=models.DateField(blank=True, null=True, verbose_name='Data de emissão do passaporte'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='phone1',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefone 1'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='phone2',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefone 2'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='profession',
            field=models.CharField(blank=True, max_length=200, verbose_name='Profissão'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='receives_mail',
            field=models.BooleanField(default=False, verbose_name='Receber mala direta impressa'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='rg',
            field=models.CharField(blank=True, max_length=30, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='rg_issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expedição do RG'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='rg_issuer',
            field=models.CharField(blank=True, max_length=50, verbose_name='Órgão expedidor do RG'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='rne',
            field=models.CharField(blank=True, max_length=50, verbose_name='RNE'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='rne_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Validade do RNE'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='rne_issue',
            field=models.DateField(blank=True, null=True, verbose_name='Data de emissão do RNE'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='seat_preference',
            field=models.CharField(blank=True, choices=[('corredor', 'Corredor'), ('janela', 'Janela'), ('meio', 'Meio')], max_length=20, verbose_name='Preferência de assento'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='street',
            field=models.CharField(blank=True, max_length=200, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='nationality',
            field=models.CharField(default='BRASILEIRA', max_length=100, verbose_name='Nacionalidade'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='state',
            field=models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=2, verbose_name='Estado'),
        ),
    ]
