# Generated by Django 6.0.5 on 2026-05-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0002_remove_passenger_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Primeiro nome'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sobrenome'),
        ),
    ]
