# Generated by Django 6.0.5 on 2026-05-29 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
        ('passengers', '0003_passenger_first_name_passenger_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='agency',
        ),
        migrations.AddField(
            model_name='passenger',
            name='agencies',
            field=models.ManyToManyField(blank=True, related_name='passengers', to='agencies.agency', verbose_name='Agências'),
        ),
    ]
