# Generated by Django 6.0.5 on 2026-05-29 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0004_remove_passenger_agency_passenger_agencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='seat_position',
            field=models.CharField(blank=True, choices=[('frente', 'Frente'), ('meio', 'Meio'), ('fundo', 'Fundo')], max_length=10, verbose_name='Posição no avião'),
        ),
    ]
