# Generated by Django 6.0.5 on 2026-05-29 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0005_passenger_seat_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='flight_class',
            field=models.CharField(blank=True, choices=[('economy', 'Classe Econômica'), ('premium_economy', 'Econômica Premium'), ('business', 'Classe Executiva (Business)'), ('first', 'Primeira Classe')], max_length=20, verbose_name='Classe de voo'),
        ),
    ]
