# Generated by Django 6.0.5 on 2026-05-29 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0006_passenger_flight_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='diet_notes',
            field=models.TextField(blank=True, verbose_name='Observações alimentares'),
        ),
    ]
