# Generated by Django 6.0.5 on 2026-05-29 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0007_passenger_diet_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='email_emergency1',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail contato de emergência 1'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='email_emergency2',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail contato de emergência 2'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='native_language',
            field=models.CharField(blank=True, max_length=100, verbose_name='Língua materna'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='other_languages',
            field=models.TextField(blank=True, verbose_name='Outras línguas'),
        ),
    ]
