# Generated by Django 6.0.5 on 2026-05-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0008_passenger_email_emergency1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='other_nationalities',
            field=models.TextField(blank=True, verbose_name='Outras nacionalidades'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='nationality',
            field=models.CharField(default='BRASILEIRA', max_length=100, verbose_name='Nacionalidade principal'),
        ),
    ]
