# Generated by Django 6.0.5 on 2026-05-30 14:15

import django.db.models.deletion
import passengers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0009_passenger_other_nationalities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassengerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('passport', 'Passaporte'), ('rg', 'Carteira de Identidade (RG)'), ('cnh', 'Carteira de Motorista (CNH)'), ('visa', 'Visto'), ('birth_cert', 'Certidão de Nascimento'), ('cpf_card', 'Cartão CPF'), ('voter_id', 'Título de Eleitor'), ('work_permit', 'Autorização de Trabalho'), ('residence', 'Comprovante de Residência'), ('other', 'Outro')], max_length=20, verbose_name='Tipo')),
                ('label', models.CharField(blank=True, max_length=200, verbose_name='Nome personalizado')),
                ('file', models.FileField(upload_to=passengers.models.secure_upload_path, verbose_name='Arquivo')),
                ('original_name', models.CharField(max_length=255, verbose_name='Nome original')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Tamanho (bytes)')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='Tipo MIME')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='passengers.passenger')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
