# Generated by Django 6.0.5 on 2026-05-31 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0010_passengerdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='country',
            field=models.CharField(blank=True, default='Brasil', max_length=100, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nome completo'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='nationality',
            field=models.CharField(blank=True, default='BRASILEIRA', max_length=100, verbose_name='Nacionalidade principal'),
        ),
    ]
