# Generated by Django 6.0.5 on 2026-05-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0010_passengerdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nome completo'),
        ),
    ]
