# Generated by Django 6.0.5 on 2026-05-31 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0011_alter_passenger_country_alter_passenger_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerdocument',
            name='doc_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Número do documento'),
        ),
        migrations.AddField(
            model_name='passengerdocument',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Validade'),
        ),
        migrations.AddField(
            model_name='passengerdocument',
            name='issued_by',
            field=models.CharField(blank=True, max_length=200, verbose_name='Emissor / Órgão'),
        ),
        migrations.AddField(
            model_name='passengerdocument',
            name='issued_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de emissão'),
        ),
    ]
