# Generated by Django 6.0.5 on 2026-05-31 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0012_passengerdocument_doc_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerdocument',
            name='doc_model',
            field=models.CharField(blank=True, max_length=20, verbose_name='Modelo do documento'),
        ),
    ]
