# Generated by Django 6.0.5 on 2026-05-31 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0013_passengerdocument_doc_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerdocument',
            name='doc_category',
            field=models.CharField(blank=True, max_length=20, verbose_name='Categoria / Classe'),
        ),
    ]
