# Generated by Django 6.0.5 on 2026-05-31 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0014_passengerdocument_doc_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='parent1_birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Pai/Mãe 1 — Data de nascimento'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='parent1_first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Pai/Mãe 1 — Primeiro nome'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='parent1_last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Pai/Mãe 1 — Sobrenome'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='parent2_birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Pai/Mãe 2 — Data de nascimento'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='parent2_first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Pai/Mãe 2 — Primeiro nome'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='parent2_last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Pai/Mãe 2 — Sobrenome'),
        ),
    ]
