# Generated by Django 6.0.5 on 2026-06-01 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0015_passenger_parent1_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='parent1_birth_date',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='parent1_first_name',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='parent1_last_name',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='parent2_birth_date',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='parent2_first_name',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='parent2_last_name',
        ),
    ]
