# Generated by Django 6.0.5 on 2026-06-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0016_remove_parent_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengerdocument',
            name='doc_type',
            field=models.CharField(choices=[('passport', 'Passaporte'), ('rg', 'Carteira de Identidade (RG)'), ('cnh', 'Carteira de Motorista (CNH)'), ('visa', 'Visto'), ('birth_cert', 'Certidão de Nascimento'), ('cpf_card', 'Cartão CPF'), ('voter_id', 'Título de Eleitor'), ('work_permit', 'Autorização de Trabalho'), ('residence', 'Comprovante de Residência'), ('vaccine', 'Vacina'), ('other', 'Outro')], max_length=20, verbose_name='Tipo'),
        ),
    ]
