# Generated by Django 6.0.5 on 2026-06-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0017_add_vaccine_doc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengerdocument',
            name='doc_type',
            field=models.CharField(max_length=50, verbose_name='Tipo'),
        ),
    ]
