# Generated by Django 6.0.5 on 2026-06-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0018_relax_doctype_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='gender',
            field=models.CharField(blank=True, max_length=100, verbose_name='Gênero'),
        ),
    ]
