# Generated by Django 6.0.5 on 2026-06-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0019_relax_gender_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='passport2',
            field=models.CharField(blank=True, max_length=50, verbose_name='Segundo passaporte'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='passport2_country',
            field=models.CharField(blank=True, max_length=10, verbose_name='País do 2º passaporte'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='passport_country',
            field=models.CharField(blank=True, max_length=10, verbose_name='País do passaporte'),
        ),
    ]
