# Generated by Django 6.0.5 on 2026-06-11 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0020_passenger_passport2_passenger_passport2_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='cpf',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='full_name',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Nome completo'),
        ),
    ]
