# Generated by Django 6.0.5 on 2026-06-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0021_alter_passenger_cpf_alter_passenger_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Excluído em'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Excluído'),
        ),
    ]
