# Generated by Django 6.0.6 on 2026-07-09 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0079_configspecialneed'),
        ('passengers', '0024_unaccent_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='special_needs',
            field=models.ManyToManyField(blank=True, related_name='passengers', to='config_api.configspecialneed', verbose_name='Necessidades especiais'),
        ),
    ]
