# Generated by Django 5.2.15 on 2026-07-16 18:02

import core.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0025_passenger_special_needs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=core.storages.public_media_storage, upload_to='passengers/', verbose_name='Foto'),
        ),
    ]
