# Generated by Django 6.0.5 on 2026-06-11 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passengers_view_basic', models.BooleanField(default=False)),
                ('passengers_view_full', models.BooleanField(default=False)),
                ('passengers_edit', models.BooleanField(default=False)),
                ('passengers_delete', models.BooleanField(default=False)),
                ('passengers_download_docs', models.BooleanField(default=False)),
                ('lists_view', models.BooleanField(default=False)),
                ('lists_edit', models.BooleanField(default=False)),
                ('lists_delete', models.BooleanField(default=False)),
                ('lists_view_logs', models.BooleanField(default=False)),
                ('manage_users', models.BooleanField(default=False)),
                ('manage_settings', models.BooleanField(default=False)),
                ('view_audit_log', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permissões de usuário',
                'verbose_name_plural': 'Permissões de usuários',
            },
        ),
    ]
