# Generated by Django 6.0.5 on 2026-06-13 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0010_remove_dashboard_view_meetings'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
