# Generated by Django 6.0.5 on 2026-06-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0011_userpermissions_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='calendar_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='calendar_view_all_deadlines',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='calendar_view_birthdays',
            field=models.BooleanField(default=False),
        ),
    ]
