# Generated by Django 6.0.5 on 2026-06-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0013_grant_calendar_view_to_existing'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='email_log_preview',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='email_log_view',
            field=models.BooleanField(default=False),
        ),
    ]
