# Generated by Django 6.0.5 on 2026-06-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0014_email_log_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='email_resend_actions',
            field=models.BooleanField(default=False),
        ),
    ]
