# Generated by Django 6.0.5 on 2026-06-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0016_userpermissions_log_agencies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='users_set_password',
            field=models.BooleanField(default=False),
        ),
    ]
