# Generated by Django 6.0.5 on 2026-06-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0017_userpermissions_users_set_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='settings_user_profiles',
            field=models.BooleanField(default=False),
        ),
    ]
