# Generated by Django 6.0.5 on 2026-06-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0018_userpermissions_settings_user_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='users_block',
            field=models.BooleanField(default=False),
        ),
    ]
