# Generated by Django 6.0.5 on 2026-06-19 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0021_userpermissions_settings_accommodations_bulk_delete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='settings_accommodations_bulk_import',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_airlines_bulk_import',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_airports_bulk_import',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_countries_bulk_import',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_crew_roles_bulk_import',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_doc_types_bulk_import',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_genders_bulk_import',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_languages_bulk_import',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_list_additionals_bulk_import',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_list_categories_bulk_import',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_prof_cards_bulk_import',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_professions_bulk_import',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_vaccines_bulk_import',
            field=models.BooleanField(default=False),
        ),
    ]
