# Generated by Django 6.0.5 on 2026-06-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0022_add_bulk_import_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='settings_airlines_import_web',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_airports_import_web',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_countries_import_web',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_languages_import_web',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_prof_cards_import_web',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_professions_import_web',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_vaccines_import_web',
            field=models.BooleanField(default=False),
        ),
    ]
