# Generated by Django 6.0.5 on 2026-06-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0023_userpermissions_settings_airlines_import_web_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='log_page_views',
            field=models.BooleanField(default=False),
        ),
    ]
