# Generated by Django 6.0.5 on 2026-06-23 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0024_userpermissions_log_page_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpermissions',
            name='log_agencies',
        ),
        migrations.RemoveField(
            model_name='userpermissions',
            name='log_lists',
        ),
        migrations.RemoveField(
            model_name='userpermissions',
            name='log_passengers',
        ),
        migrations.RemoveField(
            model_name='userpermissions',
            name='log_settings',
        ),
        migrations.RemoveField(
            model_name='userpermissions',
            name='log_users',
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_view_logs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='users_view_logs',
            field=models.BooleanField(default=False),
        ),
    ]
