# Generated by Django 6.0.5 on 2026-06-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0025_remove_userpermissions_log_agencies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Excluído em'),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Excluído'),
        ),
    ]
