# Generated by Django 6.0.5 on 2026-06-24 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0026_userpermissions_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Termos aceitos em'),
        ),
    ]
