# Generated by Django 6.0.5 on 2026-06-24 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0027_userpermissions_terms_accepted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='settings_contract_clauses_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_contract_clauses_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_contract_clauses_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_terms_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_terms_view',
            field=models.BooleanField(default=False),
        ),
    ]
