# Generated by Django 6.0.5 on 2026-06-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0028_userpermissions_settings_contract_clauses_delete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='contracts_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='contracts_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='contracts_view',
            field=models.BooleanField(default=False),
        ),
    ]
