# Generated by Django 6.0.5 on 2026-06-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0029_userpermissions_contracts_delete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='settings_exchange_rates_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_exchange_rates_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_exchange_rates_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_payment_methods_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_payment_methods_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_payment_methods_view',
            field=models.BooleanField(default=False),
        ),
    ]
