# Generated by Django 6.0.5 on 2026-06-25 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0032_userpermissions_settings_destinations_bulk_import_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpermissions',
            name='settings_continents_bulk_import',
        ),
        migrations.RemoveField(
            model_name='userpermissions',
            name='settings_continents_delete',
        ),
        migrations.RemoveField(
            model_name='userpermissions',
            name='settings_continents_edit',
        ),
        migrations.RemoveField(
            model_name='userpermissions',
            name='settings_continents_view',
        ),
    ]
