# Generated by Django 6.0.5 on 2026-06-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0033_remove_userpermissions_settings_continents_bulk_import_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='settings_holidays_bulk_import',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_holidays_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_holidays_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_holidays_view',
            field=models.BooleanField(default=False),
        ),
    ]
