# Generated by Django 6.0.5 on 2026-06-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0034_userpermissions_settings_holidays_bulk_import_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='settings_services_bulk_import',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_services_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_services_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_services_view',
            field=models.BooleanField(default=False),
        ),
    ]
