# Generated by Django 6.0.5 on 2026-06-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0035_userpermissions_settings_services_bulk_import_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='settings_itinerary_templates_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_itinerary_templates_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_itinerary_templates_view',
            field=models.BooleanField(default=False),
        ),
    ]
