# Generated by Django 6.0.5 on 2026-06-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0036_userpermissions_settings_itinerary_templates_delete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='settings_operating_company_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_operating_company_view',
            field=models.BooleanField(default=False),
        ),
    ]
