# Generated by Django 6.0.5 on 2026-06-29 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0037_userpermissions_settings_operating_company_edit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='contracts_view_logs',
            field=models.BooleanField(default=False),
        ),
    ]
