# Generated by Django 6.0.5 on 2026-06-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0041_recompute_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='settings_exchange_rates_advanced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_exchange_rates_rounding',
            field=models.BooleanField(default=False),
        ),
    ]
