# Generated by Django 6.0.5 on 2026-06-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0043_userpermissions_settings_bus_maps_bulk_import_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='contracts_change_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
