# Generated by Django 6.0.5 on 2026-06-29 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0044_userpermissions_contracts_change_seller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='contracts_edit_exchange_rate',
            field=models.BooleanField(default=False),
        ),
    ]
