# Generated by Django 6.0.5 on 2026-06-29 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0045_userpermissions_contracts_edit_exchange_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='contracts_custom_clauses',
            field=models.BooleanField(default=False),
        ),
    ]
