# Generated by Django 6.0.5 on 2026-06-30 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0046_userpermissions_contracts_custom_clauses'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='contracts_clauses_edit',
            field=models.BooleanField(default=False),
        ),
    ]
