# Generated by Django 6.0.5 on 2026-07-01 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0047_userpermissions_contracts_clauses_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='settings_exchange_rates_update_now',
            field=models.BooleanField(default=False),
        ),
    ]
