# Generated by Django 6.0.5 on 2026-07-01 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0048_userpermissions_settings_exchange_rates_update_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='contracts_review',
            field=models.BooleanField(default=False),
        ),
    ]
