# Generated by Django 6.0.5 on 2026-07-01 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0049_userpermissions_contracts_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='contracts_invoice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='contracts_invoice_view',
            field=models.BooleanField(default=False),
        ),
    ]
