# Generated by Django 6.0.6 on 2026-07-02 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0047_permissionprofile_is_agency_default'),
        ('users_api', '0050_userpermissions_contracts_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_permissions', to='config_api.permissionprofile', verbose_name='Perfil de permissão vinculado'),
        ),
    ]
