# Generated by Django 6.0.6 on 2026-07-03 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0051_userpermissions_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpermissions',
            name='settings_destinations',
        ),
        migrations.RemoveField(
            model_name='userpermissions',
            name='settings_destinations_bulk_delete',
        ),
        migrations.RemoveField(
            model_name='userpermissions',
            name='settings_destinations_bulk_import',
        ),
        migrations.RemoveField(
            model_name='userpermissions',
            name='settings_destinations_delete',
        ),
        migrations.RemoveField(
            model_name='userpermissions',
            name='settings_destinations_edit',
        ),
        migrations.RemoveField(
            model_name='userpermissions',
            name='settings_destinations_export',
        ),
        migrations.RemoveField(
            model_name='userpermissions',
            name='settings_destinations_view',
        ),
        migrations.RemoveField(
            model_name='userpermissions',
            name='settings_holidays_bulk_delete',
        ),
        migrations.RemoveField(
            model_name='userpermissions',
            name='settings_holidays_bulk_import',
        ),
        migrations.RemoveField(
            model_name='userpermissions',
            name='settings_holidays_delete',
        ),
        migrations.RemoveField(
            model_name='userpermissions',
            name='settings_holidays_edit',
        ),
        migrations.RemoveField(
            model_name='userpermissions',
            name='settings_holidays_export',
        ),
        migrations.RemoveField(
            model_name='userpermissions',
            name='settings_holidays_view',
        ),
        migrations.RemoveField(
            model_name='userpermissions',
            name='settings_itinerary_templates_bulk_delete',
        ),
        migrations.RemoveField(
            model_name='userpermissions',
            name='settings_itinerary_templates_bulk_import',
        ),
        migrations.RemoveField(
            model_name='userpermissions',
            name='settings_itinerary_templates_delete',
        ),
        migrations.RemoveField(
            model_name='userpermissions',
            name='settings_itinerary_templates_edit',
        ),
        migrations.RemoveField(
            model_name='userpermissions',
            name='settings_itinerary_templates_export',
        ),
        migrations.RemoveField(
            model_name='userpermissions',
            name='settings_itinerary_templates_view',
        ),
        migrations.RemoveField(
            model_name='userpermissions',
            name='settings_services_bulk_delete',
        ),
        migrations.RemoveField(
            model_name='userpermissions',
            name='settings_services_bulk_import',
        ),
        migrations.RemoveField(
            model_name='userpermissions',
            name='settings_services_delete',
        ),
        migrations.RemoveField(
            model_name='userpermissions',
            name='settings_services_edit',
        ),
        migrations.RemoveField(
            model_name='userpermissions',
            name='settings_services_export',
        ),
        migrations.RemoveField(
            model_name='userpermissions',
            name='settings_services_view',
        ),
    ]
