# Generated by Django 6.0.6 on 2026-07-04 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0053_userpermissions_settings_currencies_delete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='settings_keywords_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_keywords_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_keywords_view',
            field=models.BooleanField(default=False),
        ),
    ]
