# Generated by Django 6.0.6 on 2026-07-04 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0055_userpermissions_settings_inclusions_delete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='settings_highlights_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_highlights_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_highlights_view',
            field=models.BooleanField(default=False),
        ),
    ]
