# Generated by Django 6.0.6 on 2026-07-04 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0056_userpermissions_settings_highlights_delete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='settings_special_dates_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_special_dates_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_special_dates_view',
            field=models.BooleanField(default=False),
        ),
    ]
