# Generated by Django 6.0.6 on 2026-07-05 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0057_userpermissions_settings_special_dates_delete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='settings_hotels_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_hotels_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_hotels_view',
            field=models.BooleanField(default=False),
        ),
    ]
