# Generated by Django 6.0.6 on 2026-07-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0059_userpermissions_settings_boats_delete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='settings_boats_bulk_import',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_boats_export',
            field=models.BooleanField(default=False),
        ),
    ]
