# Generated by Django 6.0.6 on 2026-07-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0060_userpermissions_settings_boats_bulk_import_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='settings_terrestre_bulk_import',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_terrestre_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_terrestre_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_terrestre_export',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_terrestre_view',
            field=models.BooleanField(default=False),
        ),
    ]
