# Generated by Django 6.0.6 on 2026-07-06 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0061_userpermissions_settings_terrestre_companies_delete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='roteiros_view_logs',
            field=models.BooleanField(default=False),
        ),
    ]
