# Generated by Django 6.0.6 on 2026-07-07 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0062_userpermissions_roteiros_view_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='gallery_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='gallery_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='gallery_view',
            field=models.BooleanField(default=False),
        ),
    ]
