# Generated by Django 6.0.6 on 2026-07-07 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0063_userpermissions_gallery_delete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='gallery_view_laminas',
            field=models.BooleanField(default=False),
        ),
    ]
