# Generated by Django 6.0.6 on 2026-07-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0064_userpermissions_gallery_view_laminas'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='roteiros_docs_create',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='roteiros_docs_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='roteiros_docs_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='roteiros_docs_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='roteiros_docs_view_own',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='roteiros_edit_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='roteiros_publish',
            field=models.BooleanField(default=False),
        ),
    ]
