# Generated by Django 6.0.6 on 2026-07-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0065_userpermissions_roteiros_docs_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='gallery_delete_images',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='gallery_delete_laminas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='gallery_delete_videos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='gallery_upload_images',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='gallery_upload_laminas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='gallery_upload_videos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='gallery_view_images',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='gallery_view_videos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='roteiros_images_from_gallery',
            field=models.BooleanField(default=False),
        ),
    ]
