# Generated by Django 6.0.6 on 2026-07-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0066_userpermissions_gallery_delete_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='roteiros_create',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='roteiros_open',
            field=models.BooleanField(default=False),
        ),
    ]
