# Generated by Django 6.0.6 on 2026-07-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0068_backfill_roteiros_open_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='roteiros_docs_delete_own',
            field=models.BooleanField(default=False),
        ),
    ]
