# Generated by Django 6.0.6 on 2026-07-07 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0069_userpermissions_roteiros_docs_delete_own'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='guides_view',
            field=models.BooleanField(default=False),
        ),
    ]
