# Generated by Django 6.0.6 on 2026-07-07 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0070_userpermissions_guides_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='roteiros_laminas_edit',
            field=models.BooleanField(default=False),
        ),
    ]
