# Generated by Django 6.0.6 on 2026-07-08 03:12

import users_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0071_userpermissions_roteiros_laminas_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=users_api.models.avatar_upload_path, verbose_name='Foto de perfil'),
        ),
    ]
