# Generated by Django 6.0.6 on 2026-07-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0073_userpermissions_documentos_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='voucher_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='voucher_view',
            field=models.BooleanField(default=False),
        ),
    ]
