# Generated by Django 6.0.6 on 2026-07-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0074_userpermissions_voucher_edit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='voucher_agency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='voucher_publish',
            field=models.BooleanField(default=False),
        ),
    ]
