# Generated by Django 6.0.6 on 2026-07-08 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0075_userpermissions_voucher_agency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='voucher_agency_past',
            field=models.BooleanField(default=False),
        ),
    ]
