# Generated by Django 6.0.6 on 2026-07-08 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0076_userpermissions_voucher_agency_past'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='voucher_flight',
            field=models.BooleanField(default=False),
        ),
    ]
