# Generated by Django 6.0.6 on 2026-07-08 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0077_userpermissions_voucher_flight'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='voucher_past',
            field=models.BooleanField(default=False),
        ),
    ]
