# Generated by Django 6.0.6 on 2026-07-09 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0082_userpermissions_settings_special_needs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='storage_limit_bytes',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Limite de armazenamento (bytes)'),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='users_storage_limit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='users_storage_view',
            field=models.BooleanField(default=False),
        ),
    ]
