# Generated by Django 6.0.6 on 2026-07-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0083_userpermissions_storage_limit_bytes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='voucher_labels',
            field=models.BooleanField(default=False),
        ),
    ]
