# Generated by Django 6.0.6 on 2026-07-09 19:44

import users_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0084_userpermissions_voucher_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='avatar_crop',
            field=models.JSONField(blank=True, default=dict, verbose_name='Recorte da foto'),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='avatar_original',
            field=models.ImageField(blank=True, null=True, upload_to=users_api.models.avatar_upload_path, verbose_name='Foto de perfil (original)'),
        ),
    ]
