# Generated by Django 6.0.6 on 2026-07-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0085_userpermissions_avatar_crop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='laminas_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='laminas_view',
            field=models.BooleanField(default=False),
        ),
    ]
