# Generated by Django 6.0.6 on 2026-07-10 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0086_userpermissions_laminas_edit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpermissions',
            name='laminas_edit',
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='laminas_agency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='laminas_agency_logo',
            field=models.BooleanField(default=False),
        ),
    ]
