# Generated by Django 6.0.6 on 2026-07-11 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0087_remove_userpermissions_laminas_edit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='settings_cost_categories_bulk_import',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_cost_categories_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_cost_categories_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_cost_categories_export',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_cost_categories_view',
            field=models.BooleanField(default=False),
        ),
    ]
