# Generated by Django 6.0.6 on 2026-07-11 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0088_userpermissions_settings_cost_categories_bulk_import_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='settings_ship_cabins_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_ship_cabins_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_ship_cabins_view',
            field=models.BooleanField(default=False),
        ),
    ]
