# Generated by Django 6.0.6 on 2026-07-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0089_userpermissions_settings_ship_cabins_delete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='dashboard_view_birthdays',
            field=models.BooleanField(default=False),
        ),
    ]
