# Generated by Django 6.0.6 on 2026-07-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0090_userpermissions_dashboard_view_birthdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='settings_flight_classes_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_flight_classes_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_flight_classes_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_flight_segments_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_flight_segments_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_flight_segments_view',
            field=models.BooleanField(default=False),
        ),
    ]
