# Generated by Django 6.0.6 on 2026-07-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0091_userpermissions_settings_flight_classes_delete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='settings_flight_classes_bulk_import',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_flight_classes_export',
            field=models.BooleanField(default=False),
        ),
    ]
