# Generated by Django 6.0.6 on 2026-07-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0093_userpermissions_settings_ship_cabins_bulk_import_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='settings_hotels_bulk_import',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_hotels_export',
            field=models.BooleanField(default=False),
        ),
    ]
