# Generated by Django 5.2.15 on 2026-07-16 18:02

import core.storages
import users_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0094_userpermissions_settings_hotels_bulk_import_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermissions',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=core.storages.public_media_storage, upload_to=users_api.models.avatar_upload_path, verbose_name='Foto de perfil'),
        ),
        migrations.AlterField(
            model_name='userpermissions',
            name='avatar_original',
            field=models.ImageField(blank=True, null=True, storage=core.storages.public_media_storage, upload_to=users_api.models.avatar_upload_path, verbose_name='Foto de perfil (original)'),
        ),
    ]
