# Generated by Django 6.0.6 on 2026-07-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0095_userpermissions_settings_tpl_required_docs_bulk_import_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='is_seller',
            field=models.BooleanField(default=False, verbose_name='Vendedor'),
        ),
    ]
