# Generated by Django 5.2.15 on 2026-07-22 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0095_alter_userpermissions_avatar_and_more'),
        ('users_api', '0096_userpermissions_is_seller'),
    ]

    operations = [
    ]
