# Generated by Django 6.0.6 on 2026-07-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0097_merge_20260722_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='commissions_export',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='commissions_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='commissions_view_all',
            field=models.BooleanField(default=False),
        ),
    ]
