# Generated by Django 6.0.6 on 2026-07-25 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0098_userpermissions_commissions_export_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='panels_view',
            field=models.BooleanField(default=False),
        ),
    ]
