# Generated by Django 6.0.6 on 2026-07-25 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0099_userpermissions_panels_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='seller_commission_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Comissão do vendedor (%)'),
        ),
    ]
