# Generated by Django 6.0.6 on 2026-07-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0100_userpermissions_seller_commission_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='contracts_book_occupied',
            field=models.BooleanField(default=False),
        ),
    ]
