# Generated by Django 6.0.6 on 2026-07-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0101_userpermissions_contracts_book_occupied'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='settings_doc_models_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_doc_models_publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_doc_models_view',
            field=models.BooleanField(default=False),
        ),
    ]
