# Generated by Django 6.0.6 on 2026-07-28 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0102_userpermissions_settings_doc_models_edit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='financeiro_cashflow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='financeiro_payables',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='financeiro_receivables',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='financeiro_view',
            field=models.BooleanField(default=False),
        ),
    ]
