# Generated by Django 6.0.6 on 2026-07-29 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0103_userpermissions_financeiro_cashflow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='financeiro_past',
            field=models.BooleanField(default=False),
        ),
    ]
