# Generated by Django 6.0.6 on 2026-07-29 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0099_configjobrole'),
        ('users_api', '0104_userpermissions_financeiro_past'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='job_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='config_api.configjobrole', verbose_name='Cargo'),
        ),
    ]
