# Generated by Django 6.0.6 on 2026-07-29 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0105_userpermissions_job_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='settings_job_roles_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_job_roles_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_job_roles_view',
            field=models.BooleanField(default=False),
        ),
    ]
