# Generated by Django 6.0.6 on 2026-07-29 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0106_userpermissions_settings_job_roles_delete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='show_on_site',
            field=models.BooleanField(default=False, verbose_name='Mostrar no site'),
        ),
    ]
