# Generated by Django 6.0.6 on 2026-07-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0107_userpermissions_show_on_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='contratos_sign',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='reservas_cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='reservas_create',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='reservas_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='reservas_view_all',
            field=models.BooleanField(default=False),
        ),
    ]
