# Generated by Django 6.0.6 on 2026-07-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0108_userpermissions_contratos_sign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='reservas_create_agency',
            field=models.BooleanField(default=False),
        ),
    ]
