# Generated by Django 6.0.6 on 2026-07-31 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0109_userpermissions_reservas_create_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='lock_photo',
            field=models.BooleanField(default=False, verbose_name='Travar foto do usuário'),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='lock_profile',
            field=models.BooleanField(default=False, verbose_name='Travar perfil do usuário'),
        ),
    ]
