# Generated by Django 6.0.6 on 2026-07-31 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0110_userpermissions_lock_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='is_promoter',
            field=models.BooleanField(default=False, verbose_name='Promotor(a)'),
        ),
    ]
