# Generated by Django 6.0.6 on 2026-07-31 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0111_userpermissions_is_promoter'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='reservas_overbook',
            field=models.BooleanField(default=False),
        ),
    ]
