# Generated by Django 6.0.6 on 2026-07-31 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0112_userpermissions_reservas_overbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='reservas_delete',
            field=models.BooleanField(default=False),
        ),
    ]
