# Generated by Django 6.0.6 on 2026-07-31 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0113_userpermissions_reservas_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='reservas_over_capacity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='reservas_over_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
