# Generated by Django 6.0.6 on 2026-08-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0114_userpermissions_reservas_over_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='reservas_view_availability',
            field=models.BooleanField(default=True),
        ),
    ]
