# Generated by Django 6.0.6 on 2026-08-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0115_userpermissions_reservas_view_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='fornecedores_create',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='fornecedores_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='fornecedores_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='fornecedores_export',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='fornecedores_import',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='fornecedores_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='fornecedores_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='fornecedores_view_logs',
            field=models.BooleanField(default=False),
        ),
    ]
