# Generated by Django 6.0.6 on 2026-08-01 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0116_userpermissions_fornecedores_create_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpermissions',
            name='settings_operating_company_contatos_edit',
        ),
        migrations.RemoveField(
            model_name='userpermissions',
            name='settings_operating_company_contatos_view',
        ),
    ]
