# Generated by Django 6.0.6 on 2026-08-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0117_remove_userpermissions_settings_operating_company_contatos_edit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='panels_view_values',
            field=models.BooleanField(default=False),
        ),
    ]
