# Generated by Django 6.0.6 on 2026-08-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0118_userpermissions_panels_view_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='settings_ai_connectors_bulk_import',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_ai_connectors_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_ai_connectors_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_ai_connectors_export',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='settings_ai_connectors_view',
            field=models.BooleanField(default=False),
        ),
    ]
