# Generated by Django 6.0.6 on 2026-08-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0119_userpermissions_settings_ai_connectors_bulk_import_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='agencies_export',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='agencies_import',
            field=models.BooleanField(default=False),
        ),
    ]
