# Generated by Django 6.0.6 on 2026-08-19 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0120_userpermissions_agencies_export_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='financeiro_settle',
            field=models.BooleanField(default=False),
        ),
    ]
