# Generated by Django 6.0.6 on 2026-08-20 14:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0114_remove_paymentgateway_payment_url'),
        ('users_api', '0121_userpermissions_financeiro_settle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='cpf',
            field=models.CharField(blank=True, db_index=True, default='', max_length=11, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='former_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail anterior'),
        ),
        migrations.AddConstraint(
            model_name='userpermissions',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('cpf', ''), _negated=True)), fields=('cpf',), name='uniq_cpf_usuario_ativo'),
        ),
    ]
