# Generated by Django 6.0.5 on 2026-05-29 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('passengers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Destino')),
                ('country', models.CharField(max_length=100, verbose_name='País')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('image', models.ImageField(blank=True, null=True, upload_to='destinations/', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Destino',
                'verbose_name_plural': 'Destinos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('departure_date', models.DateField(verbose_name='Data de partida')),
                ('return_date', models.DateField(verbose_name='Data de retorno')),
                ('max_passengers', models.PositiveIntegerField(verbose_name='Máximo de passageiros')),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço por pessoa')),
                ('status', models.CharField(choices=[('planning', 'Em planejamento'), ('open', 'Aberta'), ('full', 'Lotada'), ('ongoing', 'Em andamento'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='planning', max_length=20, verbose_name='Status')),
                ('itinerary', models.TextField(blank=True, verbose_name='Itinerário')),
                ('includes', models.TextField(blank=True, verbose_name='O que inclui')),
                ('excludes', models.TextField(blank=True, verbose_name='O que não inclui')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trips.destination', verbose_name='Destino')),
            ],
            options={
                'verbose_name': 'Viagem',
                'verbose_name_plural': 'Viagens',
                'ordering': ['-departure_date'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Status')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='Inscrito em')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='passengers.passenger', verbose_name='Passageiro')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='trips.trip', verbose_name='Viagem')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
                'unique_together': {('trip', 'passenger')},
            },
        ),
    ]
