# Generated by Django 6.0.5 on 2026-06-02 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0019_relax_gender_choices'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListAdditional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Adicional',
                'verbose_name_plural': 'Adicionais',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': 'Inscrição'},
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='passengers.passenger'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='trips.trip'),
        ),
        migrations.CreateModel(
            name='PassengerList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Nome')),
                ('list_type', models.CharField(choices=[('aereo', 'Aéreo'), ('terrestre', 'Terrestre'), ('maritimo', 'Marítimo'), ('fluvial', 'Fluvial'), ('misto', 'Misto')], default='aereo', max_length=20, verbose_name='Tipo')),
                ('category', models.CharField(choices=[('internacional', 'Internacional'), ('nacional', 'Nacional')], default='internacional', max_length=20, verbose_name='Categoria')),
                ('block_capacity', models.PositiveIntegerField(default=0, verbose_name='Capacidade do bloqueio')),
                ('total_accommodations', models.PositiveIntegerField(default=0, verbose_name='Total de acomodações')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Data de início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de término')),
                ('required_document', models.CharField(blank=True, choices=[('', 'Nenhum'), ('passaporte', 'Passaporte'), ('rg', 'RG'), ('cnh', 'CNH'), ('visto', 'Visto')], max_length=20, verbose_name='Documento requerido')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('fechada', 'Fechada')], default='aberta', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('additionals', models.ManyToManyField(blank=True, related_name='passenger_lists', to='trips.listadditional', verbose_name='Adicionais')),
                ('suppliers', models.ManyToManyField(blank=True, related_name='passenger_lists', to='trips.supplier', verbose_name='Fornecedores')),
            ],
            options={
                'verbose_name': 'Lista de Passageiros',
                'verbose_name_plural': 'Listas de Passageiros',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='Adicionado em')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_enrollments', to='passengers.passenger', verbose_name='Passageiro')),
                ('passenger_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_enrollments', to='trips.passengerlist', verbose_name='Lista')),
            ],
            options={
                'verbose_name': 'Passageiro na lista',
                'verbose_name_plural': 'Passageiros na lista',
                'ordering': ['enrolled_at'],
                'unique_together': {('passenger_list', 'passenger')},
            },
        ),
    ]
