# Generated by Django 6.0.5 on 2026-06-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_passenger_list_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passengerlist',
            name='required_document',
        ),
        migrations.AddField(
            model_name='passengerlist',
            name='required_documents',
            field=models.JSONField(blank=True, default=list, verbose_name='Documentos requeridos'),
        ),
        migrations.AlterField(
            model_name='passengerlist',
            name='list_type',
            field=models.CharField(choices=[('aereo', 'Via Aéreo'), ('onibus', 'Via Ônibus'), ('maritimo', 'Via Marítimo')], default='aereo', max_length=20, verbose_name='Tipo'),
        ),
    ]
