# Generated by Django 6.0.5 on 2026-06-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_required_documents_jsonfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerlist',
            name='roteiro',
            field=models.TextField(blank=True, verbose_name='Roteiro'),
        ),
        migrations.AlterField(
            model_name='passengerlist',
            name='list_type',
            field=models.CharField(choices=[('aereo', 'Via Aéreo'), ('terrestre', 'Via Terrestre')], default='aereo', max_length=20, verbose_name='Tipo'),
        ),
    ]
