# Generated by Django 6.0.5 on 2026-06-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_add_roteiro_to_passengerlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roteiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Roteiro',
                'verbose_name_plural': 'Roteiros',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='passengerlist',
            name='roteiro',
        ),
        migrations.AddField(
            model_name='passengerlist',
            name='roteiros',
            field=models.ManyToManyField(blank=True, related_name='passenger_lists', to='trips.roteiro', verbose_name='Roteiros'),
        ),
    ]
