# Generated by Django 6.0.5 on 2026-06-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_roteiro_m2m'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listenrollment',
            options={'ordering': ['order_in_list', 'enrolled_at'], 'verbose_name': 'Passageiro na lista', 'verbose_name_plural': 'Passageiros na lista'},
        ),
        migrations.AddField(
            model_name='listenrollment',
            name='accommodation',
            field=models.CharField(blank=True, max_length=200, verbose_name='Acomodação'),
        ),
        migrations.AddField(
            model_name='listenrollment',
            name='enrollment_status',
            field=models.CharField(choices=[('confirmado', 'Confirmado'), ('pendente', 'Pendente'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='listenrollment',
            name='order_in_list',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem'),
        ),
    ]
