# Generated by Django 6.0.5 on 2026-06-02 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0019_relax_gender_choices'),
        ('trips', '0006_enrollment_accommodation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='listenrollment',
            name='block_agency',
            field=models.CharField(blank=True, max_length=200, verbose_name='Agência (bloqueio)'),
        ),
        migrations.AddField(
            model_name='listenrollment',
            name='is_block',
            field=models.BooleanField(default=False, verbose_name='É bloqueio'),
        ),
        migrations.AlterField(
            model_name='listenrollment',
            name='passenger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_enrollments', to='passengers.passenger', verbose_name='Passageiro'),
        ),
    ]
