# Generated by Django 6.0.5 on 2026-06-02 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0006_add_agency_member'),
        ('trips', '0007_enrollment_block_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='listenrollment',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_enrollments', to='agencies.agency', verbose_name='Agência'),
        ),
    ]
