# Generated by Django 6.0.5 on 2026-06-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_enrollment_responsible_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='listenrollment',
            name='pending_reason',
            field=models.TextField(blank=True, verbose_name='Motivo da pendência'),
        ),
        migrations.AddField(
            model_name='listenrollment',
            name='pending_until',
            field=models.DateField(blank=True, null=True, verbose_name='Pendente até'),
        ),
    ]
