# Generated by Django 6.0.5

from django.db import migrations, models


RENAME = {
    'internacional': 'Internacional',
    'nacional':      'Nacional',
}


def rename_existing(apps, schema_editor):
    PassengerList = apps.get_model('trips', 'PassengerList')
    for old, new in RENAME.items():
        PassengerList.objects.filter(category=old).update(category=new)


def rename_back(apps, schema_editor):
    PassengerList = apps.get_model('trips', 'PassengerList')
    for old, new in RENAME.items():
        PassengerList.objects.filter(category=new).update(category=old)


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0010_enrollment_pending_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengerlist',
            name='category',
            field=models.CharField(default='Internacional', max_length=100, verbose_name='Categoria'),
        ),
        migrations.RunPython(rename_existing, rename_back),
    ]
