# Generated by Django 6.0.5 on 2026-06-08 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0011_list_category_freeform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('passenger_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='trips.passengerlist', verbose_name='Lista')),
            ],
            options={
                'verbose_name': 'Acomodação',
                'verbose_name_plural': 'Acomodações',
                'ordering': ['name'],
                'unique_together': {('passenger_list', 'name')},
            },
        ),
    ]
