# Generated by Django 6.0.5 on 2026-06-08 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0012_airport'),
        ('trips', '0012_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='listenrollment',
            name='departure_airport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='config_api.airport', verbose_name='Aeroporto de saída'),
        ),
        migrations.AddField(
            model_name='passengerlist',
            name='default_airport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_lists', to='config_api.airport', verbose_name='Aeroporto de saída padrão'),
        ),
    ]
