# Generated by Django 6.0.5 on 2026-06-08 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0012_airport'),
        ('trips', '0013_listenrollment_departure_airport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerlist',
            name='departure_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='config_api.configcity', verbose_name='Cidade de saída'),
        ),
        migrations.AddField(
            model_name='passengerlist',
            name='departure_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='config_api.configcountry', verbose_name='País de saída'),
        ),
        migrations.AddField(
            model_name='passengerlist',
            name='departure_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='config_api.configstate', verbose_name='Estado de saída'),
        ),
    ]
