# Generated by Django 6.0.5 on 2026-06-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0014_passengerlist_departure_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listenrollment',
            name='connection_ticket_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Número da reserva (conexão)'),
        ),
        migrations.AddField(
            model_name='listenrollment',
            name='connection_ticket_seat',
            field=models.CharField(blank=True, max_length=20, verbose_name='Assento (conexão)'),
        ),
        migrations.AddField(
            model_name='listenrollment',
            name='connection_ticket_status',
            field=models.CharField(choices=[('nao_emitida', 'Não emitida'), ('via_bloqueio', 'Emitida via bloqueio'), ('fora_bloqueio', 'Emitida fora do bloqueio')], default='nao_emitida', max_length=20, verbose_name='Status da passagem de conexão'),
        ),
        migrations.AddField(
            model_name='listenrollment',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Número da reserva'),
        ),
        migrations.AddField(
            model_name='listenrollment',
            name='ticket_seat',
            field=models.CharField(blank=True, max_length=20, verbose_name='Assento'),
        ),
        migrations.AddField(
            model_name='listenrollment',
            name='ticket_status',
            field=models.CharField(choices=[('nao_emitida', 'Não emitida'), ('via_bloqueio', 'Emitida via bloqueio'), ('fora_bloqueio', 'Emitida fora do bloqueio')], default='nao_emitida', max_length=20, verbose_name='Status da passagem'),
        ),
    ]
