# Generated by Django 6.0.5 on 2026-06-08 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0012_airport'),
        ('trips', '0015_ticket_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('ida', 'Ida'), ('volta', 'Volta')], default='ida', max_length=10, verbose_name='Direção')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('flight_number', models.CharField(blank=True, max_length=20, verbose_name='Número do voo')),
                ('airline', models.CharField(blank=True, max_length=100, verbose_name='Companhia aérea')),
                ('departure_date', models.DateField(blank=True, null=True, verbose_name='Data de partida')),
                ('departure_time', models.TimeField(blank=True, null=True, verbose_name='Horário de partida')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination_airport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='config_api.airport', verbose_name='Aeroporto de destino')),
                ('origin_airport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='config_api.airport', verbose_name='Aeroporto de origem')),
                ('passenger_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_legs', to='trips.passengerlist', verbose_name='Lista')),
            ],
            options={
                'verbose_name': 'Trecho de voo',
                'verbose_name_plural': 'Trechos de voo',
                'ordering': ['direction', 'order', 'departure_date', 'departure_time'],
            },
        ),
    ]
