# Generated by Django 6.0.5 on 2026-06-08 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0016_flight_leg'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightleg',
            name='arrival_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de chegada'),
        ),
        migrations.AddField(
            model_name='flightleg',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário de chegada'),
        ),
    ]
