# Generated by Django 6.0.5 on 2026-06-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0020_feeder_leg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listenrollment',
            name='enrollment_status',
            field=models.CharField(choices=[('confirmado', 'Confirmado'), ('pendente', 'Pendente'), ('reservado', 'Reservado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='passengerflightleg',
            name='direction',
            field=models.CharField(choices=[('ida', 'Ida'), ('volta', 'Volta'), ('feeder', 'Acesso')], default='ida', max_length=10, verbose_name='Direção'),
        ),
    ]
