# Generated by Django 6.0.5 on 2026-06-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0021_add_reservado_enrollment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='listenrollment',
            name='is_provisional',
            field=models.BooleanField(default=False, verbose_name='É provisório'),
        ),
    ]
