# Generated by Django 6.0.5 on 2026-06-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0022_add_is_provisional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightleg',
            name='destination_airport',
        ),
        migrations.RemoveField(
            model_name='flightleg',
            name='origin_airport',
        ),
        migrations.RemoveField(
            model_name='flightleg',
            name='passenger_list',
        ),
        migrations.RemoveField(
            model_name='passengerflightleg',
            name='destination_airport',
        ),
        migrations.RemoveField(
            model_name='passengerflightleg',
            name='enrollment',
        ),
        migrations.RemoveField(
            model_name='passengerflightleg',
            name='origin_airport',
        ),
        migrations.RemoveField(
            model_name='listenrollment',
            name='connection_ticket_number',
        ),
        migrations.RemoveField(
            model_name='listenrollment',
            name='connection_ticket_seat',
        ),
        migrations.RemoveField(
            model_name='listenrollment',
            name='connection_ticket_status',
        ),
        migrations.RemoveField(
            model_name='listenrollment',
            name='ticket_number',
        ),
        migrations.RemoveField(
            model_name='listenrollment',
            name='ticket_seat',
        ),
        migrations.AlterField(
            model_name='listenrollment',
            name='ticket_status',
            field=models.CharField(choices=[('nao_emitida', 'Não emitida'), ('via_bloqueio', 'Via bloqueio'), ('fora_bloqueio', 'Voo individual')], default='nao_emitida', max_length=20, verbose_name='Status da passagem'),
        ),
        migrations.DeleteModel(
            name='FeederLeg',
        ),
        migrations.DeleteModel(
            name='FlightLeg',
        ),
        migrations.DeleteModel(
            name='PassengerFlightLeg',
        ),
    ]
