# Generated by Django 6.0.5 on 2026-06-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0023_remove_flight_legs_and_ticket_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='listenrollment',
            name='connection_ticket_status',
            field=models.CharField(choices=[('nao_emitida', 'Não emitida'), ('via_bloqueio', 'Via bloqueio'), ('fora_bloqueio', 'Voo individual')], default='nao_emitida', max_length=20, verbose_name='Status da passagem de conexão'),
        ),
    ]
