# Generated by Django 6.0.5 on 2026-06-10 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0025_listenrollment_selected_passport'),
    ]

    operations = [
        migrations.AddField(
            model_name='listenrollment',
            name='additionals',
            field=models.ManyToManyField(blank=True, related_name='enrollments', to='trips.listadditional', verbose_name='Adicionais'),
        ),
    ]
