# Generated by Django 6.0.5 on 2026-06-10 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0026_listenrollment_additionals'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrewRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Função da equipe técnica',
                'verbose_name_plural': 'Funções da equipe técnica',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='listenrollment',
            name='crew_roles',
            field=models.ManyToManyField(blank=True, related_name='enrollments', to='trips.crewrole', verbose_name='Funções da equipe técnica'),
        ),
        migrations.AddField(
            model_name='passengerlist',
            name='crew_roles',
            field=models.ManyToManyField(blank=True, related_name='passenger_lists', to='trips.crewrole', verbose_name='Funções da equipe técnica'),
        ),
    ]
