# Generated by Django 6.0.5 on 2026-06-10 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0027_crewrole_listenrollment_crew_roles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passengerlist',
            name='crew_roles',
        ),
    ]
