# Generated by Django 6.0.5 on 2026-06-11 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0028_remove_passengerlist_crew_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listenrollment',
            name='enrollment_status',
            field=models.CharField(choices=[('confirmado', 'Confirmado'), ('pendente', 'Pendente'), ('reservado', 'Reservado'), ('cancelado', 'Cancelado')], db_index=True, default='pendente', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='passengerlist',
            name='status',
            field=models.CharField(choices=[('aberta', 'Aberta'), ('fechada', 'Fechada')], db_index=True, default='aberta', max_length=20, verbose_name='Status'),
        ),
    ]
