# Generated by Django 6.0.5 on 2026-06-15 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0017_remove_busmap_deck_busmaprow_deck'),
        ('trips', '0030_listenrollment_pending_until_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerlist',
            name='bus_map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passenger_lists', to='config_api.busmap', verbose_name='Mapa de assentos de ônibus'),
        ),
    ]
