# Generated by Django 6.0.5 on 2026-06-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0031_passengerlist_bus_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='listenrollment',
            name='seat',
            field=models.CharField(blank=True, max_length=10, verbose_name='Assento'),
        ),
    ]
