# Generated by Django 6.0.5 on 2026-06-15 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0017_remove_busmap_deck_busmaprow_deck'),
        ('trips', '0032_listenrollment_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='listenrollment',
            name='origin_airport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='config_api.airport', verbose_name='Aeroporto de origem'),
        ),
        migrations.AddField(
            model_name='listenrollment',
            name='origin_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='config_api.configcity', verbose_name='Cidade de origem'),
        ),
        migrations.AddField(
            model_name='listenrollment',
            name='origin_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='config_api.configcountry', verbose_name='País de origem'),
        ),
        migrations.AddField(
            model_name='listenrollment',
            name='origin_mode',
            field=models.CharField(blank=True, choices=[('bus', 'Ônibus'), ('plane', 'Avião')], max_length=10, verbose_name='Modo de origem'),
        ),
        migrations.AddField(
            model_name='listenrollment',
            name='origin_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='config_api.configstate', verbose_name='Estado de origem'),
        ),
    ]
