# Generated by Django 6.0.5 on 2026-06-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0033_listenrollment_origin_airport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerlist',
            name='revision',
            field=models.PositiveIntegerField(default=1, verbose_name='Revisão'),
        ),
    ]
