# Generated by Django 6.0.5 on 2026-06-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0034_passengerlist_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerlist',
            name='notification_emails',
            field=models.JSONField(blank=True, default=list, verbose_name='E-mails de notificação'),
        ),
    ]
