# Generated by Django 6.0.5 on 2026-06-16 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0035_passengerlist_notification_emails'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Tarefa')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Prazo')),
                ('done', models.BooleanField(default=False, verbose_name='Concluída')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('passenger_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='trips.passengerlist', verbose_name='Lista')),
            ],
            options={
                'verbose_name': 'Tarefa da lista',
                'verbose_name_plural': 'Tarefas da lista',
                'ordering': ['due_date', 'created_at'],
            },
        ),
    ]
