# Generated by Django 6.0.5 on 2026-06-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0037_passengerlist_deleted_at_passengerlist_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='same_sex_ack',
            field=models.BooleanField(default=False, verbose_name='Casal mesmo sexo confirmado'),
        ),
    ]
