# Generated by Django 6.0.6 on 2026-07-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0060_itinerary_badge_color_itinerary_badge_text'),
        ('trips', '0038_room_same_sex_ack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengerlist',
            name='roteiros',
            field=models.ManyToManyField(blank=True, related_name='passenger_lists', to='itineraries.itinerary', verbose_name='Roteiros'),
        ),
    ]
