# Generated by Django 6.0.6 on 2026-07-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0075_systemsettings_color_primary_and_more'),
        ('trips', '0039_alter_passengerlist_roteiros'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerlist',
            name='default_airports',
            field=models.ManyToManyField(blank=True, related_name='base_lists', to='config_api.airport', verbose_name='Aeroportos base'),
        ),
    ]
