# Generated by Django 5.2.15 on 2026-07-16 18:02

import core.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0041_backfill_list_type_from_transport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=core.storages.public_media_storage, upload_to='destinations/', verbose_name='Imagem'),
        ),
    ]
