# Generated by Django 6.0.6 on 2026-08-06 18:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0042_alter_destination_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerlist',
            name='notification_excluded_users',
            field=models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Fixos que não recebem os avisos desta lista'),
        ),
        migrations.AddField(
            model_name='passengerlist',
            name='notification_users',
            field=models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuários que recebem os avisos desta lista'),
        ),
        migrations.AlterField(
            model_name='passengerlist',
            name='notification_emails',
            field=models.JSONField(blank=True, default=list, verbose_name='E-mails de notificação (legado)'),
        ),
    ]
