# Generated by Django 6.0.6 on 2026-08-07 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_reservationroom_guests'),
        ('trips', '0043_passengerlist_notification_excluded_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listenrollment',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='reservations.reservation', verbose_name='Reserva de origem'),
        ),
    ]
