# Generated by Django 6.0.6 on 2026-08-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0044_listenrollment_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='listenrollment',
            name='origin',
            field=models.CharField(blank=True, choices=[('', 'Manual'), ('reserva', 'Reserva'), ('contrato', 'Contrato')], db_index=True, default='', max_length=10, verbose_name='Origem'),
        ),
    ]
