# Generated by Django 6.0.5 on 2026-06-01 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('code', models.CharField(blank=True, max_length=10, verbose_name='Código ISO')),
            ],
            options={
                'verbose_name': 'País',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConfigLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Idioma',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConfigProfession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Profissão',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConfigState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Código')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='config_api.configcountry')),
            ],
            options={
                'verbose_name': 'Estado',
                'ordering': ['name'],
                'unique_together': {('country', 'name')},
            },
        ),
    ]
