# Generated by Django 6.0.5 on 2026-06-01 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='config_api.configstate')),
            ],
            options={
                'verbose_name': 'Cidade',
                'ordering': ['name'],
                'unique_together': {('state', 'name')},
            },
        ),
    ]
