# Generated by Django 6.0.5 on 2026-06-01 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0004_add_configgender'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDocField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(verbose_name='Chave')),
                ('label', models.CharField(max_length=100, verbose_name='Label')),
                ('field_type', models.CharField(choices=[('text', 'Texto livre'), ('date', 'Data'), ('list', 'Lista suspensa'), ('country', 'País / Estado / Cidade')], default='text', max_length=20, verbose_name='Tipo')),
                ('required', models.BooleanField(default=False, verbose_name='Obrigatório')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Campo de documento',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CustomDocType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True, verbose_name='Chave')),
                ('label', models.CharField(max_length=100, verbose_name='Nome')),
                ('icon', models.CharField(default='📄', max_length=10, verbose_name='Ícone (emoji)')),
                ('color', models.CharField(default='#475569', max_length=20, verbose_name='Cor')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Tipo de documento',
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='CustomDocFieldOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200, verbose_name='Valor')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='config_api.customdocfield')),
            ],
            options={
                'verbose_name': 'Opção de campo',
                'ordering': ['order', 'value'],
            },
        ),
        migrations.AddField(
            model_name='customdocfield',
            name='doc_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='config_api.customdoctype'),
        ),
        migrations.AlterUniqueTogether(
            name='customdocfield',
            unique_together={('doc_type', 'key')},
        ),
    ]
