# Generated by Django 6.0.5 on 2026-06-01 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0005_add_customdoctype'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdocfield',
            name='subtype',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Subtipo'),
        ),
    ]
