# Generated by Django 6.0.5 on 2026-06-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0006_add_docfield_subtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customdocfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Texto livre'), ('date', 'Data'), ('list', 'Lista suspensa'), ('country', 'País / Estado / Cidade'), ('language', 'Idioma'), ('profession', 'Profissão')], default='text', max_length=20, verbose_name='Tipo'),
        ),
    ]
