# Generated by Django 6.0.5 on 2026-06-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0007_add_language_profession_field_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigProfCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Carteira profissional',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='customdocfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Texto livre'), ('date', 'Data'), ('list', 'Lista suspensa'), ('country', 'País / Estado / Cidade'), ('language', 'Idioma'), ('profession', 'Profissão'), ('prof_card', 'Carteira profissional')], default='text', max_length=20, verbose_name='Tipo'),
        ),
    ]
