# Generated by Django 6.0.5 on 2026-06-02 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0008_add_profcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigAccommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tipo de acomodação',
                'verbose_name_plural': 'Tipos de acomodação',
                'ordering': ['name'],
            },
        ),
    ]
