# Generated by Django 6.0.5 on 2026-06-02 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0009_add_config_accommodation'),
    ]

    operations = [
        migrations.AddField(
            model_name='configaccommodation',
            name='capacity',
            field=models.PositiveIntegerField(default=1, verbose_name='Capacidade (pessoas)'),
        ),
        migrations.AddField(
            model_name='configaccommodation',
            name='is_couple',
            field=models.BooleanField(default=False, verbose_name='É para casal'),
        ),
    ]
