# Generated by Django 6.0.5

from django.db import migrations, models


def seed_categories(apps, schema_editor):
    ConfigListCategory = apps.get_model('config_api', 'ConfigListCategory')
    for name in ['Internacional', 'Nacional']:
        ConfigListCategory.objects.get_or_create(name=name)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0010_accommodation_capacity_couple'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigListCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Categoria de lista',
                'verbose_name_plural': 'Categorias de lista',
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(seed_categories, noop),
    ]
