# Generated by Django 6.0.5 on 2026-06-08 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0011_add_configlistcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('iata_code', models.CharField(blank=True, max_length=10, verbose_name='Código IATA')),
                ('city', models.CharField(blank=True, max_length=200, verbose_name='Cidade')),
                ('country', models.CharField(blank=True, max_length=200, verbose_name='País')),
            ],
            options={
                'verbose_name': 'Aeroporto',
                'verbose_name_plural': 'Aeroportos',
                'ordering': ['name'],
            },
        ),
    ]
