# Generated by Django 6.0.5 on 2026-06-11 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0013_airline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='iata_code',
            field=models.CharField(blank=True, db_index=True, max_length=10, verbose_name='Código IATA'),
        ),
        migrations.AlterField(
            model_name='airline',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='iata_code',
            field=models.CharField(blank=True, db_index=True, max_length=10, verbose_name='Código IATA'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Nome'),
        ),
    ]
