# Generated by Django 6.0.5 on 2026-06-15 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0014_alter_airline_iata_code_alter_airline_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=60, unique=True, verbose_name='Chave')),
                ('label', models.CharField(max_length=100, verbose_name='Nome')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Mapa de ônibus',
                'verbose_name_plural': 'Mapas de ônibus',
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='BusMapRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('left_seats', models.PositiveSmallIntegerField(default=2, verbose_name='Assentos à esquerda')),
                ('right_seats', models.PositiveSmallIntegerField(default=2, verbose_name='Assentos à direita')),
                ('bus_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='config_api.busmap')),
            ],
            options={
                'verbose_name': 'Fileira de ônibus',
                'verbose_name_plural': 'Fileiras de ônibus',
                'ordering': ['order', 'id'],
            },
        ),
    ]
