# Generated by Django 6.0.5 on 2026-06-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0015_busmap_busmaprow'),
    ]

    operations = [
        migrations.AddField(
            model_name='busmap',
            name='deck',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Andar'),
        ),
        migrations.AddField(
            model_name='busmap',
            name='deck_count',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Andar único'), (2, 'Dois andares')], default=1, verbose_name='Andares do ônibus'),
        ),
        migrations.AddField(
            model_name='busmaprow',
            name='left_labels',
            field=models.JSONField(blank=True, default=list, verbose_name='Numeração à esquerda'),
        ),
        migrations.AddField(
            model_name='busmaprow',
            name='right_labels',
            field=models.JSONField(blank=True, default=list, verbose_name='Numeração à direita'),
        ),
    ]
