# Generated by Django 6.0.5 on 2026-06-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0016_busmap_deck_busmap_deck_count_busmaprow_left_labels_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busmap',
            name='deck',
        ),
        migrations.AddField(
            model_name='busmaprow',
            name='deck',
            field=models.PositiveSmallIntegerField(choices=[(1, '1º andar'), (2, '2º andar')], default=1, verbose_name='Andar'),
        ),
    ]
