# Generated by Django 6.0.5 on 2026-06-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0017_remove_busmap_deck_busmaprow_deck'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline_notification_emails', models.JSONField(blank=True, default=list, verbose_name='E-mails de notificação de prazos')),
            ],
            options={
                'verbose_name': 'Configurações do sistema',
                'verbose_name_plural': 'Configurações do sistema',
            },
        ),
    ]
