# Generated by Django 6.0.5 on 2026-06-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0018_systemsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('permissions', models.JSONField(default=dict, verbose_name='Permissões')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Perfil de permissão',
                'ordering': ['name'],
            },
        ),
    ]
