# Generated by Django 6.0.5 on 2026-06-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0019_permissionprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionprofile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Excluído em'),
        ),
        migrations.AddField(
            model_name='permissionprofile',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Excluído'),
        ),
    ]
