# Generated by Django 6.0.5 on 2026-06-23 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0020_permissionprofile_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='is_favorite',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Favorito'),
        ),
    ]
