# Generated by Django 6.0.5 on 2026-06-24 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0021_airport_is_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Categoria')),
                ('content', models.TextField(blank=True, verbose_name='Texto')),
                ('is_default', models.BooleanField(db_index=True, default=False, verbose_name='Cláusula padrão')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Excluído')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Excluído em')),
            ],
            options={
                'verbose_name': 'Cláusula de contrato',
                'verbose_name_plural': 'Cláusulas de contrato',
                'ordering': ['category', 'name'],
            },
        ),
    ]
