# Generated by Django 6.0.5 on 2026-06-24 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0022_contractclause'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractclause',
            options={'ordering': ['name'], 'verbose_name': 'Cláusula de contrato', 'verbose_name_plural': 'Cláusulas de contrato'},
        ),
        migrations.RemoveField(
            model_name='contractclause',
            name='category',
        ),
        migrations.RemoveField(
            model_name='contractclause',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='contractclause',
            name='is_deleted',
        ),
    ]
