# Generated by Django 6.0.5 on 2026-06-24 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0023_alter_contractclause_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='is_favorite',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Favorito'),
        ),
    ]
