# Generated by Django 6.0.5 on 2026-06-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0025_termsandconditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='Nome/Empresa')),
                ('cnpj', models.CharField(blank=True, max_length=20, verbose_name='CNPJ')),
                ('seller', models.CharField(blank=True, max_length=200, verbose_name='Vendedor')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone fixo')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='Celular')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Endereço')),
                ('payment_methods', models.JSONField(blank=True, default=list, verbose_name='Formas de pagamento')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Dados da operadora',
                'verbose_name_plural': 'Dados da operadora',
            },
        ),
    ]
