# Generated by Django 6.0.5 on 2026-06-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0026_operatingcompany'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Forma de pagamento',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='operatingcompany',
            name='payment_methods',
        ),
        migrations.CreateModel(
            name='ConfigExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(default='USD', max_length=10, verbose_name='De')),
                ('to_currency', models.CharField(default='BRL', max_length=10, verbose_name='Para')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Taxa')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Câmbio',
                'verbose_name_plural': 'Câmbio',
                'ordering': ['from_currency', 'to_currency'],
                'unique_together': {('from_currency', 'to_currency')},
            },
        ),
    ]
