# Generated by Django 6.0.5 on 2026-06-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0027_configpaymentmethod_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigContinent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Continente',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConfigItineraryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Categoria de Roteiro',
                'ordering': ['name'],
            },
        ),
    ]
