# Generated by Django 6.0.5 on 2026-06-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0028_configcontinent_configitinerarycategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Destino',
                'ordering': ['name'],
            },
        ),
    ]
