# Generated by Django 6.0.5 on 2026-06-25 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0029_configdestination'),
    ]

    operations = [
        migrations.AddField(
            model_name='configcountry',
            name='continent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countries', to='config_api.configcontinent', verbose_name='Continente'),
        ),
    ]
