# Generated by Django 6.0.5 on 2026-06-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0032_configservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigItineraryTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('seguro', 'Adicional de Seguro Viagem'), ('pagamento', 'Forma de Pagamento'), ('condicoes', 'Condições Gerais para Compra do Pacote'), ('documentacao', 'Documentação Necessária para a Viagem')], max_length=20, verbose_name='Tipo')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('content', models.TextField(blank=True, verbose_name='Conteúdo')),
            ],
            options={
                'verbose_name': 'Modelo de texto do Roteiro',
                'verbose_name_plural': 'Modelos de texto do Roteiro',
                'ordering': ['kind', 'name'],
            },
        ),
    ]
