# Generated by Django 6.0.5 on 2026-06-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0033_configitinerarytemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatingcompany',
            name='default_signature_type',
            field=models.CharField(choices=[('fisica', 'Física (imprimir e assinar)'), ('digital', 'Digital')], default='fisica', max_length=10, verbose_name='Assinatura padrão dos contratos'),
        ),
    ]
