# Generated by Django 6.0.5 on 2026-06-28 23:21

from django.db import migrations, models


def backfill_base_rate(apps, schema_editor):
    ConfigExchangeRate = apps.get_model('config_api', 'ConfigExchangeRate')
    for r in ConfigExchangeRate.objects.filter(base_rate__isnull=True):
        r.base_rate = r.rate
        r.save(update_fields=['base_rate'])


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0034_operatingcompany_default_signature_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='configexchangerate',
            name='auto_update',
            field=models.BooleanField(default=False, verbose_name='Atualizar automaticamente'),
        ),
        migrations.AddField(
            model_name='configexchangerate',
            name='base_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Taxa de mercado'),
        ),
        migrations.AddField(
            model_name='configexchangerate',
            name='last_auto_update',
            field=models.DateField(blank=True, null=True, verbose_name='Última atualização automática'),
        ),
        migrations.AddField(
            model_name='configexchangerate',
            name='markup_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Acréscimo (%)'),
        ),
        migrations.AddField(
            model_name='configexchangerate',
            name='update_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário da atualização'),
        ),
        migrations.AlterField(
            model_name='configexchangerate',
            name='rate',
            field=models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Taxa'),
        ),
        migrations.RunPython(backfill_base_rate, migrations.RunPython.noop),
    ]
