# Generated by Django 6.0.5 on 2026-06-28 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0035_configexchangerate_auto_update_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigExchangeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_update_time', models.TimeField(blank=True, null=True, verbose_name='Horário geral de atualização')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Configurações de câmbio',
                'verbose_name_plural': 'Configurações de câmbio',
            },
        ),
        migrations.AddField(
            model_name='configexchangerate',
            name='source_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='Link da taxa'),
        ),
    ]
