# Generated by Django 6.0.5 on 2026-06-29 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0036_configexchangesettings_configexchangerate_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='configexchangerate',
            name='script',
            field=models.TextField(blank=True, verbose_name='Script de cálculo (Python)'),
        ),
    ]
