# Generated by Django 6.0.5 on 2026-06-29 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0037_configexchangerate_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='configexchangerate',
            name='is_favorite',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Favorito'),
        ),
    ]
