# Generated by Django 6.0.5 on 2026-06-29 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0038_configexchangerate_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='configexchangerate',
            name='rate_history',
            field=models.JSONField(blank=True, default=list, verbose_name='Histórico da taxa'),
        ),
    ]
