# Generated by Django 6.0.5 on 2026-06-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0039_configexchangerate_rate_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='configexchangerate',
            name='rounding_decimals',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Casas do arredondamento'),
        ),
        migrations.AddField(
            model_name='configexchangerate',
            name='rounding_mode',
            field=models.CharField(choices=[('nearest', 'Mais próximo'), ('up', 'Pra cima'), ('down', 'Pra baixo')], default='nearest', max_length=8, verbose_name='Modo do arredondamento'),
        ),
    ]
