# Generated by Django 6.0.5 on 2026-06-29 19:13

from django.db import migrations, models


def backfill_rate_updated_at(apps, schema_editor):
    # Nas linhas que já existem, usa o `updated_at` atual como melhor estimativa
    # de quando a taxa foi atualizada pela última vez (evita ficar tudo vazio).
    ConfigExchangeRate = apps.get_model('config_api', 'ConfigExchangeRate')
    for row in ConfigExchangeRate.objects.all().only('id', 'updated_at'):
        ConfigExchangeRate.objects.filter(pk=row.pk).update(rate_updated_at=row.updated_at)


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0040_configexchangerate_rounding_decimals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configexchangerate',
            name='rate_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Taxa atualizada em'),
        ),
        migrations.RunPython(backfill_rate_updated_at, migrations.RunPython.noop),
    ]
