# Generated by Django 6.0.5 on 2026-06-30 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0041_configexchangerate_rate_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='configexchangerate',
            name='markup_percent_installment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Acréscimo parcelado (%)'),
        ),
        migrations.AddField(
            model_name='configexchangerate',
            name='rate_installment',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Taxa parcelado'),
        ),
        migrations.AlterField(
            model_name='configexchangerate',
            name='markup_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Acréscimo à vista (%)'),
        ),
        migrations.AlterField(
            model_name='configexchangerate',
            name='rate',
            field=models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Taxa à vista'),
        ),
    ]
