# Generated by Django 6.0.5 on 2026-07-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0042_configexchangerate_markup_percent_installment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatingcompany',
            name='ceo_autentique_token',
            field=models.CharField(blank=True, max_length=255, verbose_name='CEO — token de assinatura (Autentique)'),
        ),
        migrations.AddField(
            model_name='operatingcompany',
            name='ceo_auto_sign',
            field=models.BooleanField(default=False, verbose_name='Assinar automaticamente pelo CEO nos contratos digitais'),
        ),
        migrations.AddField(
            model_name='operatingcompany',
            name='ceo_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='CEO — e-mail (conta Autentique)'),
        ),
        migrations.AddField(
            model_name='operatingcompany',
            name='ceo_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='CEO — nome'),
        ),
    ]
