# Generated by Django 6.0.6 on 2026-07-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0043_operatingcompany_ceo_autentique_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigPaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('down_payment_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Entrada (% do total)')),
                ('installments_count', models.PositiveSmallIntegerField(default=0, verbose_name='Nº de parcelas')),
                ('payment_method', models.CharField(blank=True, max_length=100, verbose_name='Forma de pagamento')),
                ('first_due_days', models.PositiveSmallIntegerField(default=30, verbose_name='1º vencimento (dias após aplicar)')),
                ('interval_days', models.PositiveSmallIntegerField(default=30, verbose_name='Intervalo entre parcelas (dias)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Modelo de pagamento',
                'ordering': ['name'],
            },
        ),
    ]
