# Generated by Django 6.0.6 on 2026-07-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0045_remove_configpaymentplan_down_payment_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatingcompany',
            name='pix_key',
            field=models.CharField(blank=True, max_length=200, verbose_name='Chave PIX'),
        ),
        migrations.AddField(
            model_name='operatingcompany',
            name='pix_key_type',
            field=models.CharField(blank=True, max_length=20, verbose_name='Tipo de chave PIX'),
        ),
    ]
