# Generated by Django 6.0.6 on 2026-07-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0046_operatingcompany_pix_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionprofile',
            name='is_agency_default',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Perfil padrão dos usuários de agência'),
        ),
    ]
