# Generated by Django 6.0.6 on 2026-07-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0047_permissionprofile_is_agency_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='configpaymentplan',
            name='down_payment_method',
            field=models.CharField(blank=True, max_length=100, verbose_name='Forma de pagamento da entrada'),
        ),
    ]
