# Generated by Django 6.0.6 on 2026-07-03 15:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0048_configpaymentplan_down_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='configpaymentplan',
            name='down_payment_rounding',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.01'), max_digits=8, verbose_name='Arredondamento da entrada (R$)'),
        ),
        migrations.AddField(
            model_name='configpaymentplan',
            name='installment_rounding',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.01'), max_digits=8, verbose_name='Arredondamento das parcelas (R$)'),
        ),
    ]
