# Generated by Django 6.0.6 on 2026-07-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0049_configpaymentplan_down_payment_rounding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configpaymentplan',
            name='a_vista',
            field=models.BooleanField(default=False, verbose_name='À vista'),
        ),
    ]
