# Generated by Django 6.0.6 on 2026-07-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0050_configpaymentplan_a_vista'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatingcompany',
            name='ceo_signature',
            field=models.ImageField(blank=True, null=True, upload_to='operating/', verbose_name='CEO — assinatura (imagem)'),
        ),
    ]
