# Generated by Django 6.0.6 on 2026-07-03 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0051_operatingcompany_ceo_signature'),
        ('itineraries', '0010_remove_itinerary_about_destination_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfigDestination',
        ),
        migrations.DeleteModel(
            name='ConfigHoliday',
        ),
        migrations.DeleteModel(
            name='ConfigItineraryTemplate',
        ),
        migrations.DeleteModel(
            name='ConfigService',
        ),
    ]
