# Generated by Django 6.0.6 on 2026-07-03 20:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0052_delete_configdestination_delete_configholiday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$', 'Use o código ISO-4217 com 3 letras maiúsculas (ex.: USD).')], verbose_name='Código ISO')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('symbol', models.CharField(blank=True, max_length=8, verbose_name='Símbolo')),
            ],
            options={
                'verbose_name': 'Moeda',
                'verbose_name_plural': 'Moedas',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ConfigItineraryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tipo de Roteiro',
                'verbose_name_plural': 'Tipos de Roteiro',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConfigMaritimeCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nome')),
                ('website', models.URLField(blank=True, verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Companhia Marítima',
                'verbose_name_plural': 'Companhias Marítimas',
                'ordering': ['name'],
            },
        ),
    ]
