# Generated by Django 6.0.6 on 2026-07-03 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0054_configpaymentplan_a_vista_discount_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='a_vista_discount_mode',
            field=models.CharField(choices=[('percent', '% do total'), ('valor', 'Valor em R$')], default='percent', max_length=10, verbose_name='Tipo do desconto à vista'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='a_vista_discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Desconto à vista (valor ou %)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='a_vista_payment_method',
            field=models.CharField(blank=True, max_length=100, verbose_name='Forma de pagamento à vista'),
        ),
    ]
