# Generated by Django 6.0.6 on 2026-07-04 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0055_systemsettings_a_vista_discount_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Palavra-chave',
                'verbose_name_plural': 'Palavras-chave',
                'ordering': ['name'],
            },
        ),
    ]
