# Generated by Django 6.0.6 on 2026-07-04 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0057_configinclusion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Destaque',
                'verbose_name_plural': 'Destaques',
                'ordering': ['name'],
            },
        ),
    ]
