# Generated by Django 6.0.6 on 2026-07-04 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0058_confighighlight'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigSpecialDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Data especial',
                'verbose_name_plural': 'Datas especiais',
                'ordering': ['name'],
            },
        ),
    ]
