# Generated by Django 6.0.6 on 2026-07-05 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0059_configspecialdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingCompanyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('role', models.CharField(blank=True, max_length=200, verbose_name='Função')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefone/WhatsApp')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Contato da operadora',
                'verbose_name_plural': 'Contatos da operadora',
                'ordering': ['order', 'name'],
            },
        ),
    ]
