# Generated by Django 6.0.6 on 2026-07-05 02:29

import config_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0060_operatingcompanycontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=config_api.models.airline_logo_path, verbose_name='Logo'),
        ),
    ]
