# Generated by Django 6.0.6 on 2026-07-05 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0061_airline_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigHotelCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Categoria de hotel',
                'verbose_name_plural': 'Categorias de hotel',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConfigHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=300, verbose_name='Nome')),
                ('website', models.CharField(blank=True, max_length=500, verbose_name='Site')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Telefone')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotels', to='config_api.configcity')),
                ('categories', models.ManyToManyField(blank=True, related_name='hotels', to='config_api.confighotelcategory')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotéis',
                'ordering': ['name'],
            },
        ),
    ]
