# Generated by Django 6.0.6 on 2026-07-05 12:33

import config_api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0062_confighotelcategory_confighotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigBoat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=300, verbose_name='Nome')),
                ('website', models.CharField(blank=True, max_length=500, verbose_name='Site')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Barco',
                'verbose_name_plural': 'Barcos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConfigBoatMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=config_api.models.boat_media_path, verbose_name='Arquivo')),
                ('kind', models.CharField(default='image', max_length=10, verbose_name='Tipo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='config_api.configboat')),
            ],
            options={
                'verbose_name': 'Mídia de barco',
                'verbose_name_plural': 'Mídias de barco',
                'ordering': ['order', 'id'],
            },
        ),
    ]
