# Generated by Django 6.0.6 on 2026-07-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0063_configboat_configboatmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='confighotel',
            name='is_global',
            field=models.BooleanField(db_index=True, default=True, verbose_name='No catálogo geral'),
        ),
    ]
