# Generated by Django 6.0.6 on 2026-07-05 13:33

import config_api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0064_confighotel_is_global'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigHotelMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=config_api.models.hotel_media_path, verbose_name='Arquivo')),
                ('kind', models.CharField(default='image', max_length=10, verbose_name='Tipo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='config_api.confighotel')),
            ],
            options={
                'verbose_name': 'Mídia de hotel',
                'verbose_name_plural': 'Mídias de hotel',
                'ordering': ['order', 'id'],
            },
        ),
    ]
