# Generated by Django 6.0.6 on 2026-07-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0065_confighotelmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='configboat',
            name='is_global',
            field=models.BooleanField(db_index=True, default=True, verbose_name='No catálogo geral'),
        ),
    ]
