# Generated by Django 6.0.6 on 2026-07-05 15:38

import config_api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0066_configboat_is_global'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigTerrestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=300, verbose_name='Nome')),
                ('website', models.CharField(blank=True, max_length=500, verbose_name='Site')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('is_global', models.BooleanField(db_index=True, default=True, verbose_name='No catálogo geral')),
            ],
            options={
                'verbose_name': 'Terrestre',
                'verbose_name_plural': 'Terrestres',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConfigTerrestreMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=config_api.models.terrestre_media_path, verbose_name='Arquivo')),
                ('kind', models.CharField(default='image', max_length=10, verbose_name='Tipo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('terrestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='config_api.configterrestre')),
            ],
            options={
                'verbose_name': 'Mídia de terrestre',
                'verbose_name_plural': 'Mídias de terrestre',
                'ordering': ['order', 'id'],
            },
        ),
    ]
