# Generated by Django 6.0.6 on 2026-07-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0066_configboat_is_global'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigTerrestreCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nome')),
                ('is_favorite', models.BooleanField(db_index=True, default=False, verbose_name='Favorito')),
            ],
            options={
                'verbose_name': 'Empresa terrestre',
                'verbose_name_plural': 'Empresas terrestres',
                'ordering': ['name'],
            },
        ),
    ]
