# Generated by Django 6.0.6 on 2026-07-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0067_configterrestrecompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='configcity',
            name='name_ascii',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150),
        ),
    ]
