# Generated by Django 6.0.6 on 2026-07-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0069_populate_city_name_ascii'),
    ]

    operations = [
        migrations.AddField(
            model_name='configcity',
            name='aliases',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
