# Generated by Django 6.0.6 on 2026-07-07 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0071_seed_city_aliases'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='Favicon (ícone do navegador)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='logo_contract',
            field=models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='Logo dos contratos'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='logo_pdf',
            field=models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='Logo do PDF dos roteiros'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='logo_site',
            field=models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='Logo do site (vitrine)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='logo_system',
            field=models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='Logo do tema (sistema)'),
        ),
    ]
