# Generated by Django 6.0.6 on 2026-07-07 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0072_systemsettings_favicon_systemsettings_logo_contract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='browser_title',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Título da aba do navegador'),
        ),
    ]
