# Generated by Django 6.0.6 on 2026-07-07 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0073_systemsettings_browser_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='logo_login',
            field=models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='Logo das telas de login'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='logo_sidebar',
            field=models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='Logo da sidebar'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='logo_topbar',
            field=models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='Logo do topo (barra branca)'),
        ),
    ]
