# Generated by Django 6.0.6 on 2026-07-07 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0074_systemsettings_logo_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='color_primary',
            field=models.CharField(blank=True, default='', max_length=9, verbose_name='Cor principal'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='color_secondary',
            field=models.CharField(blank=True, default='', max_length=9, verbose_name='Cor secundária'),
        ),
    ]
