# Generated by Django 6.0.6 on 2026-07-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0075_systemsettings_color_primary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='logo_voucher',
            field=models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='Logo dos vouchers'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='voucher_template',
            field=models.JSONField(blank=True, default=list, verbose_name='Template padrão do voucher'),
        ),
    ]
