# Generated by Django 6.0.6 on 2026-07-09 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0076_systemsettings_logo_voucher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='logo_list',
            field=models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='Logo do PDF da lista de passageiros'),
        ),
    ]
