# Generated by Django 6.0.6 on 2026-07-09 00:45

import config_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0077_systemsettings_logo_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to=config_api.models.branding_logo_path, verbose_name='Favicon (ícone do navegador)'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='logo_contract',
            field=models.ImageField(blank=True, null=True, upload_to=config_api.models.branding_logo_path, verbose_name='Logo dos contratos'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='logo_list',
            field=models.ImageField(blank=True, null=True, upload_to=config_api.models.branding_logo_path, verbose_name='Logo do PDF da lista de passageiros'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='logo_login',
            field=models.ImageField(blank=True, null=True, upload_to=config_api.models.branding_logo_path, verbose_name='Logo das telas de login'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='logo_pdf',
            field=models.ImageField(blank=True, null=True, upload_to=config_api.models.branding_logo_path, verbose_name='Logo do PDF dos roteiros'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='logo_sidebar',
            field=models.ImageField(blank=True, null=True, upload_to=config_api.models.branding_logo_path, verbose_name='Logo da sidebar'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='logo_site',
            field=models.ImageField(blank=True, null=True, upload_to=config_api.models.branding_logo_path, verbose_name='Logo do site (vitrine)'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='logo_system',
            field=models.ImageField(blank=True, null=True, upload_to=config_api.models.branding_logo_path, verbose_name='Logo do tema (sistema)'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='logo_topbar',
            field=models.ImageField(blank=True, null=True, upload_to=config_api.models.branding_logo_path, verbose_name='Logo do topo (barra branca)'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='logo_voucher',
            field=models.ImageField(blank=True, null=True, upload_to=config_api.models.branding_logo_path, verbose_name='Logo dos vouchers'),
        ),
    ]
