# Generated by Django 6.0.6 on 2026-07-09 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0078_alter_systemsettings_favicon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigSpecialNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Necessidade especial',
                'ordering': ['name'],
            },
        ),
    ]
