# Generated by Django 6.0.6 on 2026-07-09 19:44

import config_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0079_configspecialneed'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='branding_crops',
            field=models.JSONField(blank=True, default=dict, verbose_name='Recortes das logos'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='favicon_original',
            field=models.ImageField(blank=True, null=True, upload_to=config_api.models.branding_logo_path),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='logo_contract_original',
            field=models.ImageField(blank=True, null=True, upload_to=config_api.models.branding_logo_path),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='logo_list_original',
            field=models.ImageField(blank=True, null=True, upload_to=config_api.models.branding_logo_path),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='logo_login_original',
            field=models.ImageField(blank=True, null=True, upload_to=config_api.models.branding_logo_path),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='logo_pdf_original',
            field=models.ImageField(blank=True, null=True, upload_to=config_api.models.branding_logo_path),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='logo_sidebar_original',
            field=models.ImageField(blank=True, null=True, upload_to=config_api.models.branding_logo_path),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='logo_site_original',
            field=models.ImageField(blank=True, null=True, upload_to=config_api.models.branding_logo_path),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='logo_system_original',
            field=models.ImageField(blank=True, null=True, upload_to=config_api.models.branding_logo_path),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='logo_topbar_original',
            field=models.ImageField(blank=True, null=True, upload_to=config_api.models.branding_logo_path),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='logo_voucher_original',
            field=models.ImageField(blank=True, null=True, upload_to=config_api.models.branding_logo_path),
        ),
    ]
