# Generated by Django 6.0.6 on 2026-07-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0080_systemsettings_branding_crops_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatingcompany',
            name='website',
            field=models.CharField(blank=True, max_length=300, verbose_name='Site'),
        ),
    ]
