# Generated by Django 6.0.6 on 2026-07-11 01:11

from django.db import migrations, models

SEED = [
    'Aéreo', 'Hospedagem', 'Transporte terrestre', 'Transporte marítimo', 'Guia',
    'Receptivo', 'Alimentação', 'Passeios', 'Ingressos', 'Seguro', 'Documentação',
    'Vistos', 'Taxas', 'Marketing', 'Brindes', 'Operação', 'Comissão',
    'Custo financeiro', 'Contingência', 'Outros',
]


def seed(apps, schema_editor):
    Cat = apps.get_model('config_api', 'ConfigCostCategory')
    for name in SEED:
        Cat.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0081_operatingcompany_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigCostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Categoria de custo',
                'verbose_name_plural': 'Categorias de custo',
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(seed, migrations.RunPython.noop),
    ]
