# Generated by Django 6.0.6 on 2026-07-11 01:50

from django.db import migrations, models

# (nome, capacidade, é casal)
SEED = [
    ('Interior Individual', 1, False),
    ('Interior Casal', 2, True),
    ('Externa Individual', 1, False),
    ('Externa Casal', 2, True),
    ('Varanda Casal', 2, True),
    ('Suíte Casal', 2, True),
]


def seed(apps, schema_editor):
    Cabin = apps.get_model('config_api', 'ConfigShipCabin')
    for name, cap, couple in SEED:
        Cabin.objects.get_or_create(name=name, defaults={'capacity': cap, 'is_couple': couple})


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0082_configcostcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigShipCabin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nome')),
                ('capacity', models.PositiveIntegerField(default=1, verbose_name='Capacidade (pessoas)')),
                ('is_couple', models.BooleanField(default=False, verbose_name='É para casal')),
            ],
            options={
                'verbose_name': 'Tipo de cabine',
                'verbose_name_plural': 'Tipos de cabine',
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(seed, migrations.RunPython.noop),
    ]
