# Generated by Django 6.0.6 on 2026-07-13 14:03

from django.db import migrations, models


DEFAULT_SEGMENTS = ['Voo total', 'Voo do guia', 'Ida', 'Volta']
DEFAULT_CLASSES = ['Econômica', 'Econômica Premium', 'Executiva', 'Primeira Classe']


def seed(apps, schema_editor):
    Segment = apps.get_model('config_api', 'ConfigFlightSegment')
    Klass = apps.get_model('config_api', 'ConfigFlightClass')
    for n in DEFAULT_SEGMENTS:
        Segment.objects.get_or_create(name=n)
    for n in DEFAULT_CLASSES:
        Klass.objects.get_or_create(name=n)


def unseed(apps, schema_editor):
    apps.get_model('config_api', 'ConfigFlightSegment').objects.filter(name__in=DEFAULT_SEGMENTS).delete()
    apps.get_model('config_api', 'ConfigFlightClass').objects.filter(name__in=DEFAULT_CLASSES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0083_configshipcabin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigFlightClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Classe aérea',
                'verbose_name_plural': 'Classes aéreas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConfigFlightSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Trecho aéreo',
                'verbose_name_plural': 'Trechos aéreos',
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(seed, unseed),
    ]
