# Generated by Django 6.0.6 on 2026-07-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0084_configflightclass_configflightsegment'),
    ]

    operations = [
        migrations.AddField(
            model_name='configpaymentplan',
            name='interest_tiers',
            field=models.JSONField(blank=True, default=list, verbose_name='Juros por faixa de parcelas'),
        ),
    ]
