# Generated by Django 6.0.6 on 2026-07-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0085_configpaymentplan_interest_tiers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configshipcabin',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Tipo de cabine', 'verbose_name_plural': 'Tipos de cabine'},
        ),
        migrations.AddField(
            model_name='configshipcabin',
            name='category',
            field=models.CharField(blank=True, db_index=True, default='', max_length=200, verbose_name='Categoria / setor'),
        ),
        migrations.AlterField(
            model_name='configshipcabin',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterUniqueTogether(
            name='configshipcabin',
            unique_together={('category', 'name')},
        ),
    ]
