# Generated by Django 6.0.6 on 2026-07-15 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0086_alter_configshipcabin_options_and_more'),
        ('itineraries', '0079_itineraryinventoryblock'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='configshipcabin',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='configaccommodation',
            name='itinerary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='itineraries.itinerary'),
        ),
        migrations.AddField(
            model_name='configshipcabin',
            name='itinerary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='itineraries.itinerary'),
        ),
        migrations.AlterField(
            model_name='configaccommodation',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AddConstraint(
            model_name='configaccommodation',
            constraint=models.UniqueConstraint(condition=models.Q(('itinerary__isnull', True)), fields=('name',), name='uniq_global_accom_name'),
        ),
        migrations.AddConstraint(
            model_name='configaccommodation',
            constraint=models.UniqueConstraint(fields=('itinerary', 'name'), name='uniq_roteiro_accom_name'),
        ),
        migrations.AddConstraint(
            model_name='configshipcabin',
            constraint=models.UniqueConstraint(condition=models.Q(('itinerary__isnull', True)), fields=('category', 'name'), name='uniq_global_cabin'),
        ),
        migrations.AddConstraint(
            model_name='configshipcabin',
            constraint=models.UniqueConstraint(fields=('itinerary', 'category', 'name'), name='uniq_roteiro_cabin'),
        ),
    ]
