# Generated by Django 6.0.6 on 2026-07-15 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0087_alter_configshipcabin_unique_together_and_more'),
        ('itineraries', '0079_itineraryinventoryblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='configflightclass',
            name='itinerary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='itineraries.itinerary'),
        ),
        migrations.AlterField(
            model_name='configflightclass',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Nome'),
        ),
        migrations.AddConstraint(
            model_name='configflightclass',
            constraint=models.UniqueConstraint(condition=models.Q(('itinerary__isnull', True)), fields=('name',), name='uniq_global_flightclass'),
        ),
        migrations.AddConstraint(
            model_name='configflightclass',
            constraint=models.UniqueConstraint(fields=('itinerary', 'name'), name='uniq_roteiro_flightclass'),
        ),
    ]
