# Generated by Django 5.2.15 on 2026-07-16 18:02

import config_api.models
import core.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0089_repoint_scoped_type_refs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=core.storages.public_media_storage, upload_to=config_api.models.airline_logo_path, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='configboatmedia',
            name='file',
            field=models.FileField(storage=core.storages.public_media_storage, upload_to=config_api.models.boat_media_path, verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='confighotelmedia',
            name='file',
            field=models.FileField(storage=core.storages.public_media_storage, upload_to=config_api.models.hotel_media_path, verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='favicon',
            field=models.ImageField(blank=True, null=True, storage=core.storages.public_media_storage, upload_to=config_api.models.branding_logo_path, verbose_name='Favicon (ícone do navegador)'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='favicon_original',
            field=models.ImageField(blank=True, null=True, storage=core.storages.public_media_storage, upload_to=config_api.models.branding_logo_path),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='logo_contract',
            field=models.ImageField(blank=True, null=True, storage=core.storages.public_media_storage, upload_to=config_api.models.branding_logo_path, verbose_name='Logo dos contratos'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='logo_contract_original',
            field=models.ImageField(blank=True, null=True, storage=core.storages.public_media_storage, upload_to=config_api.models.branding_logo_path),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='logo_list',
            field=models.ImageField(blank=True, null=True, storage=core.storages.public_media_storage, upload_to=config_api.models.branding_logo_path, verbose_name='Logo do PDF da lista de passageiros'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='logo_list_original',
            field=models.ImageField(blank=True, null=True, storage=core.storages.public_media_storage, upload_to=config_api.models.branding_logo_path),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='logo_login',
            field=models.ImageField(blank=True, null=True, storage=core.storages.public_media_storage, upload_to=config_api.models.branding_logo_path, verbose_name='Logo das telas de login'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='logo_login_original',
            field=models.ImageField(blank=True, null=True, storage=core.storages.public_media_storage, upload_to=config_api.models.branding_logo_path),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='logo_pdf',
            field=models.ImageField(blank=True, null=True, storage=core.storages.public_media_storage, upload_to=config_api.models.branding_logo_path, verbose_name='Logo do PDF dos roteiros'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='logo_pdf_original',
            field=models.ImageField(blank=True, null=True, storage=core.storages.public_media_storage, upload_to=config_api.models.branding_logo_path),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='logo_sidebar',
            field=models.ImageField(blank=True, null=True, storage=core.storages.public_media_storage, upload_to=config_api.models.branding_logo_path, verbose_name='Logo da sidebar'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='logo_sidebar_original',
            field=models.ImageField(blank=True, null=True, storage=core.storages.public_media_storage, upload_to=config_api.models.branding_logo_path),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='logo_site',
            field=models.ImageField(blank=True, null=True, storage=core.storages.public_media_storage, upload_to=config_api.models.branding_logo_path, verbose_name='Logo do site (vitrine)'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='logo_site_original',
            field=models.ImageField(blank=True, null=True, storage=core.storages.public_media_storage, upload_to=config_api.models.branding_logo_path),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='logo_system',
            field=models.ImageField(blank=True, null=True, storage=core.storages.public_media_storage, upload_to=config_api.models.branding_logo_path, verbose_name='Logo do tema (sistema)'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='logo_system_original',
            field=models.ImageField(blank=True, null=True, storage=core.storages.public_media_storage, upload_to=config_api.models.branding_logo_path),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='logo_topbar',
            field=models.ImageField(blank=True, null=True, storage=core.storages.public_media_storage, upload_to=config_api.models.branding_logo_path, verbose_name='Logo do topo (barra branca)'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='logo_topbar_original',
            field=models.ImageField(blank=True, null=True, storage=core.storages.public_media_storage, upload_to=config_api.models.branding_logo_path),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='logo_voucher',
            field=models.ImageField(blank=True, null=True, storage=core.storages.public_media_storage, upload_to=config_api.models.branding_logo_path, verbose_name='Logo dos vouchers'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='logo_voucher_original',
            field=models.ImageField(blank=True, null=True, storage=core.storages.public_media_storage, upload_to=config_api.models.branding_logo_path),
        ),
    ]
