# Generated by Django 6.0.6 on 2026-07-19 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0089_repoint_scoped_type_refs'),
    ]

    operations = [
        migrations.AddField(
            model_name='configexchangerate',
            name='rate_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cotação verificada em'),
        ),
    ]
