# Generated by Django 6.0.6 on 2026-07-21 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0091_operatingcompany_contract_review_open_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operatingcompany',
            name='contract_review_open_mode',
        ),
    ]
