# Generated by Django 6.0.6 on 2026-07-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0092_remove_operatingcompany_contract_review_open_mode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configpaymentplan',
            options={'ordering': ['-is_favorite', 'name'], 'verbose_name': 'Modelo de pagamento'},
        ),
        migrations.AddField(
            model_name='configpaymentplan',
            name='is_favorite',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Favorito'),
        ),
    ]
