# Generated by Django 5.2.15 on 2026-07-22 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0090_alter_airline_logo_alter_configboatmedia_file_and_more'),
        ('config_api', '0093_alter_configpaymentplan_options_and_more'),
    ]

    operations = [
    ]
