# Generated by Django 6.0.6 on 2026-07-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0095_configboatmedia_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatingcompany',
            name='sms_verification',
            field=models.BooleanField(default=False, verbose_name='Exigir verificação por SMS ao assinar'),
        ),
    ]
