# Generated by Django 6.0.6 on 2026-07-25 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0094_merge_20260722_0018'),
        ('config_api', '0096_operatingcompany_sms_verification'),
    ]

    operations = [
    ]
