# Generated by Django 6.0.6 on 2026-07-27 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0097_merge_20260725_1243'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(default='label', max_length=40, verbose_name='Tipo de documento')),
                ('model_code', models.CharField(max_length=80, verbose_name='Modelo')),
                ('draft_json', models.JSONField(blank=True, default=dict, verbose_name='Rascunho')),
                ('published_json', models.JSONField(blank=True, default=dict, verbose_name='Publicado')),
                ('version', models.PositiveIntegerField(default=0, verbose_name='Versão publicada')),
                ('history', models.JSONField(blank=True, default=list, verbose_name='Histórico')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração de modelo de documento',
                'verbose_name_plural': 'Configurações de modelos de documento',
                'constraints': [models.UniqueConstraint(fields=('document_type', 'model_code'), name='uniq_doc_template')],
            },
        ),
    ]
