# Generated by Django 6.0.6 on 2026-07-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0099_configjobrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserva_online_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Reserva online (%)')),
                ('pagamento_imediato_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Pagamento imediato (%)')),
                ('reserva_operadora_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Reserva exclusiva da operadora (%)')),
            ],
            options={
                'verbose_name': 'Configurações de reserva',
                'verbose_name_plural': 'Configurações de reserva',
            },
        ),
    ]
