# Generated by Django 6.0.6 on 2026-07-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0100_reservationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationsettings',
            name='deadline_hours',
            field=models.PositiveIntegerField(default=48, verbose_name='Prazo da reserva sem pagamento (horas)'),
        ),
    ]
