# Generated by Django 6.0.6 on 2026-08-01 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0101_reservationsettings_deadline_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatingcompany',
            name='agency_invite_email',
            field=models.BooleanField(default=False, verbose_name='Enviar convite por e-mail ao criar agência'),
        ),
    ]
