# Generated by Django 6.0.6 on 2026-08-01 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0102_operatingcompany_agency_invite_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OperatingCompanyContact',
        ),
    ]
