# Generated by Django 6.0.6 on 2026-08-03 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0103_delete_operatingcompanycontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='site_order_dir',
            field=models.CharField(choices=[('asc', 'Mais cedo primeiro'), ('desc', 'Mais tarde primeiro')], default='asc', max_length=4, verbose_name='Ordem por data de início'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='site_order_own_first',
            field=models.BooleanField(default=True, verbose_name='Produtos próprios primeiro'),
        ),
    ]
