# Generated by Django 6.0.6 on 2026-08-03 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0104_systemsettings_site_order_dir_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='site_order_by',
            field=models.CharField(choices=[('start_date', 'Data de início'), ('name', 'Nome'), ('created_at', 'Cadastro')], default='start_date', max_length=12, verbose_name='Ordenar por'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='site_order_dir',
            field=models.CharField(choices=[('asc', 'Crescente'), ('desc', 'Decrescente')], default='asc', max_length=4, verbose_name='Direção'),
        ),
    ]
