# Generated by Django 6.0.6 on 2026-08-06 17:14

import config_api.models
import core.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0105_systemsettings_site_order_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120, verbose_name='Nome')),
                ('url', models.URLField(max_length=500, verbose_name='Link do site')),
                ('logo', models.ImageField(blank=True, null=True, storage=core.storages.public_media_storage, upload_to=config_api.models.ai_logo_path, verbose_name='Logo')),
                ('is_favorite', models.BooleanField(db_index=True, default=False, verbose_name='Favorito')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Conector de IA',
                'verbose_name_plural': 'Conectores de IA',
                'ordering': ['-is_favorite', 'order', 'name'],
            },
        ),
    ]
