# Generated by Django 6.0.6 on 2026-08-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0108_systemsettings_list_notification_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='passenger_address_required',
            field=models.BooleanField(default=True, verbose_name='Endereço obrigatório no passageiro'),
        ),
    ]
