# Generated by Django 6.0.6 on 2026-08-19 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0109_systemsettings_passenger_address_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Bandeira')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aceita')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Bandeira de cartão',
                'verbose_name_plural': 'Bandeiras de cartão',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Gateway')),
                ('is_active', models.BooleanField(default=True, verbose_name='Em uso')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Gateway de pagamento',
                'verbose_name_plural': 'Gateways de pagamento',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GatewayFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installments', models.PositiveSmallIntegerField(verbose_name='Parcelas')),
                ('percent', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Taxa (%)')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='config_api.cardbrand', verbose_name='Bandeira')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='config_api.paymentgateway', verbose_name='Gateway')),
            ],
            options={
                'verbose_name': 'Taxa do gateway',
                'verbose_name_plural': 'Taxas dos gateways',
                'ordering': ['gateway__order', 'gateway__name', 'installments', 'brand__order', 'brand__name'],
                'constraints': [models.UniqueConstraint(fields=('gateway', 'brand', 'installments'), name='uniq_gateway_brand_parcela')],
            },
        ),
    ]
