# Generated by Django 6.0.6 on 2026-08-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0110_cardbrand_paymentgateway_gatewayfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='configpaymentmethod',
            name='kind',
            field=models.CharField(blank=True, choices=[('cartao_credito', 'Cartão de crédito'), ('cartao_debito', 'Cartão de débito'), ('pix', 'Pix'), ('boleto', 'Boleto'), ('transferencia', 'Transferência bancária'), ('dinheiro', 'Dinheiro'), ('cheque', 'Cheque'), ('link', 'Link de pagamento'), ('outro', 'Outro')], default='', max_length=30, verbose_name='Tipo'),
        ),
    ]
