# Generated by Django 6.0.6 on 2026-08-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0112_kind_das_formas_existentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgateway',
            name='payment_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Link de pagamento'),
        ),
    ]
