# Generated by Django 6.0.6 on 2026-08-19 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0113_paymentgateway_payment_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentgateway',
            name='payment_url',
        ),
    ]
