# Generated by Django 6.0.6 on 2026-07-08 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0040_passengerlist_default_airports'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocks', models.JSONField(blank=True, default=None, null=True, verbose_name='Blocos do voucher')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('passenger_list', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voucher', to='trips.passengerlist')),
            ],
            options={
                'verbose_name': 'Voucher da lista',
                'verbose_name_plural': 'Vouchers das listas',
            },
        ),
    ]
