# Generated by Django 6.0.6 on 2026-07-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do template')),
                ('blocks', models.JSONField(blank=True, default=list, verbose_name='Blocos')),
                ('is_default', models.BooleanField(db_index=True, default=False, verbose_name='Template padrão')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Template de voucher',
                'verbose_name_plural': 'Templates de voucher',
                'ordering': ['-is_default', 'name'],
            },
        ),
    ]
