# Generated by Django 6.0.6 on 2026-07-08 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0002_vouchertemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherFlightConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_key', models.CharField(db_index=True, max_length=200, verbose_name='Voucher (passageiro/casal)')),
                ('image', models.ImageField(upload_to='vouchers/flight_confirmations/', verbose_name='Confirmação do voo')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_confirmations', to='vouchers.voucherlist')),
            ],
            options={
                'verbose_name': 'Confirmação de voo do voucher',
                'verbose_name_plural': 'Confirmações de voo dos vouchers',
                'unique_together': {('voucher', 'entry_key')},
            },
        ),
    ]
