# Generated by Django 6.0.6 on 2026-07-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0003_voucherflightconfirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherlist',
            name='status',
            field=models.CharField(choices=[('em_edicao', 'Em edição'), ('publicado', 'Publicado')], db_index=True, default='em_edicao', max_length=20, verbose_name='Status'),
        ),
    ]
