# Generated by Django 6.0.6 on 2026-07-08 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0004_voucherlist_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_key', models.CharField(db_index=True, max_length=200, verbose_name='Voucher (passageiro/casal)')),
                ('downloaded_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='vouchers.voucherlist')),
            ],
            options={
                'verbose_name': 'Download de voucher',
                'verbose_name_plural': 'Downloads de vouchers',
                'unique_together': {('voucher', 'entry_key')},
            },
        ),
    ]
