# Generated by Django 6.0.6 on 2026-07-08 23:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0005_voucherdownload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voucherdownload',
            options={'ordering': ['-downloaded_at'], 'verbose_name': 'Download de voucher', 'verbose_name_plural': 'Downloads de vouchers'},
        ),
        migrations.AlterUniqueTogether(
            name='voucherdownload',
            unique_together={('voucher', 'entry_key', 'user')},
        ),
        migrations.AddField(
            model_name='voucherdownload',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='Vezes baixado'),
        ),
    ]
