# Generated by Django 5.2.15 on 2026-07-16 18:02

import core.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0007_flight_confirmation_multi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucherflightconfirmation',
            name='image',
            field=models.ImageField(storage=core.storages.public_media_storage, upload_to='vouchers/flight_confirmations/', verbose_name='Confirmação do voo'),
        ),
    ]
