# Generated by Django 6.0.6 on 2026-07-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0008_alter_voucherflightconfirmation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherlist',
            name='kit_addresses',
            field=models.JSONField(blank=True, default=dict, verbose_name='Endereços das etiquetas do kit'),
        ),
    ]
