# Generated by Django 6.0.5 on 2026-06-01 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data/Hora')),
                ('user_display', models.CharField(blank=True, max_length=200, verbose_name='Usuário')),
                ('action', models.CharField(choices=[('create', 'Criado'), ('update', 'Atualizado'), ('delete', 'Apagado')], db_index=True, max_length=20, verbose_name='Ação')),
                ('model_name', models.CharField(db_index=True, max_length=100, verbose_name='Modelo')),
                ('model_label', models.CharField(blank=True, max_length=100, verbose_name='Tipo de registro')),
                ('object_id', models.CharField(blank=True, max_length=50, verbose_name='ID')),
                ('object_repr', models.CharField(blank=True, max_length=500, verbose_name='Descrição')),
                ('changes', models.JSONField(default=dict, verbose_name='Alterações')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de auditoria',
                'ordering': ['-timestamp'],
            },
        ),
    ]
