# Generated by Django 6.0.5 on 2026-06-22 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Criado'), ('update', 'Atualizado'), ('delete', 'Apagado'), ('download', 'Baixado'), ('upload', 'Enviado'), ('login', 'Login'), ('logout', 'Logout'), ('view', 'Visitou')], db_index=True, max_length=20, verbose_name='Ação'),
        ),
    ]
