# Generated by Django 6.0.5 on 2026-06-23 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='geo_city',
            field=models.CharField(blank=True, max_length=120, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='geo_country',
            field=models.CharField(blank=True, max_length=120, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='geo_precise',
            field=models.BooleanField(default=False, verbose_name='Localização precisa (navegador)'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
    ]
