# Generated by Django 6.0.5 on 2026-06-23 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_auditlog_geo_city_auditlog_geo_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='geo_address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Endereço'),
        ),
    ]
