# Generated by Django 6.0.5 on 2026-06-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0007_auditlog_geo_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Criado'), ('update', 'Atualizado'), ('delete', 'Apagado'), ('restore', 'Restaurado'), ('purge', 'Removido definitivamente'), ('download', 'Baixado'), ('upload', 'Enviado'), ('login', 'Login'), ('logout', 'Logout'), ('view', 'Visitou')], db_index=True, max_length=20, verbose_name='Ação'),
        ),
    ]
