# Generated by Django 6.0.6 on 2026-07-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0013_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='source',
            field=models.CharField(blank=True, choices=[('system', 'Sistema'), ('user', 'Usuário'), ('csv', 'CSV')], db_index=True, default='', max_length=10, verbose_name='Origem'),
        ),
    ]
