# Generated by Django 6.0.6 on 2026-07-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0014_auditlog_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Criado'), ('update', 'Atualizado'), ('delete', 'Apagado'), ('restore', 'Restaurado'), ('purge', 'Removido definitivamente'), ('merge', 'Mesclado'), ('download', 'Baixado'), ('upload', 'Enviado'), ('rename', 'Renomeado'), ('share', 'Compartilhado'), ('transfer', 'Transferido'), ('send', 'Enviado p/ assinatura'), ('sign', 'Assinado'), ('reopen', 'Voltou p/ edição'), ('publish', 'Publicado'), ('unpublish', 'Despublicado'), ('approve', 'Aprovado'), ('invoice', 'Faturado'), ('login', 'Login'), ('logout', 'Logout'), ('view', 'Visitou')], db_index=True, max_length=20, verbose_name='Ação'),
        ),
    ]
