# Generated by Django 6.0.6 on 2026-07-29 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0015_alter_auditlog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditActorAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(db_index=True, max_length=500, unique=True, verbose_name='Arquivo de origem')),
                ('image', models.ImageField(upload_to='audit_avatars/', verbose_name='Foto congelada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='auditlog',
            name='actor_avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='audit.auditactoravatar'),
        ),
    ]
